### PR TITLE
dark mode added

### PR DESCRIPTION
**Pull request by rjoydip**
image

### CODE REVIEW

**Comment by rjoydip** [comment]
It's working fine in github too.

**Comment by evildabbit** [comment]
@rjoydip Remove `yarn-error.log`

**Comment by rjoydip** [comment]
> @rjoydip Remove `yarn-error.log`

Done https://github.com/anuraghazra/github-readme-stats/pull/181/commits/6530e43544aecf9b11b54118475d475ee0f62eed

**Comment by filiptronicek** [comment]
Anyway we can try it @rjoydip?

**Comment by anuraghazra** [comment]
Thanks @rjoydip for the PR. 

Well, even If this works I don't think this would work instantly because of our minimum 30min cache. 🤔

**Comment by anuraghazra** [comment]
@rjoydip can you please give a working demo also a video/screenshot because it's not working on my side.

**Comment by rjoydip** [comment]
@anuraghazra You can check below links.
https://github-readme-stats.rjoydip.vercel.app/api?username=rjoydip
https://github-readme-stats.rjoydip.vercel.app/api?username=rjoydip&show_icons=true
https://github-readme-stats.rjoydip.vercel.app/api/top-langs?username=rjoydip
https://github-readme-stats.rjoydip.vercel.app/api/pin?username=rjoydip&repo=neon-hello-world-starter

**Comment by anuraghazra** [comment]
@rjoydip yeah looks like working on browser but not in github

**Comment by rjoydip** [comment]
It might be the browser cache issue. Can you try incognito mode?
It's working in github. Please check below screenshot.

github com_rjoydip_rjoydip_blob_master_README md

**Comment by anuraghazra** [comment]
> It might be the browser cache issue. Can you try incognito mode?
> It's working in github. Please check below screenshot.
> 
> github com_rjoydip_rjoydip_blob_master_README md

I'm just changing the URL to bust the cache with &v=2

**Comment by rjoydip** [comment]
Yes, that should work.

**Comment by anuraghazra** [comment]
> Yes, that should work.

Isn't working

**Pull request closed without merging**
