### PR TITLE
Feature/grs 1955 change commonjs imports

### PR DESCRIPTION
**Pull request by rsk2**

### CODE REVIEW

**Comment by rsk2** [comment]
@rickstaa it says that the test/build is failing. 

image

That seems like it is coming from the jest library.

**Comment by rickstaa** [comment]
@rsk2 I checked this PR, and something weird is happening. It looks like not all changes in https://github.com/rsk2/github-readme-stats/pull/1/files are found in this PR. I think this is because merge conflicts in [275ec70](https://github.com/anuraghazra/github-readme-stats/pull/1995/commits/275ec7001b4ba1d055be692f43e59fe3c52fa3b9) were not correctly dealt with.

image

Still is 

image

Which is incorrect and will throw an error.

**Comment by rickstaa** [comment]
I fixed the merge conflicts with a force push (see https://github.com/anuraghazra/github-readme-stats/compare/275ec7001b4ba1d055be692f43e59fe3c52fa3b9..0b3f701c005228c8723918aeea34f25ede6166ad).

**Comment by rickstaa** [comment]
All problems are fixed now. @rsk2 Thanks a lot for your contribution! 🚀 It greatly improves the codebase.

**Comment by rsk2** [comment]
Thanks for your help and guidance @rickstaa!

**Pull request merged**
