### PR TITLE
Theme: add new some themes

### PR DESCRIPTION
**Pull request by IRMABaitussalam**

### CODE REVIEW

**Comment by rickstaa** [comment]
@IRMABaitussalam, although I love the themes, I think it is a bit hard for us to review the popularity of your themes when you included so many in your PRs. 

@qwerty541, @anuraghazra, what do you think should update the theme preview CI to display a warning when multiple themes are added or maybe let it add a `batch` label? I initially added the option for multiple themes to allow people to supply both a dark an light version of a theme 🤔.

**Review by qwerty541 — COMMENTED** [review]
> @IRMABaitussalam, although I love the themes, I think it is a bit hard for us to review the popularity of your themes when you included so many in your PRs.
> 
> @qwerty541, @anuraghazra, what do you think should update the theme preview CI to display a warning when multiple themes are added or maybe let it add a `batch` label? I initially added the option for multiple themes to allow people to supply both a dark an light version of a theme 🤔.

@rickstaa I think that we can update our themes contribution guidelines wtih adding a new rule  - one theme per pull request. May be sutiations when user wants to add some versions of same theme can be exceptional. I hope it will be enough for now. If users continue adding pull requests with batch of themes we can update our theme review script to request changes instead of approving in such cases. I can open pull request with changes into documentation if you are up to merge.

**Comment by rickstaa** [comment]
> > @IRMABaitussalam, although I love the themes, I think it is a bit hard for us to review the popularity of your themes when you included so many in your PRs.
> > @qwerty541, @anuraghazra, what do you think should update the theme preview CI to display a warning when multiple themes are added or maybe let it add a `batch` label? I initially added the option for multiple themes to allow people to supply both a dark an light version of a theme 🤔.
> 
> @rickstaa I think that we can update our themes contribution guidelines wtih adding a new rule - one theme per pull request. May be sutiations when user wants to add some versions of same theme can be exeptional. I hope it will be enough for now. If users continue adding pull requests with batch of themes we can update our theme review script to request changes instead of approving in such cases. I can open pull request with changes into documentation if you are up to merge.

That sounds like a good start! How should we deal with dark and light themes? Do we still allow, for example, `github_dark` and `github_light` in one pull request? If not, we can update the pull request action to request changes 👍🏻.

**Comment by qwerty541** [comment]
> > > @IRMABaitussalam, although I love the themes, I think it is a bit hard for us to review the popularity of your themes when you included so many in your PRs.
> > > @qwerty541, @anuraghazra, what do you think should update the theme preview CI to display a warning when multiple themes are added or maybe let it add a `batch` label? I initially added the option for multiple themes to allow people to supply both a dark an light version of a theme 🤔.
> > 
> > 
> > @rickstaa I think that we can update our themes contribution guidelines wtih adding a new rule - one theme per pull request. May be sutiations when user wants to add some versions of same theme can be exeptional. I hope it will be enough for now. If users continue adding pull requests with batch of themes we can update our theme review script to request changes instead of approving in such cases. I can open pull request with changes into documentation if you are up to merge.
> 
> That sounds like a good start! How should we deal with dark and light themes? Do we still allow, for example, `github_dark` and `github_light` in one pull request? If not, we can update the pull request action to request changes 👍🏻.

> How should we deal with dark and light themes? 

I think that sutiations when user wants to add some versions of same theme can be exceptional.

> If not, we can update the pull request action to request changes 👍🏻.

If users continue adding pull requests with batch of themes after changes in documentation we can update our theme review script to request changes instead of approving in such cases.

**Comment by qwerty541** [comment]
@rickstaa I have just opened two pull requests with documentation updated (https://github.com/anuraghazra/github-readme-stats/pull/3394 and https://github.com/anuraghazra/github-readme-stats/pull/3395). Please check it out.

**Comment by anuraghazra** [comment]
We are currently pausing addition of new themes. If this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

**Pull request closed without merging**
