### PR TITLE
Silent Vercel bot

### PR DESCRIPTION
**Pull request by ruchernchong**
This is to silent the bot from commenting on each commit. 

The bot is commenting on commits which is not quite useful.
image

### CODE REVIEW

**Review by Zo-Bro-23 — APPROVED** [review]
@rickstaa this is actually useful! Thoughts?

I didn't know this was even an option lol

**Comment by rickstaa** [comment]
> @rickstaa this is actually useful! Thoughts?
> 
> I didn't know this was even an option lol

I'm fine with this if Vercel still gives me a message when a deployment fails. We have to test this out👍.

**Comment by anuraghazra** [comment]
This might also silent the comments on Pull Requests.

**Comment by ruchernchong** [comment]
> This might also silent the comments on Pull Requests.

Looking at the other pull requests, I only see the bot commenting on authorising the deployment on Vercel.

I do get that comment with the pull request from this upstream whenever I want to keep my fork up to date.

**Comment by rickstaa** [comment]
As @anuraghazra rightfully pointed out, this is currently undesirable since there currently needs to be a way to prevent these integration comments on commits (see https://vercel.com/guides/how-to-prevent-vercel-github-comments). As explained in https://vercel.com/guides/how-to-prevent-vercel-github-comments, to get this feature, we have to request it using https://vercel.com/guides/where-to-submit-feature-requests. Closing this for now.

**Comment by Zo-Bro-23** [comment]
> As @anuraghazra rightfully pointed out, this is currently undesirable since there currently needs to be a way to prevent these integration comments on commits (see https://vercel.com/guides/how-to-prevent-vercel-github-comments). As explained in https://vercel.com/guides/how-to-prevent-vercel-github-comments, to get this feature, we have to request it using https://vercel.com/guides/where-to-submit-feature-requests. Closing this for now.

I'm sorry, but I don't understand you. If a deployment fails, then we can see that on the GitHub and Vercel dashboards, and @anuraghazra gets an email, since he's on the GRS Vercel Team. I find it extremely annoying when Vercel comments on PRs and commits, since I get an email for each comment. I thought this PR will disable this, but maybe I'm wrong. I don't know much about the Vercel GitHub integration; I usually deploy to Vercel from the command line.

**Comment by ruchernchong** [comment]
> > As @anuraghazra rightfully pointed out, this is currently undesirable since there currently needs to be a way to prevent these integration comments on commits (see https://vercel.com/guides/how-to-prevent-vercel-github-comments). As explained in https://vercel.com/guides/how-to-prevent-vercel-github-comments, to get this feature, we have to request it using https://vercel.com/guides/where-to-submit-feature-requests. Closing this for now.
> 
> 
> 
> I'm sorry, but I don't understand you. If a deployment fails, then we can see that on the GitHub and Vercel dashboards, and @anuraghazra gets an email, since he's on the GRS Vercel Team. I find it extremely annoying when Vercel comments on PRs and commits, since I get an email for each comment. I thought this PR will disable this, but maybe I'm wrong. I don't know much about the Vercel GitHub integration; I usually deploy to Vercel from the command line.

Exactly my sentiments and hence created this PR to silent these comments which are not informational enough anyway.

**Comment by ruchernchong** [comment]
> As @anuraghazra rightfully pointed out, this is currently undesirable since there currently needs to be a way to prevent these integration comments on commits (see https://vercel.com/guides/how-to-prevent-vercel-github-comments). As explained in https://vercel.com/guides/how-to-prevent-vercel-github-comments, to get this feature, we have to request it using https://vercel.com/guides/where-to-submit-feature-requests. Closing this for now.

Totally understand regarding having able to see the failed PRs. But I had my own repos silencing the comments on commits and they still do show errors in PRs as intended.

**Pull request closed without merging**
