### PR TITLE
style(theme): Add transparent theme

### PR DESCRIPTION
**Pull request by Isaiah-Hamilton**
A transparent theme for #1100. This theme uses the default theme colors but with a transparent background.

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title_color: <code>#2f80ed</code> | icon_color: <code>#4c71f2</code> | text_color: <code>#000</code> | bg_color: <code>#00000000</code>
      
      
Link: https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=2f80ed&icon_color=4c71f2&text_color=000&bg_color=00000000&show_icons=true

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=2f80ed&icon_color=4c71f2&text_color=000&bg_color=00000000&show_icons=true)
      
      
  
> Hi thanks for the theme contribution, please read our theme contribution guidelines

  
> We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 
  
> Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

**Comment by AlphaNecron** [comment]
Please fix your theme. 
image

**Comment by AlphaNecron** [comment]
Versions don't matter, if the user chose light theme then the repo with dark theme for repo card enabled wouldn't work perfectly, and vice versa.

**Comment by Isaiah-Hamilton** [comment]
My goal was to make it dynamic so that it would work with both a light theme and a dark theme, but I haven't found a way to make that possible. Unless someone knows how to make that possible, I will close the pr.

**Comment by Aragas** [comment]
Just use neutral colors that work in both dark and light themes, like this
[Anuraghazra's GitHub stats](https://github.com/anuraghazra/github-readme-stats)

**Pull request closed without merging**
