### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by dev-abulhassan**

### CODE REVIEW

**Comment by Zo-Bro-23** [comment]
@rickstaa can you please check out why the preview workflow is failing? I'm a bit busy now, and it's alright if you're busy too, but just give it a look when you're free. Thanks!

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:x: Theme PR does not adhere to our guidelines.
      
## Test results
      
- :x: adnan_theme

      
**Result:** :x: Some themes are invalid.


  
Unfortunately, your theme PR contains an error or does not adhere to our [theme guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution). Please fix the issues below, and we will review your  
 PR again. This pull request will **automatically close in 20 days** if no changes are made. After this time, you must re-open the PR for it to be reviewed.

      
      
## Details
      
        
### Adnan_theme theme preview
        
        
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=14354F&bcolor=0A1E2D).
- :warning: `text_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=153B59&bcolor=0A1E2D).


        
title_color: <code>#14354F</code> | icon_color: <code>#5FABEE</code> | text_color: <code>#153B59</code> | bg_color: <code>#0A1E2D</code> | border_color: <code>#85A4C0</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=14354F&text_color=153B59&icon_color=5FABEE&border_color=85A4C0&bg_color=0A1E2D&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=14354F&text_color=153B59&icon_color=5FABEE&border_color=85A4C0&bg_color=0A1E2D&show_icons=true)

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/2543#issuecomment-1455078812) comment above for more information.

**Comment by dev-abulhassan** [comment]
ok

**Pull request closed without merging**
