### PR TITLE
Add wakatime card

### PR DESCRIPTION
**Pull request by WillianRod**
## Wakatime card

This PR allows users to create a card displaying their wakatime stats and progress. Wakatime is a tool to track developement time.

### CODE REVIEW

**Comment by HPaulson** [comment]
Was actually going to suggest something with waka, thanks so much for the PR!! This is great!

**Comment by anuraghazra** [comment]
Hi @WillianRod This looks awesome! 

BTW do we need WakaTime specific API keys to access users informations?

**Comment by WillianRod** [comment]
> Hi @WillianRod This looks awesome!
> 
> BTW do we need WakaTime specific API keys to access users informations? (i never used wakatime)

@anuraghazra No, you can get this information from a public api like this exemple [here](https://wakatime.com/api/v1/users/willianrod/stats/last_7_days?timeout=15&is_including_today=true) that list all public information of your account in the last 7 days.

You only will need an API key If you want to get more information, like which the time spent on every git repo you worked last week.

**Comment by anuraghazra** [comment]
> No, you can get this information from a public api like this exemple here that list all public information of your account in the last 7 days.

What's the rate limit?

**Comment by WillianRod** [comment]
> What's the rate limit?

@anuraghazra I couldn't find any information about that. In [wakatime developer docs](https://wakatime.com/developers) shows that they rave a response code to "Too many requests" but, they don't say how many request I can make per hour. I tried see if they put that information on response headers, but nothing showed up.

image

I'll try to contact them to see how many requests per minute|hour I can make to this route. I'll keep you posted.

**Comment by alanhamlett** [comment]
The average request rate cannot exceed 5 requests per second. A request to any url at http://wakatime.com counts towards the 5/second limit. If you go over this limit, you'll receive a 429 error response for a few minutes until your requests go back below the limit.

API docs are updated now with the 5/second limit.

**Comment by douglasjunior** [comment]
> Was actually going to suggest something with waka, thanks so much for the PR!! This is great, however I'd ask that you add a compact view similar to the compact language card... have all languages color coded by % on one line, with the lang names below. I think the current card is nice, but a compact option would be even better! Ex: `&layout=compact`
> 

I think that this could be done in another PR.

**Comment by anuraghazra** [comment]
> The average request rate cannot exceed 5 requests per second. A request to any url at http://wakatime.com counts towards the 5/second limit. If you go over this limit, you'll receive a 429 error response for a few minutes until your requests go back below the limit.
> 
> API docs are updated now with the 5/second limit.

Ahhh okay got it.. Thanks for the information!!

**Comment by anuraghazra** [comment]
I would just suggest that we don't need the percentages in the progressbar if we are showing the hours, so let's remove the percentages.

**Comment by WillianRod** [comment]
> I would just suggest that we don't need the percentages in the progressbar if we are showing the hours, so let's remove the percentages.

Removed the percentages.



I'll try to submit this weekend another pull request with a compact layout of this.

**Comment by HPaulson** [comment]
@anuraghazra Any update on a possible merge of this PR?

**Comment by WillianRod** [comment]
Any updates?

**Comment by anuraghazra** [comment]
Hey @WillianRod sorry for the late response. This is really awesome feature to be added, i've done some refactors and added basic tests, will test it on preview end and merge this now.

**Comment by anuraghazra** [comment]
Testing



With Theme

**Comment by anuraghazra** [comment]
Okay LGTM! thanks again @WillianRod  :D 💯

**Comment by Bas950** [comment]
@WillianRod it doesn't seem to work with mine... https://github-readme-stats.vercel.app/api/wakatime?username=Bas950

```
Something went wrong! file an issue at https://git.io/JJmN9
Request failed with status code 404
```

**Comment by Bas950** [comment]
> @WillianRod it doesn't seem to work with mine... https://github-readme-stats.vercel.app/api/wakatime?username=Bas950
> 
> ```
> Something went wrong! file an issue at https://git.io/JJmN9
> Request failed with status code 404
> ```

nvm fixed it, you need to setup your profile I guess...

**Pull request merged**
