### PR TITLE
Add `nebular-cosmic` theme

### PR DESCRIPTION
**Pull request by zankevich**
[Preview](https://github-readme-stats.vercel.app/api?username=anuraghazra&show_icons=true&title_color=ceceeb&icon_color=b18aff&text_color=ffffff&bg_color=323259
)

### CODE REVIEW

**Comment by anuraghazra** [comment]
Hi @zankevich thanks for the theme contribution, this looks nice, but kinda seem like the "shades-of-purple" theme just with white text

**Comment by anuraghazra** [comment]
Theme preview (bot) 
        Cannot create theme preview

**Comment by zankevich** [comment]
> shades-of-purple

What do you think about this one?
[Preview](https://github-readme-stats.vercel.app/api?username=anuraghazra&show_icons=true&title_color=F12727&icon_color=6796E6&text_color=CD8D8D&bg_color=580000)

Inspired by `Red` theme from VC Code.

**Comment by anuraghazra** [comment]
> > shades-of-purple
> 
> What do you think about this one?
> [Preview](https://github-readme-stats.vercel.app/api?username=anuraghazra&show_icons=true&title_color=F12727&icon_color=6796E6&text_color=CD8D8D&bg_color=580000)
> 
> Inspired by `Red` theme from VC Code.
> @anuraghazra

Nah maybe just use the Red from vscode without modifications

**Comment by zankevich** [comment]
> > > shades-of-purple
> > 
> > 
> > What do you think about this one?
> > [Preview](https://github-readme-stats.vercel.app/api?username=anuraghazra&show_icons=true&title_color=F12727&icon_color=6796E6&text_color=CD8D8D&bg_color=580000)
> > Inspired by `Red` theme from VC Code.
> > @anuraghazra
> 
> Nah maybe just use the Red from vscode without modifications

OK. I give up ;(

**Pull request closed without merging**
