### PR TITLE
Add Red-Velvet Theme

### PR DESCRIPTION
**Pull request by SanjayDevTech**
In the existing themes, there is no red combination.
So I tried a Red-White combination

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title-color: <code>#fa1f17</code>
      
icon-color: <code>#fa1f17</code>
      
text-color: <code>#fd544e</code>
      
bg-color: <code>#fffefe</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=fa1f17&icon_color=fa1f17&text_color=fd544e&bg_color=fffefe&show_icons=true)

**Comment by anuraghazra** [comment]
Hi @SanjayDevTech thanks for the contribution, theme looks good, but we are currently only considering good mix of colors and themes which are available as official VSCode themes.

Also Note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 

Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info



If you wanted to use these colors you can directly use the link.

```
[![](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=fa1f17&icon_color=fa1f17&text_color=fd544e&bg_color=fffefe&show_icons=true)](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=fa1f17&icon_color=fa1f17&text_color=fd544e&bg_color=fffefe&show_icons=true)
```

**Comment by SanjayDevTech** [comment]
🤩 oh thanks for the info.. I didn't know we can use custom themes....

**Comment by anuraghazra** [comment]
Yup! feel free to open any other theme contribution if you like. We don't have any gradient background themes you can try out some combinations.

Use preexisting gradient color pallets.

**Pull request closed without merging**
