### PR TITLE
Added jedi Theme

### PR DESCRIPTION
**Pull request by littlebru**
Hello @anuraghazra, I had the idea to create a Jedi theme, it looks like this.

Hope you like

image

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)

**Comment by anuraghazra** [comment]
Hi @littlebru the colors does not really look good. that contrasted red with black bg is hurting the eyes.

**Comment by littlebru** [comment]
oh, I'm sorry :(
I also found it after spending a long time looking at him lol
I will think of something better 😅

**Comment by anuraghazra** [comment]
> oh, I'm sorry :(
> I also found it after spending a long time looking at him lol
> I will think of something better

I would highly recommend adding any VScode or any popular Editor theme instead.

**Comment by anuraghazra** [comment]
Feel free to open another PR with a cool looking theme. closing this for now.

TIP: You can now use gradients too. :p

**Comment by littlebru** [comment]
> Feel free to open another PR with a cool looking theme. closing this for now.
> 
> TIP: You can now use gradients too. :p

sure, thanks for the tip, based on an editor seems like a better idea.

I loved the gradient I will use in my readme 🤩

**Pull request closed without merging**
