### PR TITLE
CI: Fix pull requests labeler workflow error

### PR DESCRIPTION
**Pull request by qwerty541**
Error:

https://github.com/anuraghazra/github-readme-stats/actions/runs/5435984321/workflow

Edited file does not show same error:

https://github.com/anuraghazra/github-readme-stats/actions/runs/5438592304/workflow

### CODE REVIEW

**Comment by rickstaa** [comment]
@qwerty541 This bug should not exist according to the documentation. I tried it with other triggers, and it does not show up (see https://github.com/rickstaa/issues-permission-error/actions/workflows/issues-permission-test-read.yml). Maybe it happens when the `pull_request_target` trigger is used. Would it be possible for you to create a PR on https://github.com/rickstaa/issues-permission-error so we can test this behaviour and file a bug report with @github?

**Review by qwerty541 — COMMENTED** [review]
> @qwerty541 This bug should not exist according to the documentation. I tried it with other triggers, and it does not show up (see https://github.com/rickstaa/issues-permission-error/actions/workflows/issues-permission-test-read.yml). Maybe it happens when the `pull_request_target` trigger is used. Would it be possible for you to create a PR on https://github.com/rickstaa/issues-permission-error so we can test this behaviour and file a bug report with @github?

I have opened pull request https://github.com/rickstaa/issues-permission-error/pull/1 and all checks passed. But i noticed that there are no `actions/labeler` inside your repository. As you see this error happens only with one of our workflows which contains pull requests labeler. I think that error can be connected to some `actions/labeler` requirements, but their documentation tells that it needs only `contents`: `read` and `pull-requests`: `write` permissions. Very strange.

**Comment by qwerty541** [comment]
Looks like there are no more such errors happens with this workflow: https://github.com/anuraghazra/github-readme-stats/actions/workflows/label-pr.yml.

This pull request is no actual for now.

**Comment by rickstaa** [comment]
@qwerty541 strange 🤔. Maybe we can close it for now?

**Comment by qwerty541** [comment]
> @qwerty541 strange thinking. Maybe we can close it for now?

@rickstaa Yes, for now it should be closed.

**Pull request closed without merging**
