### PR TITLE
Contribute new theme 'pale'

### PR DESCRIPTION
**Pull request by ioalex**
Contributing a new theme called 'pale'. 😄

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title-color: <code>#93FAF5</code>
      
icon-color: <code>#7D6B91</code>
      
text-color: <code>#989FCE</code>
      
bg-color: <code>#2728308</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=93FAF5&icon_color=7D6B91&text_color=989FCE&bg_color=2728308&show_icons=true)

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title-color: <code>#93FAF5</code>
      
icon-color: <code>#7D6B91</code>
      
text-color: <code>#989FCE</code>
      
bg-color: <code>#272838</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=93FAF5&icon_color=7D6B91&text_color=989FCE&bg_color=272838&show_icons=true)

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title-color: <code>#93FAF5</code>
      
icon-color: <code>#7D6B91</code>
      
text-color: <code>#989FCE</code>
      
bg-color: <code>#272838</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=93FAF5&icon_color=7D6B91&text_color=989FCE&bg_color=272838&show_icons=true)

**Comment by ioalex** [comment]
@anuraghazra Awaiting approval 😸

**Comment by anuraghazra** [comment]
Hi thanks for opening the theme contribution @ioalex 
sorry but we already have similar "pale" themes in our list 
image

**Comment by ioalex** [comment]
Understood! Thanks for reviewing this pull request. 😄

**Pull request closed without merging**
