### PR TITLE
docs: Correct language code in readme filename

### PR DESCRIPTION
**Pull request by Luminous-Coder**
Change readme filename from "cn" to "zh-CN" that represents Chinese variant of Chinese; follow the format used for "pt-BR".

### CODE REVIEW

**Comment by Zo-Bro-23** [comment]
Why only Chinese though? Do it for all languages then.

**Comment by Luminous-Coder** [comment]
> Why only Chinese though? Do it for all languages then.

I don't know which variants those translations use.

**Comment by Zo-Bro-23** [comment]
> > Why only Chinese though? Do it for all languages then.
> 
> I don't know which variants those translations use.

Fair point. We'll see what we can do.

**Comment by rickstaa** [comment]
> > > Why only Chinese though? Do it for all languages then.
> > 
> > 
> > I don't know which variants those translations use.
> 
> Fair point. We'll see what we can do.

@Luminous-Coder, thanks for your PR. However, the translation files will be deprecated when https://github.com/anuraghazra/github-readme-stats/pull/2489 is merged.

**Comment by Luminous-Coder** [comment]
> 

Got it.

If https://github.com/anuraghazra/github-readme-stats/pull/2489 is merged, people translate on Crowdin and GitHub action will automatically update, right?

**Comment by Zo-Bro-23** [comment]
> > > > > Why only Chinese though? Do it for all languages then.
> > > > 
> > > > 
> > > > I don't know which variants those translations use.
> > > 
> > > 
> > > Fair point. We'll see what we can do.
> > 
> > 
> > @Luminous-Coder, thanks for your PR. However, the translation files will be deprecated when #2489 is merged.
> 
> Got it.
> 
> If #2489 is merged, people translate on Crowdin and GitHub action will automatically update, right?

Yes. Closing this for now.

**Comment by lumynou5** [comment]
Hello, I notice the Crowdin PR ended up being closed, and the current `CONTRIBUTING.md` specifies how to contribute to the translation of the software strings but not the documents.  It also says the language codes should follow ISO 639-1, and `cn` obviously doesn't.  Deprecating it in the API would be a big change, but maybe we can at least correct that in the documents?  If so, please consider to reopen this PR.

---

> Why only Chinese though? Do it for all languages then.

This question has another answer actually: Some languages don't need to have a region code.  They probably have no variants with considerable differences.  For example, `ja-JP` means "Japanese, used in Japan", which is kind of meaningless.

**Pull request closed without merging**
