### PR TITLE
chore: allow to customize wakatime data range

### PR DESCRIPTION
**Pull request by muety**
PR https://github.com/anuraghazra/github-readme-stats/pull/871 changed the WakaTime fetcher in a way that it always requests data for whatever range the user has set as "Default Range" in WakaTime. However, chances are that a user may want a deviating range for her readme cards. Or she wants different ranges for different readmes in different repos. 

Also, it makes behavior more predictable when using third-party sevice like [Wakapi](https://wakapi.dev), that don't have inherent support for configurable "default ranges".

This PR allows to pass another, optional parameter to the WakaTime card to explicitly request a certain range.

### CODE REVIEW

**Comment by muety** [comment]
Could somebody please take a look at this?

**Comment by anuraghazra** [comment]
This looks good @muety can you add the `range` param to docs?

**Comment by muety** [comment]
Sure, it's done!

**Comment by muety** [comment]
Btw, how am I supposed to resolve the merge conflict? Rebase onto `master` or merge it into my feature branch?

**Comment by anuraghazra** [comment]
This looks good! thanks @muety

**Pull request merged**
