### PR TITLE
feat: default values for wakatime and language

### LINKED ISSUE #2030: Add option defaults to README.
**Is your feature request related to a problem? Please describe.**

Currently, we do not list the option defaults in the readme.

**Describe the solution you'd like**

I think adding the option defaults will improve the documentation. Maybe something like:

```diff
- hide_border - Hides the card's border (boolean)
+ hide_border - Hides the card's border (boolean). Defaults to false.
```

### PR DESCRIPTION
**Pull request by adi-uchiha**
A PR with respect to a failed PR #2091 

Closes #2030 

Modified : readme.md

Added default values to few card

### CODE REVIEW

**Comment by adi-uchiha** [comment]
Have no idea how to do that. Can you please have a look at my forked repo and tell me what commands to use. 
I am new to GitHub and Git
@rickstaa

**Comment by rickstaa** [comment]
@adi-uchiha No problem. There are multiple ways to do this a good explanation is found on https://stackoverflow.com/a/65401892/8135687. I always use option 3 together with [Vscode](https://code.visualstudio.com/) and https://gitlens.amod.io/. By doing it that way, Vscode will show the differences in the IDE. It appears that your branch is already up to date, but you removed some of the new features that were added to the README.md during the last commits. Let me quickly fix that.

**Comment by rickstaa** [comment]
@adi-uchiha Looks good to me! Thanks a lot for your contribution.

**Comment by adi-uchiha** [comment]
> @adi-uchiha No problem. There are multiple ways to do this a good explanation is found on https://stackoverflow.com/a/65401892/8135687. I always use option 3 together with [Vscode](https://code.visualstudio.com/) and https://gitlens.amod.io/. By doing it that way, Vscode will show the differences in the IDE. It appears that your branch is already up to date, but you removed some of the new features that were added to the README.md during the last commits. Let me quickly fix that.

 @rickstaa Thanks for such good insights on advanced concepts of git. I didn't knew about gitlens. This is what I like about open source 😄

**Pull request merged**
