### PR TITLE
Created CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by vasugamdha**

### CODE REVIEW

**Comment by anuraghazra** [comment]
@vasugamdha Thanks for the PR, i think i have to write a custom CONTRIBUTING.md file instead of the default ones, because i have to guide about themes contributions and stuff

**Comment by vasugamdha** [comment]
I have almost edited the basic requirements. You can modify this and merge it later.

**Comment by anuraghazra** [comment]
> I have almost edited the basic requirements. You can modify this and merge it later.

Okay, i'll merge this later. after writing the contribution guidelines. :D don't close the PR. i'll push to your fork

**Comment by anuraghazra** [comment]
Closing this since i cannot push to this PR because fork repo is archived.

**Pull request closed without merging**
