### PR TITLE
Added Date Night theme to index.js

### PR DESCRIPTION
**Pull request by jesterb0206**
Hi Anurag or whoever is reading this,

I have a new theme that I would like to contribute to the GitHub README Stats repository, I hope you enjoy!

Bradley

dateNight Theme

### CODE REVIEW

**Comment by jesterb0206** [comment]
@rickstaa One question, will it be added to themes/README.md? Sorry to be a pest

**Comment by rickstaa** [comment]
@jesterb0206 I understand your confusion. Our [generate-theme-doc.yml)](https://github.com/anuraghazra/github-readme-stats/blob/master/.github/workflows/generate-theme-doc.yml) should create a PRs for updating the Themes list. I, however, noticed that these PRs failed in the last months. @anuraghazra, Can you maybe check what is going on or trigger these action manually?

**Comment by rickstaa** [comment]
@jesterb0206 @anuraghazra Looks like the action fails with an `npm not found` action but doesn't throw an error exit code.

**Comment by rickstaa** [comment]
@anuraghazra Why do you force a `0` exit code when something goes wrong?

https://github.com/anuraghazra/github-readme-stats/blob/b2e34ac8db9dd28f009ac1f7f657da8b7f21800c/scripts/push-theme-readme.sh#L12

Further, I think we should use the `--no-verify` command to prevent this error from happening.

**Comment by rickstaa** [comment]
@anuraghazra I created https://github.com/anuraghazra/github-readme-stats/pull/2271/files to fix this. Can you maybe take a look?

**Pull request merged**
