### PR TITLE
Forest Fire Theme

### PR DESCRIPTION
**Pull request by HenryBass**
Uses Firewatch color palate

### CODE REVIEW

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:x: Theme PR does not adhere to our guidelines.
      
## Test results
      
- :x: forest_fire

      
**Result:** :x: Some themes are invalid.


  
Unfortunately, your theme PR does not adhere to our [theme guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution). Please fix the issues below, and we will review your  
 PR again. This pull request will **automatically close in 15 days** if no changes are made. After this time, you must re-open the PR for it to be reviewed.

      
      
## Details
      
          
### Forest_fire theme preview
          
          
          
- :x: Theme color property `icon_color` should not start with '#'.
- :x: Theme color property `text_color` should not start with '#'.


          
>:x: Cannot create theme preview.

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1412#issuecomment-1264658239) comment above for more information.

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1412#issuecomment-1264658239) comment above for more information.

**Comment by HenryBass** [comment]
@rickstaa Is there anything I can do to get the _Invalid_ label removed? To qualify for future Hacktoberfests, I can't have PRs marked with invalid. I'll admit I should have read through guidelines better. Sorry, and thanks!

**Comment by rickstaa** [comment]
@HenryBass Oh, sorry for that, we automatically label theme PRs that are not valid as `invalid`. It is unfortunate that Hacktoberfest uses this tag for spam PRs. As can be deduced from https://github.com/anuraghazra/github-readme-stats/pull/1412#issuecomment-1264658239, the invalid label will be removed when you remove the `#`'s from the colour codes. Although this symbol is contained in valid hex colours, we can not use it due to URL symbol restrictions. If this change is made, the invalid label will be automatically removed. I will update the comment a bit to better express this behaviour. Since you already closed your PR, I will manually remove the invalid label.

**Comment by rickstaa** [comment]
BTW your PR is not against our guidelines. It simply does not work with our code because of the URL query symbol restrictions.

**Comment by HenryBass** [comment]
Thanks!

**Pull request closed without merging**
