### PR TITLE
Just another theme for B&W people

### PR DESCRIPTION
**Pull request by TheDevilHimself69**

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title_color: <code>#F4F4F4</code> | icon_color: <code>#E5E5E5</code> | text_color: <code>#C2C2C2</code> | bg_color: <code>#1E1E1E</code>
      
      
Link: https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=F4F4F4&icon_color=E5E5E5&text_color=C2C2C2&bg_color=1E1E1E&show_icons=true

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=F4F4F4&icon_color=E5E5E5&text_color=C2C2C2&bg_color=1E1E1E&show_icons=true)
      
      
  
> Hi thanks for the theme contribution, please read our theme contribution guidelines

  
> We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 
  
> Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:x: Theme PR does not adhere to our guidelines.
      
## Test results
      
- :x: Blackwhite

      
**Result:** :x: Some themes are invalid.


  
Unfortunately, your theme PR does not adhere to our [theme guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution). Please fix the issues below, and we will review your  
 PR again. This pull request will **automatically close in 15 days** if no changes are made. After this time, you must re-open the PR for it to be reviewed.

      
      
## Details
      
        
### Blackwhite theme preview
        
        
- :warning: Theme name isn't in snake_case.


        
title_color: <code>#F4F4F4</code> | icon_color: <code>#E5E5E5</code> | text_color: <code>#C2C2C2</code> | bg_color: <code>#1E1E1E</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=F4F4F4&icon_color=E5E5E5&text_color=C2C2C2&bg_color=1E1E1E&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=F4F4F4&icon_color=E5E5E5&text_color=C2C2C2&bg_color=1E1E1E&show_icons=true)

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1066#issuecomment-1264659347) comment above for more information.

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1066#issuecomment-1264659347) comment above for more information.

**Comment by rickstaa** [comment]
This PR has been automatically closed due to inactivity. Please feel free to reopen it if you need to continue working on it.	
Thank you for your contributions.

**Pull request closed without merging**
