### PR TITLE
Added "rgbasic" and "greys" themes!

### PR DESCRIPTION
**Pull request by vasugamdha**
Added 2 themes:
1. rgbasic <code>#DA291C</code> <code>#53A567</code> <code>#56A8CB</code> <code>#000000</code>
2. greys <code>#111111</code> <code>#656565</code> <code>#373737</code> <code>#999999</code>

### CODE REVIEW

**Comment by anuraghazra** [comment]
Hi Thanks for the PR @vasugamdha 

Can you please add a screenshot?

**Comment by anuraghazra** [comment]
This is pretty interesting tho, i wasn't aware of this markdown trick <code>#DA291C</code>

```
<code>#DA291C</code>
```

**Comment by vasugamdha** [comment]
> Can you please add a screenshot?

`rgbasic:`



`greys:`<br> 
<br>

**Comment by vasugamdha** [comment]
Do I have also commit the other changes, that are to be made in <code>[github-readme-stats/themes/README.md](https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md)</code>, in this PR only? or is it automated?

**Comment by nombrekeff** [comment]
It's manual for now, but we thought of automating it. You can add it if you want once Anurag accepts the theme, otherwise, I will add it later myself!

**Comment by anuraghazra** [comment]
> > Can you please add a screenshot?
> 
> `rgbasic:`
> 
> 
> 
> `greys:`
> 
> 

Hmmm not sure about the color scheme tho, not modern enough, maybe try some material colors.

**Comment by nombrekeff** [comment]
Yup, I don't really like the greys theme neither, to muted for my taste. Consider making the background lighter.

**Comment by anuraghazra** [comment]
Yeah and the first one's colors are not  matching up with the red & green  icons maybe try other variations

**Comment by nombrekeff** [comment]
I was thinking about this yesterday, about the in-built themes becoming huge, I was thinking we should only accept already defined themes or themes that match our standards. Otherwise, themes will increase hugely, just in the last day, there have been requests for 5-6 themes. And most of them are quite personal. Also, people could just add the appropriate options instead if they want to change the theme. 

I would suggest sticking to common themes or ones that really stick out, and inform users that they can just pass in the options to the request. `?text_color=#ffffff`

>  maybe we can provide a way for users to host their own theme libraries.

Yeah, maybe hosting themes could be a good idea, it would just be another request to fetch the JSON. Maybe they could pass in the URL of the JSON theme, something like: `?theme_url=https://my-site.com/GitHub-readme-stats-{theme}.json`

I don't know if this is actually needed though, it's way easier to just pass in the theme directly to the request.

What do you guys think?

**Comment by nombrekeff** [comment]
We could explain all this in the contributing guidelines or in the theme README as well, so people know how/when to create a new theme.

**Comment by vasugamdha** [comment]
> Yeah, maybe hosting themes could be a good idea, it would just be another request to fetch the JSON. Maybe they could pass in the URL of the JSON theme, something like: `?theme_url=https://my-site.com/GitHub-readme-stats-{theme}.json`
> 
This just add up more requests.

> I don't know if this is actually needed though, it's way easier to just pass in the theme directly to the request.
> What do you guys think?
>

Yeah! `?title_color=#code&icon_color=#code&text_color=#code&bg_color=#code` this is just a one time thing. If anyone wants to add a new theme he could just make it this way.

**Comment by nombrekeff** [comment]
> This just add up more requests.

Yup not ideal, only 1 though. I don't really like that approach, kinda complicating the project.

 > Yeah! ?title_color=#code&icon_color=#code&text_color=#code&bg_color=#code this is just a one time thing. If anyone wants to add a new theme they could just make it this way, for their use.

Yup, if it's a personal theme I would suggest they do this.

**Comment by vasugamdha** [comment]
We can do like creating a whole new API as a project and authenticating users through GitHub and they can add as many as themes they want in their account. Maybe we can globalize themes and people can integrate our themes for their app, kind of! I hope you get my point, as i am don't sound clear enough!

**Pull request closed without merging**
