### PR TITLE
Add Transparent-monokai

### PR DESCRIPTION
**Pull request by Semporia**
The theme adds Transparent-monokai (transparent background), compatible with Dark and Light modes; the overall color scheme is mainly monokai.

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title_color: <code>#eb1f6a</code> | icon_color: <code>#e28905</code> | text_color: <code>#999999</code> | bg_color: <code>#27282200</code>
      
      
Link: https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=eb1f6a&icon_color=e28905&text_color=999999&bg_color=27282200&show_icons=true

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=eb1f6a&icon_color=e28905&text_color=999999&bg_color=27282200&show_icons=true)
      
      
  
> Hi thanks for the theme contribution, please read our theme contribution guidelines

  
> We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 
  
> Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1089#issuecomment-1264669495) comment above for more information.

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:x: Theme PR does not adhere to our guidelines.
      
## Test results
      
- :x: Transparent-monokai

      
**Result:** :x: Some themes are invalid.


  
Unfortunately, your theme PR does not adhere to our [theme guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution). Please fix the issues below, and we will review your  
 PR again. This pull request will **automatically close in 15 days** if no changes are made. After this time, you must re-open the PR for it to be reviewed.

      
      
## Details
      
        
### Transparent-monokai theme preview
        
        
- :warning: Theme name isn't in snake_case.
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=eb1f6a&bcolor=272822).


        
title_color: <code>#eb1f6a</code> | icon_color: <code>#e28905</code> | text_color: <code>#999999</code> | bg_color: <code>#27282200</code> | border_color: <code>#999999</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=eb1f6a&icon_color=e28905&text_color=999999&bg_color=27282200&border_color=999999&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=eb1f6a&icon_color=e28905&text_color=999999&bg_color=27282200&border_color=999999&show_icons=true)

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1089#issuecomment-1264669495) comment above for more information.

**Comment by rickstaa** [comment]
This PR has been automatically closed due to inactivity. Please feel free to reopen it if you need to continue working on it.	
Thank you for your contributions.

**Pull request closed without merging**
