### PR TITLE
add orientation option to handle vertical and horizontal stats card

### PR DESCRIPTION
**Pull request by omidnikrah**
https://github.com/anuraghazra/github-readme-stats/issues/70

### CODE REVIEW

**Comment by filiptronicek** [comment]
@anuraghazra can we please link the issue to this PR?

**Comment by anuraghazra** [comment]
I was thinking if instead of using orientation, we can do "layout" Which would have "vertical" Or "horizontal" Options, that way we can extend out and have more inbuilt layouts in future if we want

**Comment by omidnikrah** [comment]
> I was thinking if instead of using orientation, we can do "layout" Which would have "vertical" Or "horizontal" Options, that way we can extend out and have more inbuilt layouts in future if we want

That's you mean "vertical" and "horizontal" are the acceptable value of "layout" option. Right?

**Comment by anuraghazra** [comment]
Yup `?layout=vertical`

**Comment by anuraghazra** [comment]
Hold on @omidnikrah i'll be merging the PR :D i just wanted to think this layout stuff through, because all these ternary checks and conditionally changing variables seems too much work and look ugly TBH, any ideas?

**Comment by anuraghazra** [comment]
Hmm this does not look right :thinking: 
vertical_bg

**Pull request closed without merging**
