### PR TITLE
style: add ayu-mirage theme

### PR DESCRIPTION
**Pull request by impulse**

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)

**Comment by anuraghazra** [comment]
Theme preview (bot)

**Comment by anuraghazra** [comment]
Theme preview (bot)

**Comment by anuraghazra** [comment]
Theme preview (bot)

**Comment by anuraghazra** [comment]
Theme preview (bot)

**Comment by anuraghazra** [comment]
@impulse is this the final iteration?

**Comment by impulse** [comment]
@anuraghazra yeah, sorry should have tested it with the API first 😂

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
title-color: <code>#f4cd7c</code>
      
icon-color: <code>#73d0ff</code>
      
text-color: <code>#c7c8c2</code>
      
bg-color: <code>#1f2430</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=f4cd7c&icon_color=73d0ff&text_color=c7c8c2&bg_color=1f2430&show_icons=true)

**Comment by anuraghazra** [comment]
Looks good! merging it. Thanks @impulse

**Pull request merged**
