### PR TITLE
add holi_theme

### PR DESCRIPTION
**Pull request by mohamedhassan279**

### CODE REVIEW

**Review by mohamedhassan279 — COMMENTED** [review]
done

**Review by Zo-Bro-23 — COMMENTED** [review]
Looks good :) Is it from a VSCode theme?

**Comment by mohamedhassan279** [comment]
yes, it's a VSCode theme :)

**Review by Zo-Bro-23 — APPROVED** [review]

**Review by rickstaa — APPROVED** [review]

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/2539#issuecomment-1444417742) comment above for more information.

**Pull request merged**
