### PR TITLE
Enable valid-jsdoc eslint rule

### PR DESCRIPTION
**Pull request by qwerty541**
Related to https://github.com/anuraghazra/github-readme-stats/pull/2913 https://github.com/anuraghazra/github-readme-stats/pull/2920 https://github.com/anuraghazra/github-readme-stats/pull/2923 https://github.com/anuraghazra/github-readme-stats/pull/2924

### CODE REVIEW

**Review by qwerty541 — COMMENTED** [review]
> I like this rule since it improves maintainability. However, I think we should merge it after all errors are fixed:
> 
> ```shell
> /home/ricks/development/personal/github-readme-stats/api/status/pat-info.js
>    11:1  error  JSDoc syntax error                       valid-jsdoc
>    39:1  error  Missing JSDoc @returns for function      valid-jsdoc
>    39:1  error  Missing JSDoc for parameter 'fetcher'    valid-jsdoc
>    39:1  error  Missing JSDoc for parameter 'variables'  valid-jsdoc
>   118:1  error  Missing JSDoc @returns for function      valid-jsdoc
>   118:1  error  Missing JSDoc for parameter '_'          valid-jsdoc
>   118:1  error  Missing JSDoc for parameter 'res'        valid-jsdoc
> 
> /home/ricks/development/personal/github-readme-stats/api/status/up.js
>   13:1  error  JSDoc syntax error                   valid-jsdoc
>   37:1  error  Missing JSDoc return type            valid-jsdoc
>   60:1  error  Missing JSDoc @returns for function  valid-jsdoc
>   60:1  error  Missing JSDoc for parameter 'req'    valid-jsdoc
>   60:1  error  Missing JSDoc for parameter 'res'    valid-jsdoc
> 
> /home/ricks/development/personal/github-readme-stats/src/cards/repo-card.js
>   82:1  error  JSDoc syntax error  valid-jsdoc
> 
> /home/ricks/development/personal/github-readme-stats/src/cards/stats-card.js
>   23:1  error  JSDoc type missing brace  valid-jsdoc
>   77:1  error  JSDoc syntax error        valid-jsdoc
> 
> /home/ricks/development/personal/github-readme-stats/src/cards/top-languages-card.js
>    45:1  error    Missing JSDoc return type    valid-jsdoc
>    53:1  error    Missing JSDoc return type    valid-jsdoc
>   395:9  warning  Expected property shorthand  object-shorthand
>   664:1  error    JSDoc syntax error           valid-jsdoc
>   681:1  error    JSDoc syntax error           valid-jsdoc
>   703:1  error    JSDoc syntax error           valid-jsdoc
> 
> /home/ricks/development/personal/github-readme-stats/src/cards/wakatime-card.js
>    31:4   error    Use @returns instead                   valid-jsdoc
>    39:1   error    JSDoc syntax error                     valid-jsdoc
>    48:40  warning  'totalSize' is defined but never used  no-unused-vars
>    61:1   error    JSDoc syntax error                     valid-jsdoc
>    70:53  warning  'x' is defined but never used          no-unused-vars
>    89:1   error    Missing JSDoc @returns for function    valid-jsdoc
>   141:1   error    JSDoc syntax error                     valid-jsdoc
>   159:1   error    JSDoc syntax error                     valid-jsdoc
>   301:15  warning  Expected property shorthand            object-shorthand
> 
> /home/ricks/development/personal/github-readme-stats/src/common/Card.js
>    61:3  error  Missing JSDoc @returns for function              valid-jsdoc
>    62:6  error  Missing JSDoc parameter description for 'prop'   valid-jsdoc
>    69:3  error  Missing JSDoc @returns for function              valid-jsdoc
>    70:6  error  Missing JSDoc parameter description for 'value'  valid-jsdoc
>    76:3  error  Missing JSDoc @returns for function              valid-jsdoc
>    77:6  error  Missing JSDoc parameter description for 'value'  valid-jsdoc
>    83:3  error  Missing JSDoc @returns for function              valid-jsdoc
>    84:6  error  Missing JSDoc parameter description for 'value'  valid-jsdoc
>    93:3  error  Missing JSDoc @returns for function              valid-jsdoc
>    94:6  error  Missing JSDoc parameter description for 'text'   valid-jsdoc
>   158:3  error  Missing JSDoc @returns for function              valid-jsdoc
>   159:6  error  Missing JSDoc parameter description for 'body'   valid-jsdoc
> 
> /home/ricks/development/personal/github-readme-stats/src/common/retryer.js
>    9:1  error  Missing JSDoc return type                               valid-jsdoc
>    9:1  error  Missing JSDoc for parameter 'variables'                 valid-jsdoc
>    9:1  error  Missing JSDoc for parameter 'retries'                   valid-jsdoc
>   12:4  error  Expected JSDoc for 'fetcher' but found 'retryerParams'  valid-jsdoc
> 
> /home/ricks/development/personal/github-readme-stats/src/common/utils.js
>   325:20  error  Parsing error: Unexpected token =
> 
> /home/ricks/development/personal/github-readme-stats/src/fetchers/repo-fetcher.js
>    5:1  error  JSDoc syntax error  valid-jsdoc
>   56:1  error  JSDoc syntax error  valid-jsdoc
> 
> /home/ricks/development/personal/github-readme-stats/src/fetchers/stats-fetcher.js
>    77:1  error  JSDoc syntax error  valid-jsdoc
>    97:1  error  JSDoc syntax error  valid-jsdoc
>   178:1  error  JSDoc syntax error  valid-jsdoc
> 
> /home/ricks/development/personal/github-readme-stats/src/fetchers/top-languages-fetcher.js
>   11:1  error  JSDoc syntax error  valid-jsdoc
>   50:1  error  JSDoc syntax error  valid-jsdoc
> 
> /home/ricks/development/personal/github-readme-stats/src/fetchers/wakatime-fetcher.js
>   3:10  warning  'I18n' is defined but never used  no-unused-vars
> ```

изображение

@rickstaa I have opened this pull request after running `npm run lint` and seeing no errors and warnings. You can check on screenshot. Also you can check eslint output on GitHub Actions https://github.com/anuraghazra/github-readme-stats/actions/runs/5510580836/jobs/10044991453?pr=2928. If there was some errors and warnings test workflow should fail. I should ask you how you managed to receive this output?

**Comment by qwerty541** [comment]
Oh i understand the problem. Out `lint` command should run:
```
npx eslint --max-warnings 0 "./src/**/*.js" "./scripts/**/*.js" "./tests/**/*.js" "./api/**/*.js" "./themes/**/*.js"
```

Instead of:

```
npx eslint --max-warnings 0 "./src/**.js" "./scripts/**.js" "./tests/**.js" "./api/**.js" "./themes/**.js"
```

**Comment by qwerty541** [comment]
@rickstaa I have opened #2932 pull request to fix this problem. And #2930 & #2931 which should be merged before.

**Comment by rickstaa** [comment]
@qwerty541, thanks for tackling the linting errors 🚀. There now are fewer. However, I think all should be fixed before we merge this 🤔.

```bash
/home/ricks/development/personal/github-readme-stats/api/status/pat-info.js
   11:1  error  JSDoc syntax error                       valid-jsdoc
   39:1  error  Missing JSDoc @returns for function      valid-jsdoc
   39:1  error  Missing JSDoc for parameter 'fetcher'    valid-jsdoc
   39:1  error  Missing JSDoc for parameter 'variables'  valid-jsdoc
  118:1  error  Missing JSDoc @returns for function      valid-jsdoc
  118:1  error  Missing JSDoc for parameter '_'          valid-jsdoc
  118:1  error  Missing JSDoc for parameter 'res'        valid-jsdoc

/home/ricks/development/personal/github-readme-stats/api/status/up.js
  13:1  error  JSDoc syntax error                   valid-jsdoc
  37:1  error  Missing JSDoc return type            valid-jsdoc
  60:1  error  Missing JSDoc @returns for function  valid-jsdoc
  60:1  error  Missing JSDoc for parameter 'req'    valid-jsdoc
  60:1  error  Missing JSDoc for parameter 'res'    valid-jsdoc

/home/ricks/development/personal/github-readme-stats/src/cards/repo-card.js
  82:1  error  JSDoc syntax error  valid-jsdoc

/home/ricks/development/personal/github-readme-stats/src/cards/stats-card.js
  77:1  error  JSDoc syntax error  valid-jsdoc

/home/ricks/development/personal/github-readme-stats/src/cards/top-languages-card.js
   45:1  error  Missing JSDoc return type  valid-jsdoc
   53:1  error  Missing JSDoc return type  valid-jsdoc
  664:1  error  JSDoc syntax error         valid-jsdoc
  681:1  error  JSDoc syntax error         valid-jsdoc
  703:1  error  JSDoc syntax error         valid-jsdoc

/home/ricks/development/personal/github-readme-stats/src/cards/wakatime-card.js
   39:1  error  JSDoc syntax error                   valid-jsdoc
   60:1  error  JSDoc syntax error                   valid-jsdoc
   84:1  error  Missing JSDoc @returns for function  valid-jsdoc
  136:1  error  JSDoc syntax error                   valid-jsdoc
  154:1  error  JSDoc syntax error                   valid-jsdoc

/home/ricks/development/personal/github-readme-stats/src/common/utils.js
  152:1  error  JSDoc syntax error                                          valid-jsdoc
  169:1  error  JSDoc syntax error                                          valid-jsdoc
  194:1  error  JSDoc syntax error                                          valid-jsdoc
  344:6  error  Missing JSDoc parameter description for 'missedParams'      valid-jsdoc
  345:6  error  Missing JSDoc parameter description for 'secondaryMessage'  valid-jsdoc
  399:1  error  Missing JSDoc @returns for function                         valid-jsdoc
  399:5  error  Missing JSDoc parameter description for 'name'              valid-jsdoc
  437:1  error  Missing JSDoc return description                            valid-jsdoc
  439:4  error  Missing JSDoc parameter description for 'd1'                valid-jsdoc
  440:4  error  Missing JSDoc parameter description for 'd2'                valid-jsdoc

/home/ricks/development/personal/github-readme-stats/src/fetchers/repo-fetcher.js
   5:1  error  JSDoc syntax error  valid-jsdoc
  56:1  error  JSDoc syntax error  valid-jsdoc

/home/ricks/development/personal/github-readme-stats/src/fetchers/stats-fetcher.js
   77:1  error  JSDoc syntax error  valid-jsdoc
   97:1  error  JSDoc syntax error  valid-jsdoc
  178:1  error  JSDoc syntax error  valid-jsdoc

/home/ricks/development/personal/github-readme-stats/src/fetchers/top-languages-fetcher.js
  11:1  error  JSDoc syntax error  valid-jsdoc
  50:1  error  JSDoc syntax error  valid-jsdoc

✖ 41 problems (41 errors, 0 warnings)
```

**Review by rickstaa — APPROVED** [review]

**Pull request merged**
