### PR TITLE
update my theme

### PR DESCRIPTION
**Pull request by eduardozaniboni**

### CODE REVIEW

**Comment by Zo-Bro-23** [comment]
@rickstaa will this have backward compatibility issues?

**Comment by rickstaa** [comment]
> @ricksta,a will this have backward compatibility issues?

We can ignore the theme preview action since it must be coded for theme renames. For backward compatibility, the rename will cause the cards of people using the theme to revert to the default theme.

**Comment by Zo-Bro-23** [comment]
> 

Yes, but this theme was added recently, so it should be fine right?

**Comment by rickstaa** [comment]
> > 
> 
> Yes, but this theme was added recently, so it should be fine right?

Yea no problem. I will approve.

**Review by rickstaa — APPROVED** [review]

**Pull request merged**
