### PR TITLE
Added dark-vue theme.

### PR DESCRIPTION
**Pull request by mehtaabGill**
Annotation 2020-08-26 172651

Good day. I created a 'dark-vue' theme and would like to share it with others.

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title-color: <code>#41b883</code>
      
icon-color: <code>#41b883</code>
      
text-color: <code>#fffefe</code>
      
bg-color: <code>#273849</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=41b883&icon_color=41b883&text_color=fffefe&bg_color=273849&show_icons=true)

**Comment by anuraghazra** [comment]
This looks good @mehtaabGill . sorry for late response i'm kinda busy nowdays.

**Comment by anuraghazra** [comment]
wow oops, sorry we already have vue-dark theme

**Comment by mehtaabGill** [comment]
Ah yes. I did see that but the colors on that theme were slightly inaccurate in my opinion, however, I will let you decide wether you would like it to be added or not.

**Comment by anuraghazra** [comment]
> Ah yes. I did see that but the colors on that theme were slightly inaccurate in my opinion, however, I will let you decide wether you would like it to be added or not.


Well true, your are more accurate, maybe you can overwrite the old vue dark theme with your more accurate colors. instead of adding this new theme

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title-color: <code>#41b883</code>
      
icon-color: <code>#41b883</code>
      
text-color: <code>#fffefe</code>
      
bg-color: <code>#273849</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=41b883&icon_color=41b883&text_color=fffefe&bg_color=273849&show_icons=true)

**Comment by mehtaabGill** [comment]
I have just edited the old theme now to match the correct Vue.js  colors.

**Comment by anuraghazra** [comment]
Awesome! thanks @mehtaabGill

**Pull request merged**
