### PR TITLE
feat: Add trophy rank icon

### PR DESCRIPTION
**Pull request by FajarKim**
## Description

Add trophy rank icon

## Screenshots

Link:
```markdown
https://github-readme-stats-git-trophy-rank-icon-fkstreakstats.vercel.app/api?username=anuraghazra&rank_icon=trophy
```

Preview

### CODE REVIEW

**Review by qwerty541 — APPROVED** [review]
Hey, @FajarKim! Thanks for opening pull request! This trophy icon looks good to me. I give my approval to this. If any other maintainer will give his approval we can merge this.

**Comment by rickstaa** [comment]
Related to https://github.com/anuraghazra/github-readme-stats/pull/3275.

**Comment by rickstaa** [comment]
@qwerty541, although this pull request is well-coded. I am afraid if we keep adding icons like this, the maintainability of the repository will decrease since it adds a lot of extra code in the icons.js 🤔. @anuraghazra, what do you think? Maybe we can use an icon provider to fetch these icons?

**Comment by qwerty541** [comment]
> @qwerty541, although this pull request is well-coded. I am afraid if we keep adding icons like this, the maintainability of the repository will decrease since it adds a lot of extra code in the icons.js 🤔. @anuraghazra, what do you think? Maybe we can use an icon provider to fetch these icons?

@rickstaa I completely agree with your thoughts about maintainability. I'm okay with current state of `icon.js` file, but i wanted to propose same solution after merging this pull request, this was the reason why i approved only one of three pull requests opened by @FajarKim with addition of rank icon alternatives. We can also refactor `icon.js` file with icon providers before merging this. I will open a pull request if you are up to approve and merge it.

**Comment by rickstaa** [comment]
> > @qwerty541, although this pull request is well-coded. I am afraid if we keep adding icons like this, the maintainability of the repository will decrease since it adds a lot of extra code in the icons.js 🤔. @anuraghazra, what do you think? Maybe we can use an icon provider to fetch these icons?
> 
> @rickstaa I completely agree with your thoughts about maintainability. I'm okay with current state of `icon.js` file, but i wanted to propose same solution after merging this pull request, this was the reason why i approved only one of three pull requests opened by @FajarKim with addition of rank icon alternatives. We can also refactor `icon.js` file with icon providers before merging this. I will open a pull request if you are up to approve and merge it.

If the community shows enough interest I'm okay with allowing users to use icons provided by an icon provider as long as it doesn't degrade the cards' performance. I myself, however, do not see myself using this feature in the future. I, therefore, think it is best to first double-check with @anuraghazra to see his thoughts on this feature 🤔.

**Comment by anuraghazra** [comment]
Let's discuss this before adding any new icons. 

First of all, visually this trophy icon looks quite bulky even if we plan to add a trophy icon I would probably refrain from adding this particular icon. We need something more simplified this icon is bit too complex. Visually looks bad.

Secondly, if we plan to add trophy icons might as well be better to make these trophy icons dynamic based on how much ranking you have.

**Comment by rickstaa** [comment]
> Secondly, if we plan to add trophy icons might as well be better to make these trophy icons dynamic based on how much ranking you have.

@anuraghazra, thanks a lot for your input. I like your idea of rank-based icons 👍🏻. I think we can make a feature request for this and merge it if enough people are interested in it.

> First of all, visually this trophy icon looks quite bulky even if we plan to add a trophy icon I would probably refrain from adding this particular icon. We need something more simplified this icon is bit too complex. Visually looks bad.

I agree. What are your thoughts on "giving users the ability to change the icon based on an icon provider like font-awesome"? In my opinion, it is a nice shiny extra but I'm not sure if it is worth donating developer time 😅. In that case, adding rank-based icons makes more sense given the project's nature 🤔.

**Comment by anuraghazra** [comment]
I don't think adding icon providers and randomly choosing icons from icon providers will be very much useful. 

Rather better to create dynamic trophies.

**Comment by rickstaa** [comment]
> I don't think adding icon providers and randomly choosing icons from icon providers will be very much useful.
> 
> Rather better to create dynamic trophies.

Cool, then we agree! Let's close #3275, #3276, #3277 for now. 

@FajarKim, feel free to create a feature request for rank-based icons if that is something you would like to be implemented. Please bear in mind, however that since we are a small team, we only merge pull requests that solve pressing bugs or for which the community has shown significant interest in the form of upvotes 👍🏻 (see https://github.com/anuraghazra/github-readme-stats/issues/1935)>

**Pull request closed without merging**
