### PR TITLE
Add my theme called fairy_purple

### PR DESCRIPTION
**Pull request by yakiee**

### CODE REVIEW

**Comment by yakiee** [comment]
I added fairy purple theme💜
preview

api

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:x: Theme PR does not adhere to our guidelines.
      
## Test results
      
- :x: fairy_purple

      
**Result:** :x: Some themes are invalid.


  
Unfortunately, your theme PR does not adhere to our [theme guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution). Please fix the issues below, and we will review your  
 PR again. This pull request will **automatically close in 15 days** if no changes are made. After this time, you must re-open the PR for it to be reviewed.

      
      
## Details
      
        
### Fairy_purple theme preview
        
        
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=B4A8FF&bcolor=F0F2FD).
- :warning: `icon_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=2883EB&bcolor=F0F2FD).
- :warning: `text_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=759AFF&bcolor=F0F2FD).


        
title_color: <code>#B4A8FF</code> | icon_color: <code>#2883EB</code> | text_color: <code>#759AFF</code> | bg_color: <code>#F0F2FD</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=B4A8FF&icon_color=2883EB&text_color=759AFF&bg_color=F0F2FD&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=B4A8FF&icon_color=2883EB&text_color=759AFF&bg_color=F0F2FD&show_icons=true)

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1667#issuecomment-1264657710) comment above for more information.

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1667#issuecomment-1264657710) comment above for more information.

**Pull request closed without merging**
