### PR TITLE
Added pr reviews to stats

### PR DESCRIPTION
**Pull request by Marcholio**
Fixes: #1394 

Added code reviews to stats card:
Screenshot 2021-10-21 at 17 38 40

What do you think about this feature? They do not affect the rank at the moment, that's something that should be maybe added later. Also translations just default to english.

### CODE REVIEW

**Comment by kerthcet** [comment]
kindly ping @[anuraghazra](https://github.com/anuraghazra)

**Comment by kerthcet** [comment]
kindly ping @anuraghazra

**Comment by rickstaa** [comment]
@kerthcet I fully understand that this is a feature you want. Pinging the repository author, however, does not speed up the PR review process. We already got an alert when you posted https://github.com/anuraghazra/github-readme-stats/pull/1404#issuecomment-1045631301. It only puts more stress on the repository collaborators who maintain this project in their free time. 

There are currently several other PRs open which have a higher priority (e.g. https://github.com/anuraghazra/github-readme-stats/issues/1 and https://github.com/anuraghazra/github-readme-stats/pull/1186). We, therefore, can not give you an ETA for this feature. 

I would therefore advise you to fork this project, for now, merge #1404 and create your own vercel instance (see https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance). 

Hope that helps. Let me know if you have any questions

**Comment by kerthcet** [comment]
> 

Sorry guys, my intension here was to check whether this pr is forgotten for approved since last year.
Thanks for syncing the information. Apologize again.

**Comment by rickstaa** [comment]
@kerthcet No problem I understand. Feel free to let me know if you run into problems merging this PR on your own fork and deploying it on your own vercel instance.

**Comment by anuraghazra** [comment]
This looks good, will give final review soon.

GOSH I still regret the decision to add the `hide` param. Should've been better to put show param as default.

**Comment by kerthcet** [comment]
Revisit this pr again, any progress?

**Comment by Harrypotterrrr** [comment]
Any progress on this branch?

**Comment by qwerty541** [comment]
@Marcholio @rickstaa 

изображение

I have merged master branch and refactored the code a little. Please check it and write about your thoughts. If you didn't liked the changed feel free to force push them back.

**Review by rickstaa — APPROVED** [review]

**Comment by rickstaa** [comment]
@merged into master. @Marcholio thanks for your contribution!

**Pull request merged**
