### PR TITLE
Update index.js 

### PR DESCRIPTION
**Pull request by pascall-de-creator**
Added new theme

### CODE REVIEW

**Comment by anuraghazra** [comment]
**Automated Theme Preview**  
      
      
- :warning: Theme name isn't in snake_case


      
title_color: <code>#15ba88</code> | icon_color: <code>#8093f1</code> | text_color: <code>#15ba88</code> | bg_color: <code>#272640</code>
      
      
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=15ba88&icon_color=8093f1&text_color=15ba88&bg_color=272640&border_color=15ba88&show_icons=true)

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=15ba88&icon_color=8093f1&text_color=15ba88&bg_color=272640&border_color=15ba88&show_icons=true)
      
      
  
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).  
  
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

**Comment by rickstaa** [comment]
@pascall-de-creator thanks for your contribution. Please change the theme name to snake_case (see https://github.com/anuraghazra/github-readme-stats/pull/1621#issuecomment-1053786920).

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1621#issuecomment-1264657876) comment above for more information.

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:x: Theme PR does not adhere to our guidelines.
      
## Test results
      
- :x: cyanSpaceCoder

      
**Result:** :x: Some themes are invalid.


  
Unfortunately, your theme PR does not adhere to our [theme guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution). Please fix the issues below, and we will review your  
 PR again. This pull request will **automatically close in 15 days** if no changes are made. After this time, you must re-open the PR for it to be reviewed.

      
      
## Details
      
        
### CyanSpaceCoder theme preview
        
        
- :warning: Theme name isn't in snake_case.


        
title_color: <code>#15ba88</code> | icon_color: <code>#8093f1</code> | text_color: <code>#15ba88</code> | bg_color: <code>#272640</code> | border_color: <code>#15ba88</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=15ba88&icon_color=8093f1&text_color=15ba88&bg_color=272640&border_color=15ba88&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=15ba88&icon_color=8093f1&text_color=15ba88&bg_color=272640&border_color=15ba88&show_icons=true)

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1621#issuecomment-1264657876) comment above for more information.

**Comment by rickstaa** [comment]
This PR has been automatically closed due to inactivity. Please feel free to reopen it if you need to continue working on it.	
Thank you for your contributions.

**Pull request closed without merging**
