### PR TITLE
Update readme_es.md

### PR DESCRIPTION
**Pull request by moonantonio**
Added the ES language translation of the new feature. 
 * Count of private repositories in commits.

### CODE REVIEW

**Comment by anuraghazra** [comment]
@nombrekeff

**Comment by nombrekeff** [comment]
Looks good to me! Sorry I was away all weekend, I'll be updating the whole readme tomorrow

**Comment by JoseDeFreitas** [comment]
👍

**Comment by anuraghazra** [comment]
Thanks @moonantonio

**Pull request merged**
