### PR TITLE
New nice theme!!!!

### PR DESCRIPTION
**Pull request by FleetAdmiralJakob**
Pls. add it

### CODE REVIEW

**Comment by FleetAdmiralJakob** [comment]
Pls. add it, although it doesn't follow the contrast rules, nobody else has to use it but me, and it's exactly the theme I use on my website. Thanks

**Comment by rickstaa** [comment]
@FleetAdmiralJakob Thanks for your theme PR. Unfortunately, we only accept themes with good AA colours to keep our theme database from cluttering. Therefore, the `icon_color` must be updated before we can accept the theme. You can, however, still use your theme with the following syntax:

[Anurag's GitHub stats

**Comment by FleetAdmiralJakob** [comment]
> 

Can you resend the syntax? I can't read it.

**Comment by rickstaa** [comment]
> ```lisp
> &title_color=c770f0&icon_color=5d417a&text_color=ebebeb&bg_color=0a0e12
> ```

All of [the cards](https://github.com/anuraghazra/github-readme-stats) should give your theme if you append `&title_color=c770f0&icon_color=5d417a&text_color=ebebeb&bg_color=0a0e12`. Let me know if that works.

**Comment by FleetAdmiralJakob** [comment]
Yup, it woeks

**Pull request closed without merging**
