### PR TITLE
Add theme "Yeblu"

### PR DESCRIPTION
**Pull request by orama254**
This is a new theme suggestion for github readme stats

**theme appearance:**
yeblu github readme stats theme

Kindly let me know if it's something that would be fit for the project

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title-color: <code>#ffff00</code>
      
icon-color: <code>#ffff00</code>
      
text-color: <code>#ffffff</code>
      
bg-color: <code>#002046</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ffff00&icon_color=ffff00&text_color=ffffff&bg_color=002046&show_icons=true)

**Comment by ffflabs** [comment]
Theme preview (bot)  
      
      
title-color: <code>#ffff00</code>
      
icon-color: <code>#ffff00</code>
      
text-color: <code>#ffffff</code>
      
bg-color: <code>#002046</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=ffflabs&title_color=ffff00&icon_color=ffff00&text_color=ffffff&bg_color=002046&show_icons=true)

**Comment by anuraghazra** [comment]
Looks good! thanks @orama254

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title-color: <code>#ffff00</code>
      
icon-color: <code>#ffff00</code>
      
text-color: <code>#ffffff</code>
      
bg-color: <code>#002046</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ffff00&icon_color=ffff00&text_color=ffffff&bg_color=002046&show_icons=true)

**Pull request merged**
