### PR TITLE
Add new theme

### PR DESCRIPTION
**Pull request by yensubldg**

### CODE REVIEW

**Review by yensubldg — COMMENTED** [review]
I can add new theme

**Comment by yensubldg** [comment]
I approve this, and it not work

Vào CN, 19 thg 6, 2022 vào lúc 19:09 vercel[bot] ***@***.***>
đã viết:

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:x: Theme PR does not adhere to our guidelines.
      
## Test results
      
- :x: yensubldg

      
**Result:** :x: Some themes are invalid.


  
Unfortunately, your theme PR does not adhere to our [theme guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution). Please fix the issues below, and we will review your  
 PR again. This pull request will **automatically close in 15 days** if no changes are made. After this time, you must re-open the PR for it to be reviewed.

      
      
## Details
      
        
### Yensubldg theme preview
        
        
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=f707ab&bcolor=9e8d9d).
- :warning: `text_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=de0dcc&bcolor=9e8d9d).


        
title_color: <code>#f707ab</code> | icon_color: <code>#2b0828</code> | text_color: <code>#de0dcc</code> | bg_color: <code>#9e8d9d</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=f707ab&icon_color=2b0828&text_color=de0dcc&bg_color=9e8d9d&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=f707ab&icon_color=2b0828&text_color=de0dcc&bg_color=9e8d9d&show_icons=true)

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1819#issuecomment-1264647253) comment above for more information.

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:x: Theme PR does not adhere to our guidelines.
      
## Test results
      
- :x: yensubldg

      
**Result:** :x: Some themes are invalid.


  
Unfortunately, your theme PR does not adhere to our [theme guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution). Please fix the issues below, and we will review your  
 PR again. This pull request will **automatically close in 15 days** if no changes are made. After this time, you must re-open the PR for it to be reviewed.

      
      
## Details
      
        
### Yensubldg theme preview
        
        
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=f707ab&bcolor=9e8d9d).
- :warning: `text_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=de0dcc&bcolor=9e8d9d).


        
title_color: <code>#f707ab</code> | icon_color: <code>#2b0828</code> | text_color: <code>#de0dcc</code> | bg_color: <code>#9e8d9d</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=f707ab&icon_color=2b0828&text_color=de0dcc&bg_color=9e8d9d&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=f707ab&icon_color=2b0828&text_color=de0dcc&bg_color=9e8d9d&show_icons=true)

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1819#issuecomment-1264656689) comment above for more information.

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1819#issuecomment-1264647253) comment above for more information.

**Comment by yensubldg** [comment]
I seem this is bad theme

**Pull request closed without merging**
