### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by J0rgeSerran0**
Microsoft Visual Studio theme

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title-color: <code>#d59dff</code>
      
icon-color: <code>#d59dff</code>
      
text-color: <code>#ffffff</code>
      
bg-color: <code>#3b2e58</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=d59dff&icon_color=d59dff&text_color=ffffff&bg_color=3b2e58&show_icons=true)

**Comment by J0rgeSerran0** [comment]
😳😥

**Comment by anuraghazra** [comment]
Hi @J0rgeSerran0 do you have the original theme link? because this looks like Palenight to me

**Comment by J0rgeSerran0** [comment]
Hi @anuraghazra 

I'm sorry, but I don't understand what you mean with the original theme link.

**Pull request closed without merging**
