### PR TITLE
infra(dependabot): configure commits message to match conventional commits rules

### PR DESCRIPTION
**Pull request by qwerty541**

### CODE REVIEW

**Comment by rickstaa** [comment]
@qwerty541 can you explain why this is needed? I thought these were already the defaults. See this PR https://github.com/rickstaa/panda-gazebo/commit/de2253a3e989900c46741fa5591139fa3d4528fe that was generated by https://github.com/rickstaa/panda-gazebo/blob/noetic/.github/dependabot.yml.

**Review by qwerty541 — COMMENTED** [review]
> @qwerty541 can you explain why this is needed? I thought these were already the defaults. See this PR [rickstaa/panda-gazebo@de2253a](https://github.com/rickstaa/panda-gazebo/commit/de2253a3e989900c46741fa5591139fa3d4528fe) that https://github.com/rickstaa/panda-gazebo/blob/noetic/.github/dependabot.yml generated.
> 
> ```yaml
> version: 2
> updates:
>   # Maintain dependencies for GitHub Actions.
>   - package-ecosystem: "github-actions"
>     directory: "/"
>     schedule:
>       interval: "weekly"
>     ignore:
>       - dependency-name: "*"
>         update-types: ["version-update:semver-patch"]
> ```

@rickstaa You can check any pull request recently opened by dependabot in this repository and there will be uppercase first prefix letter instead of lowercase, for example  https://github.com/anuraghazra/github-readme-stats/pull/3449. I have no idea why different repositories have different dependabot default configs.

**Comment by rickstaa** [comment]
> > @qwerty541 can you explain why this is needed? I thought these were already the defaults. See this PR [rickstaa/panda-gazebo@de2253a](https://github.com/rickstaa/panda-gazebo/commit/de2253a3e989900c46741fa5591139fa3d4528fe) that https://github.com/rickstaa/panda-gazebo/blob/noetic/.github/dependabot.yml generated.
> > ```yaml
> > version: 2
> > updates:
> >   # Maintain dependencies for GitHub Actions.
> >   - package-ecosystem: "github-actions"
> >     directory: "/"
> >     schedule:
> >       interval: "weekly"
> >     ignore:
> >       - dependency-name: "*"
> >         update-types: ["version-update:semver-patch"]
> > ```
> 
> @rickstaa You can check any pull request recently opened by dependabot in this repository and there will be uppercase first prefix letter instead of lowercase, for example #3449. I have no idea why different repositories have different dependabot default configs.

O damn, that is strange. Feel free to merge it then 👍🏻.

**Review by rickstaa — APPROVED** [review]

**Comment by qwerty541** [comment]
> > > @qwerty541 can you explain why this is needed? I thought these were already the defaults. See this PR [rickstaa/panda-gazebo@de2253a](https://github.com/rickstaa/panda-gazebo/commit/de2253a3e989900c46741fa5591139fa3d4528fe) that https://github.com/rickstaa/panda-gazebo/blob/noetic/.github/dependabot.yml generated.
> > > ```yaml
> > > version: 2
> > > updates:
> > >   # Maintain dependencies for GitHub Actions.
> > >   - package-ecosystem: "github-actions"
> > >     directory: "/"
> > >     schedule:
> > >       interval: "weekly"
> > >     ignore:
> > >       - dependency-name: "*"
> > >         update-types: ["version-update:semver-patch"]
> > > ```
> > 
> > 
> > @rickstaa You can check any pull request recently opened by dependabot in this repository and there will be uppercase first prefix letter instead of lowercase, for example #3449. I have no idea why different repositories have different dependabot default configs.
> 
> O damn, that is strange. Feel free to merge it then 👍🏻.



> > > @qwerty541 can you explain why this is needed? I thought these were already the defaults. See this PR [rickstaa/panda-gazebo@de2253a](https://github.com/rickstaa/panda-gazebo/commit/de2253a3e989900c46741fa5591139fa3d4528fe) that https://github.com/rickstaa/panda-gazebo/blob/noetic/.github/dependabot.yml generated.
> > > ```yaml
> > > version: 2
> > > updates:
> > >   # Maintain dependencies for GitHub Actions.
> > >   - package-ecosystem: "github-actions"
> > >     directory: "/"
> > >     schedule:
> > >       interval: "weekly"
> > >     ignore:
> > >       - dependency-name: "*"
> > >         update-types: ["version-update:semver-patch"]
> > > ```
> > 
> > 
> > @rickstaa You can check any pull request recently opened by dependabot in this repository and there will be uppercase first prefix letter instead of lowercase, for example #3449. I have no idea why different repositories have different dependabot default configs.
> 
> O damn, that is strange. Feel free to merge it then 👍🏻.

Thanks!

**Pull request merged**
