### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by PamLissa**

### CODE REVIEW

**Comment by anuraghazra** [comment]
**Automated Theme preview**  
      
      
title_color: <code>#B2A0FA</code> | icon_color: <code>#8258FF</code> | text_color: <code>#AACFFE</code> | bg_color: <code>#1B1A52</code>
      
      
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=B2A0FA&icon_color=8258FF&text_color=AACFFE&bg_color=1B1A52&show_icons=true)

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=B2A0FA&icon_color=8258FF&text_color=AACFFE&bg_color=1B1A52&show_icons=true)
      
      
  
Hi thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).  
  
We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

**Comment by anuraghazra** [comment]
**Automated Theme preview**  
      
      
title_color: <code>#B2A0FA</code> | icon_color: <code>#8258FF</code> | text_color: <code>#AACFFE</code> | bg_color: <code>#1B1A52</code>
      
      
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=B2A0FA&icon_color=8258FF&text_color=AACFFE&bg_color=1B1A52&show_icons=true)

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=B2A0FA&icon_color=8258FF&text_color=AACFFE&bg_color=1B1A52&show_icons=true)
      
      
  
Hi thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).  
  
We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

**Comment by anuraghazra** [comment]
Hi @PamLissa the theme colors looks great, but there is already a vscode theme named night-sky in the marketplace, can you name your theme differently?

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:x: Theme PR does not adhere to our guidelines.
      
## Test results
      
- :x: night-sky

      
**Result:** :x: Some themes are invalid.


  
Unfortunately, your theme PR does not adhere to our [theme guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution). Please fix the issues below, and we will review your  
 PR again. This pull request will **automatically close in 15 days** if no changes are made. After this time, you must re-open the PR for it to be reviewed.

      
      
## Details
      
        
### Night-sky theme preview
        
        
- :warning: Theme name isn't in snake_case.
- :warning: `icon_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=8258FF&bcolor=1B1A52).


        
title_color: <code>#B2A0FA</code> | icon_color: <code>#8258FF</code> | text_color: <code>#AACFFE</code> | bg_color: <code>#1B1A52</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=B2A0FA&icon_color=8258FF&text_color=AACFFE&bg_color=1B1A52&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=B2A0FA&icon_color=8258FF&text_color=AACFFE&bg_color=1B1A52&show_icons=true)

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1338#issuecomment-1264658475) comment above for more information.

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1338#issuecomment-1264658475) comment above for more information.

**Pull request closed without merging**
