### PR TITLE
Add new theme

### PR DESCRIPTION
**Pull request by HorebParraud**
CleanShot 2021-09-15 at 01 19 50@2x

---

![Horeb's GitHub stats][card]

[card]: https://github-readme-stats.vercel.app/api?username=HorebParraud&count_private=true&hide=contribs,prs,issues&show_icons=true&title_color=ff7372&icon_color=6cffd0&text_color=dbdbdb&bg_color=252334&hide_border=TRUE

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title_color: <code>#ff7372</code> | icon_color: <code>#6cffd0</code> | text_color: <code>#dbdbdb</code> | bg_color: <code>#252334</code>
      
      
Link: https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ff7372&icon_color=6cffd0&text_color=dbdbdb&bg_color=252334&show_icons=true

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ff7372&icon_color=6cffd0&text_color=dbdbdb&bg_color=252334&show_icons=true)
      
      
  
> Hi thanks for the theme contribution, please read our theme contribution guidelines

  
> We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 
  
> Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

**Comment by HorebParraud** [comment]
this is a theme inspired by the theme I use on vscode

**Comment by anuraghazra** [comment]
Looks very nice, what is it called?

**Comment by HorebParraud** [comment]
Aura theme, iI was inspired by this [repo](https://github.com/daltonmenezes/aura-theme), I made all the configurations of my arch in this style

**Comment by anuraghazra** [comment]
Looks cool! Thanks for the contribution.

**Pull request merged**
