### PR TITLE
Adding gold and all black themes

### PR DESCRIPTION
**Pull request by PhelipeRocha99**
These are my two themes suggestions... I hope you enjoy 😊 

This is "**Gold**" Theme
image

This is "**All Black"** Theme
image

### CODE REVIEW

**Comment by anuraghazra** [comment]
**Automated Theme Preview**  
      
      
- :warning: `text_color` does not passes [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=976909&bcolor=010409)


      
title_color: <code>#FFB300</code> | icon_color: <code>#FFB300</code> | text_color: <code>#976909</code> | bg_color: <code>#010409</code>
      
      
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FFB300&icon_color=FFB300&text_color=976909&bg_color=010409&show_icons=true)

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FFB300&icon_color=FFB300&text_color=976909&bg_color=010409&show_icons=true)
      
      
  
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).  
  
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1570#issuecomment-1264657980) comment above for more information.

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:x: Theme PR does not adhere to our guidelines.
      
## Test results
      
- :x: gold
- :x: all_black

      
**Result:** :x: Some themes are invalid.


  
Unfortunately, your theme PR does not adhere to our [theme guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution). Please fix the issues below, and we will review your  
 PR again. This pull request will **automatically close in 15 days** if no changes are made. After this time, you must re-open the PR for it to be reviewed.

      
      
## Details
      
        
### Gold theme preview
        
        
- :warning: `text_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=976909&bcolor=010409).


        
title_color: <code>#FFB300</code> | icon_color: <code>#FFB300</code> | text_color: <code>#976909</code> | bg_color: <code>#010409</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FFB300&icon_color=FFB300&text_color=976909&bg_color=010409&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FFB300&icon_color=FFB300&text_color=976909&bg_color=010409&show_icons=true)
      
        
### All_black theme preview
        
        
- :warning: `icon_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=666&bcolor=000).
- :warning: `text_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=444&bcolor=000).


        
title_color: <code>#999</code> | icon_color: <code>#666</code> | text_color: <code>#444</code> | bg_color: <code>#000</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=999&icon_color=666&text_color=444&bg_color=000&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=999&icon_color=666&text_color=444&bg_color=000&show_icons=true)

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1570#issuecomment-1264657980) comment above for more information.

**Comment by rickstaa** [comment]
This PR has been automatically closed due to inactivity. Please feel free to reopen it if you need to continue working on it.	
Thank you for your contributions.

**Pull request closed without merging**
