### PR TITLE
add ncoder theme

### PR DESCRIPTION
**Pull request by n-c0d3r**

### CODE REVIEW

**Comment by anuraghazra** [comment]
**Automated Theme Preview**  
      
      

      
title_color: <code>#61dafb</code> | icon_color: <code>#61dafb</code> | text_color: <code>#ffffff</code> | bg_color: <code>#20232a</code>
      
      
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=61dafb&icon_color=61dafb&text_color=ffffff&bg_color=20232a&border_color=0c1a25&show_icons=true)

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=61dafb&icon_color=61dafb&text_color=ffffff&bg_color=20232a&border_color=0c1a25&show_icons=true)
      
      
  
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).  
  
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: ncoder

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Ncoder theme preview
        
        

        
title_color: <code>#61dafb</code> | icon_color: <code>#61dafb</code> | text_color: <code>#ffffff</code> | bg_color: <code>#20232a</code> | border_color: <code>#0c1a25</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=61dafb&icon_color=61dafb&text_color=ffffff&bg_color=20232a&border_color=0c1a25&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=61dafb&icon_color=61dafb&text_color=ffffff&bg_color=20232a&border_color=0c1a25&show_icons=true)

**Review by rickstaa — APPROVED** [review]

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: ncoder

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Ncoder theme preview
        
        

        
title_color: <code>#61dafb</code> | icon_color: <code>#61dafb</code> | text_color: <code>#ffffff</code> | bg_color: <code>#20232a</code> | border_color: <code>#0c1a25</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=61dafb&icon_color=61dafb&text_color=ffffff&bg_color=20232a&border_color=0c1a25&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=61dafb&icon_color=61dafb&text_color=ffffff&bg_color=20232a&border_color=0c1a25&show_icons=true)

**Review by rickstaa — APPROVED** [review]

**Review by rickstaa — APPROVED** [review]

**Comment by anuraghazra** [comment]
We are currently pausing addition of new themes. If this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

**Pull request closed without merging**
