### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by teeradon43**
image

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title_color: <code>#F7E252</code> | icon_color: <code>#10</code> | text_color: <code>#F23D92</code> | bg_color: <code>#CA3AB0</code>
      
      
Link: https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=F7E252&icon_color=10&text_color=F23D92&bg_color=CA3AB0&show_icons=true

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=F7E252&icon_color=10&text_color=F23D92&bg_color=CA3AB0&show_icons=true)
      
      
  
> Hi thanks for the theme contribution, please read our theme contribution guidelines

  
> We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 
  
> Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1292#issuecomment-1264658756) comment above for more information.

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:x: Theme PR does not adhere to our guidelines.
      
## Test results
      
- :x: neon_purpleRed

      
**Result:** :x: Some themes are invalid.


  
Unfortunately, your theme PR does not adhere to our [theme guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution). Please fix the issues below, and we will review your  
 PR again. This pull request will **automatically close in 15 days** if no changes are made. After this time, you must re-open the PR for it to be reviewed.

      
      
## Details
      
          
### Neon_purpleRed theme preview
          
          
- :warning: Theme name isn't in snake_case.

          
- :x: Theme color property `bg_color` is not a valid hex color: <code>#10,F23D92,CA3AB0,9138A7,69208E</code>.


          
>:x: Cannot create theme preview.

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1292#issuecomment-1264658756) comment above for more information.

**Comment by rickstaa** [comment]
This PR has been automatically closed due to inactivity. Please feel free to reopen it if you need to continue working on it.	
Thank you for your contributions.

**Pull request closed without merging**
