### PR TITLE
Add testing theme

### PR DESCRIPTION
**Pull request by rickstaa**
This quickly tests if the theme preview action is working.

### CODE REVIEW

**Comment by rickstaa** [comment]
Works! Great 🚀.

**Comment by rickstaa** [comment]
### Automated Theme Preview
    
  
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)


    
#### Test theme preview
    
    

    

    
title_color: <code>#9ccfd8</code> | icon_color: <code>#ebbcba</code> | text_color: <code>#e0def4</code> | bg_color: <code>#191724</code>

    
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

    
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

**Comment by rickstaa** [comment]
### Automated Theme Preview
    
  
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)


    
#### Test theme preview
    
    

    

    
title_color: <code>#9ccfd8</code> | icon_color: <code>#ebbcba</code> | text_color: <code>#e0def4</code> | bg_color: <code>#191724</code>

    
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

    
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

**Comment by rickstaa** [comment]
### Automated Theme Preview
    
  
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)


    
#### Test theme preview
    
    

    

    
title_color: <code>#9ccfd8</code> | icon_color: <code>#ebbcba</code> | text_color: <code>#e0def4</code> | bg_color: <code>#191724</code>

    
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

    
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

**Comment by rickstaa** [comment]
### Automated Theme Preview
    
  
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)


    
#### Test theme preview
    
    

    

    
title_color: <code>#9ccfd8</code> | icon_color: <code>#ebbcba</code> | text_color: <code>#e0def4</code> | bg_color: <code>#191724</code>

    
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

    
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

**Comment by rickstaa** [comment]
## Automated Theme Preview
    
  
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

    
    
**Themes:**
    
- test
    
    
### Test theme preview
    
    

    

    
title_color: <code>#9ccfd8</code> | icon_color: <code>#ebbcba</code> | text_color: <code>#e0def4</code> | bg_color: <code>#191724</code>

    
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

    
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

**Comment by rickstaa** [comment]
## Automated Theme Preview
      
  
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

      
      
**Themes:**
      
- test
    
    
### Test theme preview
    
    

    
title_color: <code>#9ccfd8</code> | icon_color: <code>#ebbcba</code> | text_color: <code>#e0def4</code> | bg_color: <code>#191724</code>

    
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

    
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

**Comment by rickstaa** [comment]
## Automated Theme Preview
      
  
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

      
      
**Themes:**
      
- test
    
    
### Test theme preview
    
    

    
title_color: <code>#9ccfd8</code> | icon_color: <code>#ebbcba</code> | text_color: <code>#e0def4</code> | bg_color: <code>#191724</code>

    
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

    
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

**Comment by rickstaa** [comment]
## Automated Theme Preview
      
  
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

      
      
**Themes:**
      
- test
    
    
### Test theme preview
    
    

    
title_color: <code>#9ccfd8</code> | icon_color: <code>#ebbcba</code> | text_color: <code>#e0def4</code> | bg_color: <code>#191724</code>

    
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

    
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

**Comment by rickstaa** [comment]
## Automated Theme Preview
      
  
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

    

      
**Themes:**
      
- test
      
      
### Test theme preview
      
      

      
title_color: <code>#9ccfd8</code> | icon_color: <code>#ebbcba</code> | text_color: <code>#e0def4</code> | bg_color: <code>#191724</code>

      
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

**Comment by rickstaa** [comment]
## Automated Theme Preview
      
  
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

    
    
**Themes:**
    -:white_check_mark: test

    **Result:**

    :white_check_mark: All themes passed.
    
    
      
### Test theme preview
      
      

      
title_color: <code>#9ccfd8</code> | icon_color: <code>#ebbcba</code> | text_color: <code>#e0def4</code> | bg_color: <code>#191724</code>

      
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

**Comment by rickstaa** [comment]
## Automated Theme Preview
      
  
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

    
    
**Themes:**
    - :white_check_mark: test

    
**Result:**

    :white_check_mark: All themes passed.
    
    
      
### Test theme preview
      
      

      
title_color: <code>#9ccfd8</code> | icon_color: <code>#ebbcba</code> | text_color: <code>#e0def4</code> | bg_color: <code>#191724</code>

      
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

**Comment by rickstaa** [comment]
## Automated Theme Preview
      
  
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

    
    
**Themes:**
    - :white_check_mark: test

    
**Result:**

    
:white_check_mark: All themes passed.
    
    
      
### Test theme preview
      
      

      
title_color: <code>#9ccfd8</code> | icon_color: <code>#ebbcba</code> | text_color: <code>#e0def4</code> | bg_color: <code>#191724</code>

      
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

**Comment by rickstaa** [comment]
## Automated Theme Preview
      
  
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

    
    
### Test results
    - :heavy_check_mark: test

    
:heavy_check_mark: All themes passed.
    
    
### Details
    
      
#### Test theme preview
      
      

      
title_color: <code>#9ccfd8</code> | icon_color: <code>#ebbcba</code> | text_color: <code>#e0def4</code> | bg_color: <code>#191724</code>

      
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

**Comment by rickstaa** [comment]
## Automated Theme Preview
      
  
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

    
    
### Test results
    
- :heavy_check_mark: test

    
:heavy_check_mark: All themes passed.
    
    
### Details
    
      
#### Test theme preview
      
      

      
title_color: <code>#9ccfd8</code> | icon_color: <code>#ebbcba</code> | text_color: <code>#e0def4</code> | bg_color: <code>#191724</code>

      
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

    
    
## Test results
    
- :heavy_check_mark: test

    
:heavy_check_mark: All themes passed.
    
    
## Details
    
      
### Test theme preview
      
      

      
title_color: <code>#9ccfd8</code> | icon_color: <code>#ebbcba</code> | text_color: <code>#e0def4</code> | bg_color: <code>#191724</code>

      
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

**Comment by anuraghazra** [comment]
**Automated Theme Preview**

      

      
title_color: <code>#9ccfd8</code> | icon_color: <code>#ebbcba</code> | text_color: <code>#e0def4</code> | bg_color: <code>#191724</code>

      
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

      
  
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

**Pull request closed without merging**
