### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by Jess2D**
Add unicorn theme

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title_color: <code>#DEDAF9</code> | icon_color: <code>#FE7295</code> | text_color: <code>#DEDAF9</code> | bg_color: <code>#8176FF</code>
      
      
Link: https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=DEDAF9&icon_color=FE7295&text_color=DEDAF9&bg_color=8176FF&show_icons=true

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=DEDAF9&icon_color=FE7295&text_color=DEDAF9&bg_color=8176FF&show_icons=true)
      
      
  
> Hi thanks for the theme contribution, please read our theme contribution guidelines

  
> We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 
  
> Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1269#issuecomment-1264658769) comment above for more information.

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:x: Theme PR does not adhere to our guidelines.
      
## Test results
      
- :x: unicorn

      
**Result:** :x: Some themes are invalid.


  
Unfortunately, your theme PR does not adhere to our [theme guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution). Please fix the issues below, and we will review your  
 PR again. This pull request will **automatically close in 15 days** if no changes are made. After this time, you must re-open the PR for it to be reviewed.

      
      
## Details
      
        
### Unicorn theme preview
        
        
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=DEDAF9&bcolor=8176FF).
- :warning: `icon_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=FE7295&bcolor=8176FF).
- :warning: `text_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=DEDAF9&bcolor=8176FF).


        
title_color: <code>#DEDAF9</code> | icon_color: <code>#FE7295</code> | text_color: <code>#DEDAF9</code> | bg_color: <code>#8176FF</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=DEDAF9&icon_color=FE7295&text_color=DEDAF9&bg_color=8176FF&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=DEDAF9&icon_color=FE7295&text_color=DEDAF9&bg_color=8176FF&show_icons=true)

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1269#issuecomment-1264658769) comment above for more information.

**Pull request closed without merging**
