### PR TITLE
Added "pythonice" theme

### PR DESCRIPTION
**Pull request by betterTisen**
### Theme Name : Pythonice

[iceiceice's github stats](https://github.com/betterTisen)

### CODE REVIEW

**Comment by anuraghazra** [comment]
Hi @betterTisen thanks for the theme contribution. this looks good. just the contrast is low the colors are kinda washed out maybe darken them a bit

**Comment by betterTisen** [comment]
I improved that contrast to make them look brighter

[iceiceice's github stats](https://github.com/betterTisen)

**Comment by betterTisen** [comment]
> Hi @betterTisen thanks for the theme contribution. this looks good. just the contrast is low the colors are kinda washed out maybe darken them a bit

I improved that contrast to make them look brighter

[iceiceice's github stats](https://github.com/betterTisen)

**Comment by HPaulson** [comment]
Just me, or does this look a bit too similar to the default theme?

**Comment by betterTisen** [comment]
@HPaulson 

Haha, I use the color of the Python logo as the theme

[iceiceice's github stats](https://github.com/betterTisen)
[iceiceice's github stats](https://github.com/betterTisen)

emm🤔...it does look like the default theme

**Comment by HPaulson** [comment]
@betterTisen Yeah... honestly the default card should just have the icons yellow since it looks nicer anyway, but think it's a bit too close to have a whole entire new theme

**Comment by betterTisen** [comment]
@HPaulson yes, I closed this pr

**Pull request closed without merging**
