### PR TITLE
Top languages card donut vertical layout

### PR DESCRIPTION
**Pull request by qwerty541**
image

Preview deployed there: https://github-readme-stats-1svgrsiyn-qwerty541.vercel.app

Option: `https://github-readme-stats-1svgrsiyn-qwerty541.vercel.app/api/top-langs?username=qwerty541&layout=donut-vertical`

TODOS:

- [x] rebase master
- [x] refactoring
- [x] docs
- [x] tests
- [x] animations

### CODE REVIEW

**Comment by rickstaa** [comment]
Hey @qwerty541. I think it is wonderful that you have contributed so much to the project in the last days 🚀! I asked @anuraghazra to add you as a collaborator. You are welcome to accept or decline 👍🏻.

Sadly, the donut layout has already been implemented in https://github.com/anuraghazra/github-readme-stats/pull/2099 😅. I am planning to merge it this week when the @arndom implements the changes I requested. You can find the other top bugs, feature requests and pull requests in https://github.com/anuraghazra/github-readme-stats/issues/1935.

**Comment by qwerty541** [comment]
> Hey @qwerty541. I think it is wonderful that you have contributed so much to the project in the last days 🚀! I asked @anuraghazra to add you as a collaborator. You are welcome to accept or decline 👍🏻.
> 
> Sadly, the donut layout has already been implemented in #2099 😅. I am planning to merge it this week when the @arndom implements the changes I requested. You can find the other top bugs, feature requests and pull requests in #1935.

Hey @rickstaa. Thank you for the collaboration invitation, i am going to accept it when it will be sent.

I feel like a fool for not checking for open pull requests on the issue before starting to work. I'll try to be more careful in the future.

I want to draw your attention to what my pull request offers a DIFFERENT design of top languages card with donut than #2099. In my pull request, the objects are arranged vertically, the amount of empty space is minimized, the card turned out to be quite compact. In another pull request, the objects are arranged horizontally, the card turned out to be quite cumbersome, and it has an obvious disadvantage, which is that with a large number of different languages there will be a lot of empty space above and below the donut. For this reason, some users may prefer to use my design. What do you think about supporting both layouts like `donut-vertical` and `donut-horizontal`?

**Comment by rickstaa** [comment]
> > Hey @qwerty541. I think it is wonderful that you have contributed so much to the project in the last days rocket! I asked @anuraghazra to add you as a collaborator. You are welcome to accept or decline 👍🏻.
> > Sadly, the donut layout has already been implemented in #2099 sweat_smile. I am planning to merge it this week when the @arndom implements the changes I requested. You can find the other top bugs, feature requests and pull requests in #1935.
> 
> Hey @rickstaa. Thank you for the collaboration invitation, i am going to accept it when it will be sent.
> 
> I feel like a fool for not checking for open pull requests on the issue before starting to work. I'll try to be more careful in the future.
> 
> I want to draw your attention to what my pull request offers a DIFFERENT design of top languages card with donut than #2099. In my pull request, the objects are arranged vertically, the amount of empty space is minimized, the card turned out to be quite compact. In another pull request, the objects are arranged horizontally, the card turned out to be quite cumbersome, and it has an obvious disadvantage, which is that with a large number of different languages there will be a lot of empty space above and below the donut. For this reason, some users may prefer to use my design. What do you think about supporting both layouts like `donut-vertical` and `donut-horizontal`?

> Hey @rickstaa. Thank you for the collaboration invitation, i am going to accept it when it will be sent.

Amazing! It would be an honour to have you on the team 🚀.

> I feel like a fool for not checking for open pull requests on the issue before starting to work. I'll try to be more careful in the future.

No problem, it is easy to get lost in 180 open pull requests 😅. That is why merging https://github.com/anuraghazra/github-readme-stats/pull/2489 is a high priority since that will remove 36 translation repositories.

> I want to draw your attention to what my pull request offers a DIFFERENT design of top languages card with donut than #2099. In my pull request, the objects are arranged vertically, the amount of empty space is minimized, the card turned out to be quite compact. In another pull request, the objects are arranged horizontally, the card turned out to be quite cumbersome, and it has an obvious disadvantage, which is that with a large number of different languages there will be a lot of empty space above and below the donut. For this reason, some users may prefer to use my design. What do you think about supporting both layouts like `donut-vertical` and `donut-horizontal`?

I think having two donut layouts is great if duplicate code is kept to the minimum. Let's keep this PR open so that you can rebase it on top of the `master` branch when https://github.com/anuraghazra/github-readme-stats/pull/2099 is merged.

**Review by qwerty541 — COMMENTED** [review]
@rickstaa Hey, Rick! I finished work on this pull request, can you review it?

**Review by rickstaa — APPROVED** [review]

**Comment by rickstaa** [comment]
Great pull request! Merged into master.

**Pull request merged**
