### PR TITLE
Docs: improve quick align tip section

### PR DESCRIPTION
**Pull request by qwerty541**

### CODE REVIEW

**Comment by rickstaa** [comment]
@qwerty541 I think the location of this item is correct, as it is a tip for all cards. I would change the right card to another card, like the stats card.

**Comment by rickstaa** [comment]
<a href="https://github.com/anuraghazra/github-readme-stats">
  
</a>
<a href="https://github.com/anuraghazra/convoychat">
  
</a>
<a href="https://github.com/anuraghazra/github-readme-stats">
  
</a>
</a>
<a href="https://github.com/anuraghazra/github-readme-stats">
  
</a>

```md
<a href="https://github.com/anuraghazra/github-readme-stats">
  <img align="center" src="https://github-readme-stats.vercel.app/api?username=anuraghazra&repo=github-readme-stats" />
</a>
<a href="https://github.com/anuraghazra/convoychat">
  <img align="center" src="https://github-readme-stats.vercel.app/api/top-langs?username=anuraghazra&layout=compact&langs_count=8&repo=convoychat" />
</a>
<a href="https://github.com/anuraghazra/github-readme-stats">
  <img align="center" src="https://github-readme-stats.vercel.app/api/pin?username=anuraghazra&repo=github-readme-stats" />
</a>
</a>
<a href="https://github.com/anuraghazra/github-readme-stats">
  <img align="center" src="https://github-readme-stats.vercel.app/api/pin?username=anuraghazra&repo=github-readme-stats" />
</a>
```

**Review by qwerty541 — COMMENTED** [review]
> @qwerty541 I think the location of this item is correct, as it is a tip for all cards. I would change the right card to another card, like the stats card.

@rickstaa Yes, you are right, this tip can be used for all card. I have updated the code by adding additional example with stats and languages cards and by adding opt-in example preview. Please check it. I decided to guide people with both examples because align method is different, you need to specify height and width manually for stats and languages cards to set them at center.

изображение

**Review by rickstaa — APPROVED** [review]

**Comment by rickstaa** [comment]
> > @qwerty541 I think the location of this item is correct, as it is a tip for all cards. I would change the right card to another card, like the stats card.
> 
> @rickstaa Yes, you are right, this tip can be used for all card. I have updated the code by adding additional example with stats and languages cards and by adding opt-in example preview. Please check it. I decided to guide people with both examples because align method is different, you need to specify height and width manually for stats and languages cards to set them at center.
> 
> изображение

Amazing thanks!

**Pull request merged**
