### PR TITLE
docs: fix relative README links

### LINKED ISSUE #3066: README `src/calculateRank.js` Link Inconsistent
### Describe the bug

 The [src/calculateRank.js](./src/calculateRank.js) link inside the README file does not work consistently, i.e., if you are on `https://github.com/anuraghazra/github-readme-stats` and you click it, it takes you to `https://github.com/anuraghazra/src/calculateRank.js` incorrectly.

### Expected behavior

I would expect to be taken to the `src/calculateRank.js` file within the current repository.

### Screenshots / Live demo link

https://streamable.com/ocjjn1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rickstaa**
Fixes #3066.

### CODE REVIEW

**Review by qwerty541 — COMMENTED** [review]
@rickstaa Are you sure that this will work? I have opened redme file on your branch and this link still broken:

chrome_T8dVlfAr7V

I also have some doubts about if we need this backslashes near each admonition

https://github.com/anuraghazra/github-readme-stats/pull/3067/files#diff-5a831ea67cf5cf8703b0de46901ab25bd191f56b320053be9332d9a3b0d01d15R126

**Review by AbdullahWins — APPROVED** [review]
Good Job!!

**Review by qwerty541 — APPROVED** [review]
@rickstaa As i told in my previous comment i have doubts about if this solution will work, but you can merge it and check if you want.

**Comment by rickstaa** [comment]
Related to https://github.com/anuraghazra/github-readme-stats/pull/3140#issuecomment-1692745629.

**Comment by rickstaa** [comment]
@ qwerty541 The relative links should work on all branches with these close files. The problem is with the `tree` prefix placed before your URL by GitHub. This prefix should not be present when people view the main README. Let's try this first, and otherwise, use absolute URLs.

**Pull request merged**
