### PR TITLE
add send_tech theme

### PR DESCRIPTION
**Pull request by eichenbergerche**
nice themes, here are my two cents =)

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title_color: <code>#FC784A</code> | icon_color: <code>#F75762</code> | text_color: <code>#EEEEEE</code> | bg_color: <code>#0d0c2d</code>
      
      
Link: https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FC784A&icon_color=F75762&text_color=EEEEEE&bg_color=0d0c2d&show_icons=true

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FC784A&icon_color=F75762&text_color=EEEEEE&bg_color=0d0c2d&show_icons=true)
      
      
  
> Hi thanks for the theme contribution, please read our theme contribution guidelines

  
> We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 
  
> Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title_color: <code>#FC784A</code> | icon_color: <code>#F75762</code> | text_color: <code>#EEEEEE</code> | bg_color: <code>#0d0c2d</code>
      
      
Link: https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FC784A&icon_color=F75762&text_color=EEEEEE&bg_color=0d0c2d&show_icons=true

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FC784A&icon_color=F75762&text_color=EEEEEE&bg_color=0d0c2d&show_icons=true)
      
      
  
> Hi thanks for the theme contribution, please read our theme contribution guidelines

  
> We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 
  
> Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: send_tech

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Send_tech theme preview
        
        

        
title_color: <code>#FC784A</code> | icon_color: <code>#F75762</code> | text_color: <code>#EEEEEE</code> | bg_color: <code>#0d0c2d</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FC784A&icon_color=F75762&text_color=EEEEEE&bg_color=0d0c2d&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FC784A&icon_color=F75762&text_color=EEEEEE&bg_color=0d0c2d&show_icons=true)

**Review by rickstaa — APPROVED** [review]

**Review by rickstaa — APPROVED** [review]

**Review by qwerty541 — APPROVED** [review]
Nice theme! I have resolved conflicts with master branch to be able to merge this PR after it receive enough community support.

@rickstaa We have already decided that the decision to merge themes is based on feedback from the community, but we have not decided on the specific number of thumbs up that a pull request should receive in order to be considered that the community supported it. What do you think?

**Comment by anuraghazra** [comment]
We are currently pausing addition of new themes. If this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

**Pull request closed without merging**
