### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by avanti-bhandarkar**
Added [Nord theme]( https://www.nordtheme.com/)

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title-color: <code>#8fbcbb</code>
      
icon-color: <code>#e5e9f0</code>
      
text-color: <code>#eceff4</code>
      
bg-color: <code>#2e3440</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=8fbcbb&icon_color=e5e9f0&text_color=eceff4&bg_color=2e3440&show_icons=true)

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title-color: <code>#8fbcbb</code>
      
icon-color: <code>#e5e9f0</code>
      
text-color: <code>#eceff4</code>
      
bg-color: <code>#2e3440</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=8fbcbb&icon_color=e5e9f0&text_color=eceff4&bg_color=2e3440&show_icons=true)

**Comment by anuraghazra** [comment]
Sorry we already have nord theme. please check the theme collections.

https://github.com/anuraghazra/github-readme-stats/tree/master/themes

**Comment by avanti-bhandarkar** [comment]
Ok, sorry about that

**Pull request closed without merging**
