### PR TITLE
style(theme): Default transparent theme

### PR DESCRIPTION
**Pull request by Isaiah-Hamilton**
A transparent theme for #1100. This theme uses the default theme colors but with a transparent background.

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title_color: <code>#2f80ed</code> | icon_color: <code>#4c71f2</code> | text_color: <code>#333</code> | bg_color: <code>#00000000</code>
      
      
Link: https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=2f80ed&icon_color=4c71f2&text_color=333&bg_color=00000000&show_icons=true

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=2f80ed&icon_color=4c71f2&text_color=333&bg_color=00000000&show_icons=true)
      
      
  
> Hi thanks for the theme contribution, please read our theme contribution guidelines

  
> We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 
  
> Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title_color: <code>#2f80ed</code> | icon_color: <code>#4c71f2</code> | text_color: <code>#272727</code> | bg_color: <code>#00000000</code>
      
      
Link: https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=2f80ed&icon_color=4c71f2&text_color=272727&bg_color=00000000&show_icons=true

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=2f80ed&icon_color=4c71f2&text_color=272727&bg_color=00000000&show_icons=true)
      
      
  
> Hi thanks for the theme contribution, please read our theme contribution guidelines

  
> We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 
  
> Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title_color: <code>#2f80ed</code> | icon_color: <code>#4c71f2</code> | text_color: <code>#000</code> | bg_color: <code>#00000000</code>
      
      
Link: https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=2f80ed&icon_color=4c71f2&text_color=000&bg_color=00000000&show_icons=true

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=2f80ed&icon_color=4c71f2&text_color=000&bg_color=00000000&show_icons=true)
      
      
  
> Hi thanks for the theme contribution, please read our theme contribution guidelines

  
> We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 
  
> Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

**Comment by Isaiah-Hamilton** [comment]
closing this pr to make better version.

**Pull request closed without merging**
