### PR TITLE
chore: remove redundant codes

### PR DESCRIPTION
**Pull request by JounQin**
`axios` is Promise based, there is no need to wrap it into a Promise constructor again

### CODE REVIEW

**Comment by anuraghazra** [comment]
@JounQin can you resolve the conflicts?

**Comment by JounQin** [comment]
@anuraghazra Done!

**Comment by anuraghazra** [comment]
Opps look like your branch in not updated with the master.. there are some code changes on master

**Comment by JounQin** [comment]
@anuraghazra Just notice that. 🤣

Not sure why should `headers` be copied?

**Comment by anuraghazra** [comment]
> @anuraghazra Just notice that. 
> 
> Not sure why should `headers` be copied?

headers are copied so that we can pass the Auth headers

**Comment by anuraghazra** [comment]
Thanks for the PR @JounQin

**Comment by JounQin** [comment]
I mean `headers` vs `headers: {...headers}`.

**Comment by anuraghazra** [comment]
> I mean `headers` vs `headers: {...headers}`.

i did that just if i wanted to add some default headers like `{ Cache-Control: 'max-age=10', ...headers }`

**Pull request merged**
