### PR TITLE
Created new theme - slack_purple

### PR DESCRIPTION
**Pull request by Aryankpoor**
Created new theme - ``slack purple`` for public use. It is based on the **slack - purple** theme of vscode.

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title-color: <code>#660077</code>
      
icon-color: <code>#6a5287</code>
      
text-color: <code>#9f0fef</code>
      
bg-color: <code>#f8f8f9</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=660077&icon_color=6a5287&text_color=9f0fef&bg_color=f8f8f9&show_icons=true)

**Comment by anuraghazra** [comment]
This is really annoying @Aryankpoor please review your code and before submitting a PR & don't close/open the same PR 5 times. i've told you already and you are not replying to me.

You literally made/closed these many PRs

https://github.com/anuraghazra/github-readme-stats/pull/511
https://github.com/anuraghazra/github-readme-stats/pull/512
https://github.com/anuraghazra/github-readme-stats/pull/513
https://github.com/anuraghazra/github-readme-stats/pull/533
https://github.com/anuraghazra/github-readme-stats/pull/534
https://github.com/anuraghazra/github-readme-stats/pull/536
https://github.com/anuraghazra/github-readme-stats/pull/537

Please stop doing this. this is not how you open PRs.

Use [Customization options](https://github.com/anuraghazra/github-readme-stats#customization) to try out the theme first before making the Pull Request, and don't close it without my review.

**Comment by Aryankpoor** [comment]
Initially there were some typos in ``index.js`` file which I made due to which the checks were not successful and I had to close the PRs. Won't happen again.

**Comment by anuraghazra** [comment]
> Initially there were some typos in `index.js` file which I made due to which the checks were not successful and I had to close the PRs. Won't happen again.

You don't need to close the PR everytime you make a mistake... you can just edit the PR itself.

**Pull request closed without merging**
