### PR TITLE
Added new theme Bear

### PR DESCRIPTION
**Pull request by RahulMahesh62**
Bear is one of the most downloaded color themes on VSCode. So I created a theme based on that.

### CODE REVIEW

**Comment by RahulMahesh62** [comment]
bear theme
Here's the screenshot of the theme

**Comment by anuraghazra** [comment]
Hi @RahulMahesh62 thanks for theme contribution, can you send a link of the vscode marketplace?

**Comment by RahulMahesh62** [comment]
Yeah.. Here's the link to the theme: https://marketplace.visualstudio.com/items?itemName=dahong.theme-bear

**Comment by anuraghazra** [comment]
Try changing the text color to the blue, and icons color to orange.

**Comment by RahulMahesh62** [comment]
bear

**Comment by anuraghazra** [comment]
@RahulMahesh62 this looks good, thanks!

**Pull request merged**
