### PR TITLE
Added new theme: Ultraviolet

### PR DESCRIPTION
**Pull request by Aryankpoor**

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title-color: <code>#e2f3f5</code>
      
icon-color: <code>#9c1de7</code>
      
text-color: <code>#fcefee</code>
      
bg-color: <code>#581b98</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=e2f3f5&icon_color=9c1de7&text_color=fcefee&bg_color=581b98&show_icons=true)

**Comment by Aryankpoor** [comment]
#### Added new theme: ``ultraviolet`` to ``index.js``

**Comment by anuraghazra** [comment]
Hi thanks for opening the PR

Note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)  we are currently only accepting theme contributions from which are vscode theme inspired & themes which have good color combination.

Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info.

**Comment by Aryankpoor** [comment]
Its based on the pitaya smoothie theme of vscode.View it [**here**](https://marketplace.visualstudio.com/items?itemName=trallard.pitaya-smoothie)

**Comment by anuraghazra** [comment]
Try other combinations then, especially for those icons

**Comment by anuraghazra** [comment]
Don't open a new PR

**Comment by anuraghazra** [comment]
Reopen and edit push the changes on this pr

**Pull request closed without merging**
