### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by akhilbaiju**

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title_color: <code>#DA0000</code> | icon_color: <code>#FF1212</code> | text_color: <code>#FF1212</code> | bg_color: <code>#000000</code>
      
      
Link: https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=DA0000&icon_color=FF1212&text_color=FF1212&bg_color=000000&show_icons=true

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=DA0000&icon_color=FF1212&text_color=FF1212&bg_color=000000&show_icons=true)
      
      
  
> Hi thanks for the theme contribution, please read our theme contribution guidelines

  
> We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 
  
> Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:x: Theme PR does not adhere to our guidelines.
      
## Test results
      
- :x: red_velvet

      
**Result:** :x: Some themes are invalid.


  
Unfortunately, your theme PR does not adhere to our [theme guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution). Please fix the issues below, and we will review your  
 PR again. This pull request will **automatically close in 15 days** if no changes are made. After this time, you must re-open the PR for it to be reviewed.

      
      
## Details
      
        
### Red_velvet theme preview
        
        
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=DA0000&bcolor=000000).


        
title_color: <code>#DA0000</code> | icon_color: <code>#FF1212</code> | text_color: <code>#FF1212</code> | bg_color: <code>#000000</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=DA0000&icon_color=FF1212&text_color=FF1212&bg_color=000000&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=DA0000&icon_color=FF1212&text_color=FF1212&bg_color=000000&show_icons=true)

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/993#issuecomment-1264659497) comment above for more information.

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/993#issuecomment-1264659497) comment above for more information.

**Comment by rickstaa** [comment]
This PR has been automatically closed due to inactivity. Please feel free to reopen it if you need to continue working on it.	
Thank you for your contributions.

**Pull request closed without merging**
