### PR TITLE
Add one_dark_pro

### PR DESCRIPTION
**Pull request by b3dyk**
This colors were taken from One Dark Pro theme in VSCode extention. Please add it and I will use it in my profile

### CODE REVIEW

**Review by Zo-Bro-23 — APPROVED** [review]
Looks good to me! Will merge if it gets enough upvotes (and @rickstaa approves).

**Review by Zo-Bro-23 — CHANGES_REQUESTED** [review]
Oh, and also, please update `/themes/README.md` to list the new theme.

**Review by Zo-Bro-23 — APPROVED** [review]

**Comment by rickstaa** [comment]
@Zo-Bro-23 I'm okay with also including One Dark Pro since it is one of the most popular Vscode Themes (see https://marketplace.visualstudio.com/items?itemName=zhuangtongfa.Material-theme). @anuraghazra However made a comment about not bloating the themes library, so I will leave the decision to him. 😅

**Comment by Zo-Bro-23** [comment]
@rickstaa this looks good to me, ***and*** it's from a VSCode extension. Merge?

**Comment by rickstaa** [comment]
@Zo-Bro-23 since this is one of the most popular vs code themes, I agree it can be merged. Please merge https://github.com/anuraghazra/github-readme-stats/pull/2518 before this one so that the docs README gets updated. 👍🏻

**Review by rickstaa — APPROVED** [review]

**Comment by Zo-Bro-23** [comment]
@b3dyk will merge after we resolve the issue in #2518!

**Pull request merged**
