### PR TITLE
fix: wip fix total commit counts

### LINKED ISSUE #14: Bug: Wrong commit count
Hey 👋 

Cool project, is there a limitation to the number of commits/PRs it can fetch?

They seem to be off by quite a lot for instance - 

image

In normal GitHub search - 
image

### LINKED ISSUE #92: Total commits shown on the card is way less than actual
**Describe the bug**
Total commits shown on the card is way less than actual. A single repo of mine https://github.com/rampatra/Algorithms-and-Data-Structures-in-Java has 230+ commits but the card only shows 108 commits in total. The repo is public too.

**Expected behavior**
I was expecting to sum up the commits in all of my public repos. If it can consider private repos then even better.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
[Ram's github stats](https://rampatra.com)

### PR DESCRIPTION
**Pull request by anuraghazra**
fixes #14 
fixes #92
closes #15 

Currently github readme stats can only fetch total commits of 1year max, because of limitations of Github API mentioned in here https://github.com/anuraghazra/github-readme-stats/issues/14#issuecomment-656559694 but we can fix it by brute forcing and looping over all the years to accumulate total commits of a user as we did in #15 

But there are downsides of this approach in terms on performance because we are looping over all the years and calling the GraphQL Api each time 

### The fix

So as mentioned by @kingthorin in this comment https://github.com/anuraghazra/github-readme-stats/pull/15#issuecomment-657535644 instead of showing "Total commits" we would show "Total Commits (2020)" in order to eliminate any confusion.

And as mentioned in this https://github.com/anuraghazra/github-readme-stats/issues/92#issuecomment-661026467 by @adamyi Github has a experimental REST endpoint to fetch all the commits which we can utilize nicely. 

We've added a new flag "include_all_commits" which would fetch the total commits of a user if enabled otherwise we will show only the last year commits (which is current behaviour)

## Screenshots

@rampatra issue #92

- `&include_all_commits=true`
rampatra_true

- `&include_all_commits=false`
rampatra_false

@anshumanv issue #14 

- `&include_all_commits=true`

anshu_true

- `&include_all_commits=false`
anshu_false

NOTE: As mentioned in github's documentation https://developer.github.com/v3/search/#search-commits this API is experimental and the API may change without advance notice during the preview period.

TODO: 
- Write tests
- Discussion

### CODE REVIEW

**Comment by rampatra** [comment]
I think when `&include_all_commits=true` the year shouldn't be there in the title `Total Commits (2020)`. It should be just `Total Commits`.

**Comment by anshumanv** [comment]
> I think when &include_all_commits=true the year shouldn't be there in the title Total Commits (2020). It should be just Total Commits.

already, check PR description

**Comment by anshumanv** [comment]
Doesn't show up in mine for some reason

**Comment by anuraghazra** [comment]
> I think when `&include_all_commits=true` the year shouldn't be there in the title `Total Commits (2020)`. It should be just `Total Commits`.

Huh??? did you saw the screenshot?

**Comment by anuraghazra** [comment]
> I think when `&include_all_commits=true` the year shouldn't be there in the title `Total Commits (2020)`. It should be just `Total Commits`.

Oh weird, maybe i uploaded the wrong screenshot. my bad

**Comment by anuraghazra** [comment]
Live demo

include_all_commits=false


include_all_commits=true

**Comment by masterking32** [comment]
Hey @anuraghazra , thanks, Can we have both of them? like this
Total commits: XXX
2020 Commits: XXX

**Comment by anuraghazra** [comment]
> Hey @anuraghazra , thanks, Can we have both of them? like this
> Total commits: XXX
> 2020 Commits: XXX

Good idea, but i'm not sure i would do that, it seems kinda redundant.

**Comment by bokub** [comment]
Just to be sure about this code:

https://github.com/anuraghazra/github-readme-stats/blob/ff292f2c0b740a4cb4aa61412049d3e46fc4c923/src/fetchStats.js#L121-L126

I though `experimental_totalCommits` already contained all the commits, but you're adding the `totalCommitContributions` and the `restrictedContributionsCount` from the GraphQL API.

Aren't you counting the same commits 2 times ?

**Comment by anuraghazra** [comment]
> Just to be sure about this code:
> 
> https://github.com/anuraghazra/github-readme-stats/blob/ff292f2c0b740a4cb4aa61412049d3e46fc4c923/src/fetchStats.js#L121-L126
> 
> I though `experimental_totalCommits` already contained all the commits, but you're adding the `totalCommitContributions` and the `restrictedContributionsCount` from the GraphQL API.
> 
> Aren't you counting the same commits 2 times ?

#298 feel free to send a PR

**Comment by bokub** [comment]
Sure! I will try to send a PR this weekend if I find some time

**Pull request merged**
