### PR TITLE
add rose theme

### PR DESCRIPTION
**Pull request by Meezzi**

### CODE REVIEW

**Comment by Zo-Bro-23** [comment]
I like this, but is it perhaps too close to `swift`, `moltack`, and `graywhite`? @rickstaa what do you think? Also @Meezzi please don't keep closing your PRs. It complicates things for us maintainers, and it doesn't really help anyone. We will consider your PR and let you know if we plan to merge, but this will take some time. Thanks for understanding!

**Comment by rickstaa** [comment]
> swift

It is indeed close to `moltack`. I, however, think that because of the `rose` background, it is distinct enough. So feel free to merge it. I mostly merge theme PRs with multiple 👍🏻or card themes based on popular Vscode themes like `onedark`, `monokai`, `cobalt` ect.

**Review by Zo-Bro-23 — APPROVED** [review]
Looks good to me :)

**Comment by Meezzi** [comment]
> 
> 
> Merged 🎉

Thank you !!!  :)

**Pull request merged**
