### PR TITLE
Added new theme called "Sakura"

### PR DESCRIPTION
**Pull request by szyven**
sakura

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title-color: <code>#ed9de</code>
      
icon-color: <code>#ff66e</code>
      
text-color: <code>#ffdbf9</code>
      
bg-color: <code>#2b2029</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ed9de&icon_color=ff66e&text_color=ffdbf9&bg_color=2b2029&show_icons=true)

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title-color: <code>#ed9de0</code>
      
icon-color: <code>#ff66e6</code>
      
text-color: <code>#ffdbf9</code>
      
bg-color: <code>#2b2029</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ed9de0&icon_color=ff66e6&text_color=ffdbf9&bg_color=2b2029&show_icons=true)

**Comment by JustIzumi** [comment]
Commenting to keep the issue alive

**Comment by szyven** [comment]
This pull req. has been inactive for way too long I'm closing it

**Pull request closed without merging**
