### PR TITLE
Added theme: nord-light-aurora

### PR DESCRIPTION
**Pull request by anirbanbasu**
I added a new light theme based on the Nord theme colour palettes: https://www.nordtheme.com/docs/colors-and-palettes. For my Github profile, it looks like this:

[My GitHub statistics](https://github.com/anuraghazra/github-readme-stats)

### CODE REVIEW

**Comment by anirbanbasu** [comment]
I have also deployed it on my own Vercel account. Here's a preview using `theme=nord-light-aurora` on my own deployment.

[My GitHub statistics](https://github.com/anirbanbasu/github-readme-stats)

**Comment by rickstaa** [comment]
JSON can not contain comments. Please fix it and ask me to reopen if you still want to merge this PR.

**Comment by anirbanbasu** [comment]
@rickstaa I have deleted the comment from the JSON file. Please check, re-open and reconsider the PR. Thanks.

**Comment by rickstaa** [comment]
@anirbanbasu Looks that now the theme check action can run. The theme, however, is invalid. Please fix the points in https://github.com/anuraghazra/github-readme-stats/pull/1997#issuecomment-1275690503.

**Comment by anirbanbasu** [comment]
@rickstaa thanks for re-opening the PR. Are the warnings about AA contrast ratio just warnings (in https://github.com/anuraghazra/github-readme-stats/pull/1997#issuecomment-1275690503)? I am using the Nord theme colours (https://www.nordtheme.com/docs/colors-and-palettes) -- I cannot guarantee that their colour palette passes the AA contrast ratio checks. I do not want to change the colours by myself because then I will be deviating from the Nord theme.

**Comment by rickstaa** [comment]
> @rickstaa, thanks for re-opening the PR. Are the warnings about AA contrast ratio just warnings (in [#1997 (comment)](https://github.com/anuraghazra/github-readme-stats/pull/1997#issuecomment-1275690503))? I am using the Nord theme colours (https://www.nordtheme.com/docs/colors-and-palettes) -- I cannot guarantee that their colour palette passes the AA contrast ratio checks. I do not want to change the colours by myself because I will be deviating from the Nord theme.

They are warning because we are currently not merging themes for which the text is hard to read. Your theme looks dimmed, but that is the whole point of the Nord theme I read. 😅 You can still use this theme through the following syntax.

```md
https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=d08770&text_color=5e81ac&icon_color=a3be8c&bg_color=ffffff&border_color=b48ead&show_icons=true
```

Or create a separate repo to give users the right theme syntax (see https://github.com/catppuccin/github-readme-stats).

**Comment by anirbanbasu** [comment]
@rickstaa yes, the whole point of the Nord theme is to have a dimmed colour palette :-) Nonetheless, I have updated the colours a bit, still not deviating from the Nord palette. Now, `icon_color` still does not pass the AA contrast checks fully but passes the graphical objects check. Will this be acceptable?

Indeed, I could change the colours in the way you have mentioned. As the Nord theme is available as a theme in various UIs, I thought of adding it to this project. I do understand that the problem is with the `nord_light_aurora`, not the `nord` theme that I added, which is a dark theme. Thus, I could get rid of the `nord_light_aurora` altogether.

**Comment by rickstaa** [comment]
> @rickstaa yes, the whole point of the Nord theme is to have a dimmed colour palette :-) Nonetheless, I have updated the colours a bit, still not deviating from the Nord palette. Now, `icon_color` still does not pass the AA contrast checks fully but passes the graphical objects check. Will this be acceptable?
> 
> Indeed, I could change the colours in the way you have mentioned. As the Nord theme is available as a theme in various UIs, I thought of adding it to this project. I do understand that the problem is with the `nord_light_aurora`, not the `nord` theme that I added, which is a dark theme. Thus, I could get rid of the `nord_light_aurora` altogether.

These guidelines were set by @anuraghazra to keep the theme database from bloating. I will therefore adhere to them. It is good to go if the `nord` theme passes our tests. If you want to make all themes available in their original colours, I would advise you to use the approach taken by catppuccin (see https://github.com/catppuccin/github-readme-stats).

**Comment by anirbanbasu** [comment]
@rickstaa, I have removed the `nord_light_aurora` theme altogether. I will check the https://github.com/catppuccin/github-readme-stats -- thanks!

**Comment by anirbanbasu** [comment]
Not sure why the invalid label is still there while the theme label is gone.

**Comment by rickstaa** [comment]
@anirbanbasu That is because now the PR has no theme-related changes, and thus the theme check action does not run. You should add the Nord theme if you want the invalid label to be gone. I can also just remove this label and close the PR if you're not planning to add the `nord` theme.

**Comment by rickstaa** [comment]
O the Nord theme was already accepted. I will remove the label and close the PR.

**Comment by anirbanbasu** [comment]
> O the Nord theme was already accepted. I will remove the label and close the PR.

Okay, understood. Thank you!

**Pull request closed without merging**
