### PR TITLE
refactor: Simplifying rank selection

### PR DESCRIPTION
**Pull request by marcospb19**
Fixing level selection over complicated `if` condition blocks that split into multiple lines using a simpler code with `else if`.

### CODE REVIEW

**Comment by marcospb19** [comment]
bumping it

**Review by ensia96 — COMMENTED** [review]
```
  let level =
    normalizedScore < RANK_S_VALUE
      ? "S+"
      : normalizedScore < RANK_DOUBLE_A_VALUE
      ? "S"
      : normalizedScore < RANK_A2_VALUE
      ? "A++"
      : normalizedScore < RANK_A3_VALUE
      ? "A+"
      : "B+";
```

I think the code change you suggested can be organized in this way as well. : )

Instead of solving conditional processing with behavioral syntax,
you can make it to be processed by the variable assignment process itself.

**Comment by marcospb19** [comment]
I personally think that
```js
let level =
  normalizedScore < RANK_S_VALUE
    ? "S+"
    : normalizedScore < RANK_DOUBLE_A_VALUE
    ? "S"
    : normalizedScore < RANK_A2_VALUE
    ? "A++"
    : normalizedScore < RANK_A3_VALUE
    ? "A+"
    : "B+";
```

Is very unreadable comparing to:
```js
if (normalizedScore < RANK_S_VALUE) {
  level = "S+";
} else if (normalizedScore < RANK_DOUBLE_A_VALUE) {
  level = "S";
} else if (normalizedScore < RANK_A2_VALUE) {
  level = "A++";
} else if (normalizedScore < RANK_A3_VALUE) {
  level = "A+";
} else if (normalizedScore < RANK_B_VALUE) {
  level = "B+";
}
```

**Comment by marcospb19** [comment]
Force pushed with new formattation.

**Pull request closed without merging**
