### PR TITLE
added forty theme

### PR DESCRIPTION
**Pull request by Ritwikrajsingh**

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title_color: <code>#8d82c4</code> | icon_color: <code>#ec8d81</code> | text_color: <code>#9bf1ff</code> | bg_color: <code>#2a2f4a</code>
      
      
Link: https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=8d82c4&icon_color=ec8d81&text_color=9bf1ff&bg_color=2a2f4a&show_icons=true

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=8d82c4&icon_color=ec8d81&text_color=9bf1ff&bg_color=2a2f4a&show_icons=true)
      
      
  
> Hi thanks for the theme contribution, please read our theme contribution guidelines

  
> We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 
  
> Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title_color: <code>#8d82c4</code> | icon_color: <code>#ec8d81</code> | text_color: <code>#9bf1ff</code> | bg_color: <code>#2a2f4a</code>
      
      
Link: https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=8d82c4&icon_color=ec8d81&text_color=9bf1ff&bg_color=2a2f4a&show_icons=true

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=8d82c4&icon_color=ec8d81&text_color=9bf1ff&bg_color=2a2f4a&show_icons=true)
      
      
  
> Hi thanks for the theme contribution, please read our theme contribution guidelines

  
> We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 
  
> Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title_color: <code>#ec8d81</code> | icon_color: <code>#f1e05a</code> | text_color: <code>#9bf1ff</code> | bg_color: <code>#2a2f4a</code>
      
      
Link: https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ec8d81&icon_color=f1e05a&text_color=9bf1ff&bg_color=2a2f4a&show_icons=true

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ec8d81&icon_color=f1e05a&text_color=9bf1ff&bg_color=2a2f4a&show_icons=true)
      
      
  
> Hi thanks for the theme contribution, please read our theme contribution guidelines

  
> We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 
  
> Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title_color: <code>#ec8d81</code> | icon_color: <code>#f1e05a</code> | text_color: <code>#9bf1ff</code> | bg_color: <code>#2a2f4a</code>
      
      
Link: https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ec8d81&icon_color=f1e05a&text_color=9bf1ff&bg_color=2a2f4a&show_icons=true

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ec8d81&icon_color=f1e05a&text_color=9bf1ff&bg_color=2a2f4a&show_icons=true)
      
      
  
> Hi thanks for the theme contribution, please read our theme contribution guidelines

  
> We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 
  
> Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: forty

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Forty theme preview
        
        

        
title_color: <code>#ec8d81</code> | icon_color: <code>#f1e05a</code> | text_color: <code>#9bf1ff</code> | bg_color: <code>#2a2f4a</code> | border_color: <code>#8d82c4</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ec8d81&icon_color=f1e05a&text_color=9bf1ff&bg_color=2a2f4a&border_color=8d82c4&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ec8d81&icon_color=f1e05a&text_color=9bf1ff&bg_color=2a2f4a&border_color=8d82c4&show_icons=true)

**Review by rickstaa — APPROVED** [review]

**Review by rickstaa — APPROVED** [review]

**Pull request closed without merging**
