### PR TITLE
Added new theme "purple-pink-mirror" 

### PR DESCRIPTION
**Pull request by lostgirljourney**
- **Theme Name**: "purple-pink-mirror"
- **Preview**: 
image

(_Hope you all will like it._)

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title_color: <code>#C197D2</code> | icon_color: <code>#de265a</code> | text_color: <code>#D3B1C2</code> | bg_color: <code>#211522</code>
      
      
Link: https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=C197D2&icon_color=de265a&text_color=D3B1C2&bg_color=211522&show_icons=true

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=C197D2&icon_color=de265a&text_color=D3B1C2&bg_color=211522&show_icons=true)
      
      
  
> Hi thanks for the theme contribution, please read our theme contribution guidelines

  
> We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 
  
> Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title_color: <code>#C197D2</code> | icon_color: <code>#de265a</code> | text_color: <code>#D3B1C2</code> | bg_color: <code>#211522</code>
      
      
Link: https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=C197D2&icon_color=de265a&text_color=D3B1C2&bg_color=211522&show_icons=true

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=C197D2&icon_color=de265a&text_color=D3B1C2&bg_color=211522&show_icons=true)
      
      
  
> Hi thanks for the theme contribution, please read our theme contribution guidelines

  
> We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 
  
> Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title_color: <code>#C197D2</code> | icon_color: <code>#de265a</code> | text_color: <code>#D3B1C2</code> | bg_color: <code>#211522</code>
      
      
Link: https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=C197D2&icon_color=de265a&text_color=D3B1C2&bg_color=211522&show_icons=true

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=C197D2&icon_color=de265a&text_color=D3B1C2&bg_color=211522&show_icons=true)
      
      
  
> Hi thanks for the theme contribution, please read our theme contribution guidelines

  
> We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 
  
> Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

**Comment by rickstaa** [comment]
You appear to be changing an existing theme. Can you please specify why you want this theme to change?

**Comment by lostgirljourney** [comment]
@rickstaa hi, I opened this PR quite a good time ago, and it was not changing any existing theme. Tho thanks for the update.

**Comment by rickstaa** [comment]
@lostgirljourney Ah, I see. I think it is because the PR and the master diverged too much. 🤔 I tried to rebase your pr onto the main branch, but it looks like your branch is already created. Feel free to reopen and merge the master if you still want to merge this theme.

**Comment by lostgirljourney** [comment]
@rickstaa, can i open a new pr for the same?

**Comment by rickstaa** [comment]
Of course! I, however, can not promise that the theme will be added. We have 50 valid theme PR requests we still haven't looked at (see https://github.com/anuraghazra/github-readme-stats/pulls?q=is%3Aopen+is%3Apr+label%3Athemes+-label%3Ainvalid+). We are therefore currently only merging the ones that receive multiple upvotes, are distinct enough from the themes we already have or are based on very popular Vscode themes.

**Comment by rickstaa** [comment]
You can also just rebase this PR onto the master branch.

**Comment by lostgirljourney** [comment]
I can see some themes like this there so if I get a new piece, then I surely will make PR again. Thanks tho. :)

**Pull request closed without merging**
