### PR TITLE
Add discord theme

### PR DESCRIPTION
**Pull request by ItzMiracleOwO**
Title color: White #FFFFFF
Icon color: Nitro purple #FF73FE
Text color: Discord Blue #7289DA
Background color: Discord chat #36393F

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title_color: <code>#FFFFFF</code> | icon_color: <code>#FF73FE</code> | text_color: <code>#7289DA</code> | bg_color: <code>#36393F</code>
      
      
Link: https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FFFFFF&icon_color=FF73FE&text_color=7289DA&bg_color=36393F&show_icons=true

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FFFFFF&icon_color=FF73FE&text_color=7289DA&bg_color=36393F&show_icons=true)
      
      
  
> Hi thanks for the theme contribution, please read our theme contribution guidelines

  
> We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 
  
> Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:x: Theme PR does not adhere to our guidelines.
      
## Test results
      
- :x: discord

      
**Result:** :x: Some themes are invalid.


  
Unfortunately, your theme PR does not adhere to our [theme guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution). Please fix the issues below, and we will review your  
 PR again. This pull request will **automatically close in 15 days** if no changes are made. After this time, you must re-open the PR for it to be reviewed.

      
      
## Details
      
        
### Discord theme preview
        
        
- :warning: `text_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=7289DA&bcolor=36393F).


        
title_color: <code>#FFFFFF</code> | icon_color: <code>#FF73FE</code> | text_color: <code>#7289DA</code> | bg_color: <code>#36393F</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FFFFFF&icon_color=FF73FE&text_color=7289DA&bg_color=36393F&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FFFFFF&icon_color=FF73FE&text_color=7289DA&bg_color=36393F&show_icons=true)

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1239#issuecomment-1264658806) comment above for more information.

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1239#issuecomment-1264658806) comment above for more information.

**Comment by rickstaa** [comment]
This PR has been automatically closed due to inactivity. Please feel free to reopen it if you need to continue working on it.	
Thank you for your contributions.

**Pull request closed without merging**
