### PR TITLE
add blue_tech theme

### PR DESCRIPTION
**Pull request by GFrancV**

### CODE REVIEW

**Comment by GFrancV** [comment]
Add new color with awesome colors

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: blue_tech

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Blue_tech theme preview
        
        

        
title_color: <code>#01ffff</code> | icon_color: <code>#01ffff</code> | text_color: <code>#fefefe</code> | bg_color: <code>#243642</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=01ffff&icon_color=01ffff&text_color=fefefe&bg_color=243642&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=01ffff&icon_color=01ffff&text_color=fefefe&bg_color=243642&show_icons=true)

**Review by rickstaa — APPROVED** [review]

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: blue_tech

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Blue_tech theme preview
        
        

        
title_color: <code>#01ffff</code> | icon_color: <code>#01ffff</code> | text_color: <code>#fefefe</code> | bg_color: <code>#243642</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=01ffff&icon_color=01ffff&text_color=fefefe&bg_color=243642&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=01ffff&icon_color=01ffff&text_color=fefefe&bg_color=243642&show_icons=true)

**Review by rickstaa — APPROVED** [review]

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: blue_tech

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Blue_tech theme preview
        
        

        
title_color: <code>#01ffff</code> | icon_color: <code>#01ffff</code> | text_color: <code>#fefefe</code> | bg_color: <code>#243642</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=01ffff&icon_color=01ffff&text_color=fefefe&bg_color=243642&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=01ffff&icon_color=01ffff&text_color=fefefe&bg_color=243642&show_icons=true)

**Review by rickstaa — APPROVED** [review]

**Review by rickstaa — APPROVED** [review]

**Pull request closed without merging**
