### PR TITLE
Added green color for all components except background

### PR DESCRIPTION
**Pull request by meSajied**
I added this theme, for people who love the simple design.

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title-color: <code>#008000</code>
      
icon-color: <code>#008000</code>
      
text-color: <code>#008000</code>
      
bg-color: <code>#ffffff</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=008000&icon_color=008000&text_color=008000&bg_color=ffffff&show_icons=true)

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title-color: <code>#000000</code>
      
icon-color: <code>#008000</code>
      
text-color: <code>#008000</code>
      
bg-color: <code>#ffffff</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=000000&icon_color=008000&text_color=008000&bg_color=ffffff&show_icons=true)

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title-color: <code>#006400</code>
      
icon-color: <code>#008000</code>
      
text-color: <code>#008000</code>
      
bg-color: <code>#ffffff</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=006400&icon_color=008000&text_color=008000&bg_color=ffffff&show_icons=true)

**Comment by meSajied** [comment]
I will look good when added without title..

**Comment by anuraghazra** [comment]
Hi @meSajied thanks for opening the PR, but I don't think we need to add these to our themes collection since this theme is very simplistic and can be easily just be done with custom options.

```md
![](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=006400&icon_color=008000&text_color=008000&bg_color=ffffff&show_icons=true)
```

Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 

Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

**Pull request closed without merging**
