### PR TITLE
Added a Cobalt2 theme!

### PR DESCRIPTION
**Pull request by vidhanio**
Hey there! Great project, just wanted to add one of my favourite themes to it.

[Vidhan's GitHub stats](https://github.com/anuraghazra/github-readme-stats)

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title_color: <code>#FFC600</code> | icon_color: <code>#9EFFFF</code> | text_color: <code>#A5FF90</code> | bg_color: <code>#193549</code>
      
      
Link: https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FFC600&icon_color=9EFFFF&text_color=A5FF90&bg_color=193549&show_icons=true

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FFC600&icon_color=9EFFFF&text_color=A5FF90&bg_color=193549&show_icons=true)
      
      
  
> Hi thanks for the theme contribution, please read our theme contribution guidelines

  
> We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 
  
> Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:x: Theme PR does not adhere to our guidelines.
      
## Test results
      
- :x: cobalt2

      
**Result:** :x: Some themes are invalid.


  
Unfortunately, your theme PR does not adhere to our [theme guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution). Please fix the issues below, and we will review your  
 PR again. This pull request will **automatically close in 15 days** if no changes are made. After this time, you must re-open the PR for it to be reviewed.

      
      
## Details
      
        
### Cobalt2 theme preview
        
        
- :warning: Theme name already taken.
- :warning: Theme name isn't in snake_case.


        
title_color: <code>#FFC600</code> | icon_color: <code>#9EFFFF</code> | text_color: <code>#A5FF90</code> | bg_color: <code>#193549</code> | border_color: <code>#717D88</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FFC600&icon_color=9EFFFF&text_color=A5FF90&bg_color=193549&border_color=717D88&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FFC600&icon_color=9EFFFF&text_color=A5FF90&bg_color=193549&border_color=717D88&show_icons=true)

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1231#issuecomment-1264658833) comment above for more information.

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1231#issuecomment-1264658833) comment above for more information.

**Pull request closed without merging**
