### PR TITLE
Update luotianyi themes

### PR DESCRIPTION
**Pull request by SakuraPuare**
Hope you like it :]

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title-color: <code>#66ccff</code>
      
icon-color: <code>#ea549f</code>
      
text-color: <code>#333</code>
      
bg-color: <code>#0fffff</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=66ccff&icon_color=ea549f&text_color=333&bg_color=0fffff&show_icons=true)

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title-color: <code>#66ccff</code>
      
icon-color: <code>#ea549f</code>
      
text-color: <code>#333</code>
      
bg-color: <code>#ffffff</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=66ccff&icon_color=ea549f&text_color=333&bg_color=ffffff&show_icons=true)

**Comment by SakuraPuare** [comment]
I found that bg_color was wrong

**Comment by SakuraPuare** [comment]
e

**Pull request closed without merging**
