### PR TITLE
chore(themes): add eclipse configuration

### PR DESCRIPTION
**Pull request by ming-tsai**
**Live demo**
[My github stats](https://github.com/anuraghazra/github-readme-stats#customization)

### CODE REVIEW

**Comment by anuraghazra** [comment]
@ming-tsai thanks for the theme contribution, can you please provide live demo or screenshot

**Comment by ming-tsai** [comment]
> @ming-tsai thanks for the theme contribution, can you please provide live demo or screenshot

PR description updated, check it out

**Comment by anuraghazra** [comment]
I'm not really sure about the color combination, feels like just the icon color is changed.

**Comment by ming-tsai** [comment]
> I'm not really sure about the color combination, feels like just the icon color is changed.

The letter color is changed to almost white but no smoke white and the background color is changed

**Pull request closed without merging**
