### PR TITLE
Add darcula theme.

### PR DESCRIPTION
**Pull request by WIttyJudge**
Hello, @ahmadawais 
```darcula``` is one of the my favorite theme, so I want to add it.

Screenshot_2020-08-01_18-36-37

Inspiration:
https://plugins.jetbrains.com/plugin/12692-darcula-darker-theme
https://marketplace.visualstudio.com/items?itemName=rokoroku.vscode-theme-darcula

Thank you!

### CODE REVIEW

**Comment by ahmadawais** [comment]
@WIttyJudge nothing to do with me though :) Not my repo.

**Comment by WIttyJudge** [comment]
> @WIttyJudge nothing to do with me though :) Not my repo. 

Oops, I'm sorry😁

**Comment by anuraghazra** [comment]
haha @WIttyJudge hello! thanks for the theme contribution. 

Huh looks like we already have a theme called dracula

**Comment by WIttyJudge** [comment]
> haha @WIttyJudge hello! thanks for the theme contribution. 
> 
> Huh looks like we already have a theme called dracula
> 
> 

I want to add theme called darcula, not dracula. I've seen you already have dracula, but it is not the same theme.

**Comment by anuraghazra** [comment]
OHHHHH It's darcula. haha

**Comment by anuraghazra** [comment]
@WIttyJudge Don't update the theme readme, i've script setup to automatically generate that

**Comment by WIttyJudge** [comment]
@anuraghazra I've resolved my conflicts and and delete code I wrote in readme.

**Comment by WIttyJudge** [comment]
okay, now it's passed :sweat_smile:

**Comment by WIttyJudge** [comment]
@ahmadawais what do you think?

**Comment by ahmadawais** [comment]
> @ahmadawais what do you think?

Not my theme. Not my repo. I don't use that theme. Neither this widget. I think you are mis tagging me.

**Comment by anuraghazra** [comment]
@WIttyJudge sorry for late merge.

LGTM! thanks for the contribution.

**Pull request merged**
