### PR TITLE
refactor: object shorthand

### PR DESCRIPTION
**Pull request by mxdvl**
For your consideration, a [shorthand property in object initialisation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#property_definitions).

### CODE REVIEW

**Comment by mxdvl** [comment]
No one's asked for this 😆

**Review by rickstaa — APPROVED** [review]

**Comment by rickstaa** [comment]
> No one's asked for this laughing

No, it's a good code improvement. Thanks for your contribution. Merged into master 🚀.

**Comment by mxdvl** [comment]
> > No one's asked for this laughing
> 
> No, it's a good code improvement. Thanks for your contribution. Merged into master 🚀.

Glad you like it – just chasing those sweet sweet stats 😜

You probably want to enable the [`object-shorthand` ESLint rule](https://eslint.org/docs/latest/rules/object-shorthand) if you want consistency across your codebase!

**Comment by rickstaa** [comment]
> > > No one's asked for this laughing
> > 
> > 
> > No, it's a good code improvement. Thanks for your contribution. Merged into master rocket.
> 
> Glad you like it – just chasing those sweet sweet stats stuck_out_tongue_winking_eye
> 
> You probably want to enable the [`object-shorthand` ESLint rule](https://eslint.org/docs/latest/rules/object-shorthand) if you want consistency across your codebase!

That sounds great to me. I, however, checked, and [Prettier](https://github.com/prettier/prettier/issues/12864) currently doesn't support this rule and Eslint still needs to be enabled for this repository. I, however, think that we can safely add eslint next to prettier if we want. @qwerty541 what do you think?

**Comment by qwerty541** [comment]
> > > > No one's asked for this laughing
> > > 
> > > 
> > > No, it's a good code improvement. Thanks for your contribution. Merged into master rocket.
> > 
> > 
> > Glad you like it – just chasing those sweet sweet stats stuck_out_tongue_winking_eye
> > You probably want to enable the [`object-shorthand` ESLint rule](https://eslint.org/docs/latest/rules/object-shorthand) if you want consistency across your codebase!
> 
> That sounds great to me. I, however, checked, and [Prettier](https://github.com/prettier/prettier/issues/12864) currently doesn't support this rule, and Eslint still needs to be enabled for this repository. I, however, think that we can safely add Eslint next to prettier if we want (see https://prettier.io/docs/en/integrating-with-linters.html). @qwerty541, what do you think?

Eslint integration is great idea. I use it for all my presonal and commercial ts/js repositories. I have opened draft pull request #2885 related to it.

**Pull request merged**
