### PR TITLE
Theme restructure

### PR DESCRIPTION
**Pull request by Zo-Bro-23**
Some themes have names with hyphens, and others have names with underscores. This is slightly confusing, so I thought we'd have names with both hyphens and underscores moving forward. @rickstaa what do you think?

### CODE REVIEW

**Comment by rickstaa** [comment]
@Zo-Bro-23 I'm okay with this if we make it back-compatible, meaning that we parse themes so that regardless of whether people use a hyphen or underscore, the card works 👍🏻.

**Comment by Zo-Bro-23** [comment]
> 

That's what I was trying to do with this PR. Parsing cards with hyphens and underscores works, but as a temporary solution I'm just creating duplicate theme names with hyphens and underscores. What do you think of that? Is it just better to take the time to modify the theme parsing instead of doing this?

**Comment by Zo-Bro-23** [comment]
#2558 is another way to do this. @rickstaa let me know which one you prefer.

**Comment by rickstaa** [comment]
> #2558 is another way to do this. @rickstaa let me know which one you prefer.

I would love the combination. Making it consistent and back compatible 😄.

**Review by rickstaa — CHANGES_REQUESTED** [review]
End of input while parsing an object (missing '}') at line 1,153 >>> "default-repocard": ...

**Review by rickstaa — CHANGES_REQUESTED** [review]
`End of input while parsing an object (missing '}') at line 1,153 >>> "default-repocard": ...`

**Review by rickstaa — CHANGES_REQUESTED** [review]
Something went wrong: `Theme JSON file could not be parsed: Error: End of input while parsing an object (missing '}') at line 1,153 >>> "default-repocard": ...`

**Review by rickstaa — CHANGES_REQUESTED** [review]
**Something went wrong in the theme preview action:** `Theme JSON file could not be parsed: End of input while parsing an object (missing '}') at line 1,153 >>> "default-repocard": ...`

**Comment by Zo-Bro-23** [comment]
@rickstaa the JSON seems to be valid. What do you think?

PS: The error feature is awesome. Thanks for adding it :)

**Comment by rickstaa** [comment]
> @rickstaa the JSON seems to be valid. What do you think?
> 
> PS: The error feature is awesome. Thanks for adding it :)

Mm I'm not sure maybe 

> @rickstaa the JSON seems to be valid. What do you think?
> 
> PS: The error feature is awesome. Thanks for adding it :)

Probably my regex not being inclusive enough you changed a lot of things:

https://github.com/anuraghazra/github-readme-stats/blob/1e61f9f3fe955fa25ab27dd1e06ddbfd788f4fda/scripts/preview-theme.js#L298-L304

**Comment by Zo-Bro-23** [comment]
> > @rickstaa the JSON seems to be valid. What do you think?
> > PS: The error feature is awesome. Thanks for adding it :)
> 
> Mm I'm not sure maybe
> 
> > @rickstaa the JSON seems to be valid. What do you think?
> > PS: The error feature is awesome. Thanks for adding it :)
> 
> Probably my regex not being inclusive enough you changed a lot of things:
> 
> https://github.com/anuraghazra/github-readme-stats/blob/1e61f9f3fe955fa25ab27dd1e06ddbfd788f4fda/scripts/preview-theme.js#L298-L304

Maybe... Can you try making it a bit more lenient?

**Comment by rickstaa** [comment]
> > > @rickstaa the JSON seems to be valid. What do you think?
> > > PS: The error feature is awesome. Thanks for adding it :)
> > 
> > 
> > Mm I'm not sure maybe
> > > @rickstaa the JSON seems to be valid. What do you think?
> > > PS: The error feature is awesome. Thanks for adding it :)
> > 
> > 
> > Probably my regex not being inclusive enough you changed a lot of things:
> > https://github.com/anuraghazra/github-readme-stats/blob/1e61f9f3fe955fa25ab27dd1e06ddbfd788f4fda/scripts/preview-theme.js#L298-L304
> 
> Maybe... Can you try making it a bit more lenient?

@Zo-Bro-23 I currently sadly do not have much time to improve it myself. Feel free to suggest a PR for me to review 👍🏻.

**Comment by Zo-Bro-23** [comment]
@rickstaa what commit broke the action? Maybe we should revert it to its previous version.

**Comment by rickstaa** [comment]
> @rickstaa what commit broke the action? Maybe we should revert it to its previous version.

No commit broke the action. It is just not equipped yet to handle the mount of changes you made 😅. I will take a quick look.

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:x: Theme PR does not adhere to our guidelines.
      
## Test results
      
- :x: default-repocard
- :x: gruvbox-light
- :heavy_check_mark: vue_dark
- :x: shades_of_purple
- :heavy_check_mark: blue_green
- :heavy_check_mark: great_gatsby
- :x: solarized_dark
- :x: solarized_light
- :heavy_check_mark: chartreuse_dark
- :heavy_check_mark: material_palenight
- :heavy_check_mark: vision_friendly_dark
- :heavy_check_mark: ayu_mirage
- :x: midnight_purple
- :x: flag_india
- :x: kacho-ga
- :x: ocean-dark
- :x: city-lights
- :x: github-dark
- :x: discord-old-blurple
- :x: aura-dark
- :x: noctis-minimus
- :x: rose-pine
- :x: date-night
- :x: one-dark-pro
- :x: holi-theme

      
**Result:** :x: Some themes are invalid.


  
Unfortunately, your theme PR contains an error or does not adhere to our [theme guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution). Please fix the issues below, and we will review your  
 PR again. This pull request will **automatically close in 20 days** if no changes are made. After this time, you must re-open the PR for it to be reviewed.

      
      
## Details
      
        
### Default-repocard theme preview
        
        
- :warning: Theme name isn't in snake_case.
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=2f80ed&bcolor=fffefe).


        
title_color: <code>#2f80ed</code> | icon_color: <code>#586069</code> | text_color: <code>#434d58</code> | bg_color: <code>#fffefe</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=2f80ed&icon_color=586069&text_color=434d58&bg_color=fffefe&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=2f80ed&icon_color=586069&text_color=434d58&bg_color=fffefe&show_icons=true)
      
        
### Gruvbox-light theme preview
        
        
- :warning: Theme name isn't in snake_case.
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=b57614&bcolor=fbf1c7).
- :warning: `text_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=427b58&bcolor=fbf1c7).


        
title_color: <code>#b57614</code> | icon_color: <code>#af3a03</code> | text_color: <code>#427b58</code> | bg_color: <code>#fbf1c7</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=b57614&icon_color=af3a03&text_color=427b58&bg_color=fbf1c7&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=b57614&icon_color=af3a03&text_color=427b58&bg_color=fbf1c7&show_icons=true)
      
        
### Vue_dark theme preview
        
        

        
title_color: <code>#41b883</code> | icon_color: <code>#41b883</code> | text_color: <code>#fffefe</code> | bg_color: <code>#273849</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=41b883&icon_color=41b883&text_color=fffefe&bg_color=273849&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=41b883&icon_color=41b883&text_color=fffefe&bg_color=273849&show_icons=true)
      
        
### Shades_of_purple theme preview
        
        
- :warning: `icon_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=b362ff&bcolor=2d2b55).


        
title_color: <code>#fad000</code> | icon_color: <code>#b362ff</code> | text_color: <code>#a599e9</code> | bg_color: <code>#2d2b55</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=fad000&icon_color=b362ff&text_color=a599e9&bg_color=2d2b55&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=fad000&icon_color=b362ff&text_color=a599e9&bg_color=2d2b55&show_icons=true)
      
        
### Blue_green theme preview
        
        

        
title_color: <code>#2f97c1</code> | icon_color: <code>#f5b700</code> | text_color: <code>#0cf574</code> | bg_color: <code>#040f0f</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=2f97c1&icon_color=f5b700&text_color=0cf574&bg_color=040f0f&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=2f97c1&icon_color=f5b700&text_color=0cf574&bg_color=040f0f&show_icons=true)
      
        
### Great_gatsby theme preview
        
        

        
title_color: <code>#ffa726</code> | icon_color: <code>#ffb74d</code> | text_color: <code>#ffd95b</code> | bg_color: <code>#000000</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ffa726&icon_color=ffb74d&text_color=ffd95b&bg_color=000000&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ffa726&icon_color=ffb74d&text_color=ffd95b&bg_color=000000&show_icons=true)
      
        
### Solarized_dark theme preview
        
        
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=268bd2&bcolor=002b36).


        
title_color: <code>#268bd2</code> | icon_color: <code>#b58900</code> | text_color: <code>#859900</code> | bg_color: <code>#002b36</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=268bd2&icon_color=b58900&text_color=859900&bg_color=002b36&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=268bd2&icon_color=b58900&text_color=859900&bg_color=002b36&show_icons=true)
      
        
### Solarized_light theme preview
        
        
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=268bd2&bcolor=fdf6e3).
- :warning: `icon_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=b58900&bcolor=fdf6e3).
- :warning: `text_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=859900&bcolor=fdf6e3).


        
title_color: <code>#268bd2</code> | icon_color: <code>#b58900</code> | text_color: <code>#859900</code> | bg_color: <code>#fdf6e3</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=268bd2&icon_color=b58900&text_color=859900&bg_color=fdf6e3&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=268bd2&icon_color=b58900&text_color=859900&bg_color=fdf6e3&show_icons=true)
      
        
### Chartreuse_dark theme preview
        
        

        
title_color: <code>#7fff00</code> | icon_color: <code>#00AEFF</code> | text_color: <code>#fff</code> | bg_color: <code>#000</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=7fff00&icon_color=00AEFF&text_color=fff&bg_color=000&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=7fff00&icon_color=00AEFF&text_color=fff&bg_color=000&show_icons=true)
      
        
### Material_palenight theme preview
        
        

        
title_color: <code>#c792ea</code> | icon_color: <code>#89ddff</code> | text_color: <code>#a6accd</code> | bg_color: <code>#292d3e</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=c792ea&icon_color=89ddff&text_color=a6accd&bg_color=292d3e&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=c792ea&icon_color=89ddff&text_color=a6accd&bg_color=292d3e&show_icons=true)
      
        
### Vision_friendly_dark theme preview
        
        

        
title_color: <code>#ffb000</code> | icon_color: <code>#785ef0</code> | text_color: <code>#ffffff</code> | bg_color: <code>#000000</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ffb000&icon_color=785ef0&text_color=ffffff&bg_color=000000&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ffb000&icon_color=785ef0&text_color=ffffff&bg_color=000000&show_icons=true)
      
        
### Ayu_mirage theme preview
        
        

        
title_color: <code>#f4cd7c</code> | icon_color: <code>#73d0ff</code> | text_color: <code>#c7c8c2</code> | bg_color: <code>#1f2430</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=f4cd7c&icon_color=73d0ff&text_color=c7c8c2&bg_color=1f2430&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=f4cd7c&icon_color=73d0ff&text_color=c7c8c2&bg_color=1f2430&show_icons=true)
      
        
### Midnight_purple theme preview
        
        
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=9745f5&bcolor=000000).


        
title_color: <code>#9745f5</code> | icon_color: <code>#9f4bff</code> | text_color: <code>#ffffff</code> | bg_color: <code>#000000</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9745f5&icon_color=9f4bff&text_color=ffffff&bg_color=000000&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9745f5&icon_color=9f4bff&text_color=ffffff&bg_color=000000&show_icons=true)
      
        
### Flag_india theme preview
        
        
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=ff8f1c&bcolor=ffffff).
- :warning: `text_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=509E2F&bcolor=ffffff).


        
title_color: <code>#ff8f1c</code> | icon_color: <code>#250E62</code> | text_color: <code>#509E2F</code> | bg_color: <code>#ffffff</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ff8f1c&icon_color=250E62&text_color=509E2F&bg_color=ffffff&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ff8f1c&icon_color=250E62&text_color=509E2F&bg_color=ffffff&show_icons=true)
      
        
### Kacho-ga theme preview
        
        
- :warning: Theme name isn't in snake_case.
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=bf4a3f&bcolor=402b23).
- :warning: `icon_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=a64833&bcolor=402b23).


        
title_color: <code>#bf4a3f</code> | icon_color: <code>#a64833</code> | text_color: <code>#d9c8a9</code> | bg_color: <code>#402b23</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=bf4a3f&icon_color=a64833&text_color=d9c8a9&bg_color=402b23&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=bf4a3f&icon_color=a64833&text_color=d9c8a9&bg_color=402b23&show_icons=true)
      
        
### Ocean-dark theme preview
        
        
- :warning: Theme name isn't in snake_case.
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=8957B2&bcolor=151A28).


        
title_color: <code>#8957B2</code> | icon_color: <code>#FFFFFF</code> | text_color: <code>#92D534</code> | bg_color: <code>#151A28</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=8957B2&icon_color=FFFFFF&text_color=92D534&bg_color=151A28&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=8957B2&icon_color=FFFFFF&text_color=92D534&bg_color=151A28&show_icons=true)
      
        
### City-lights theme preview
        
        
- :warning: Theme name isn't in snake_case.
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=5D8CB3&bcolor=1D252C).
- :warning: `text_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=718CA1&bcolor=1D252C).


        
title_color: <code>#5D8CB3</code> | icon_color: <code>#4798FF</code> | text_color: <code>#718CA1</code> | bg_color: <code>#1D252C</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=5D8CB3&icon_color=4798FF&text_color=718CA1&bg_color=1D252C&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=5D8CB3&icon_color=4798FF&text_color=718CA1&bg_color=1D252C&show_icons=true)
      
        
### Github-dark theme preview
        
        
- :warning: Theme name isn't in snake_case.
- :warning: `icon_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=1F6FEB&bcolor=0D1117).


        
title_color: <code>#58A6FF</code> | icon_color: <code>#1F6FEB</code> | text_color: <code>#C3D1D9</code> | bg_color: <code>#0D1117</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=58A6FF&icon_color=1F6FEB&text_color=C3D1D9&bg_color=0D1117&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=58A6FF&icon_color=1F6FEB&text_color=C3D1D9&bg_color=0D1117&show_icons=true)
      
        
### Discord-old-blurple theme preview
        
        
- :warning: Theme name isn't in snake_case.
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=7289DA&bcolor=2C2F33).
- :warning: `icon_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=7289DA&bcolor=2C2F33).


        
title_color: <code>#7289DA</code> | icon_color: <code>#7289DA</code> | text_color: <code>#FFFFFF</code> | bg_color: <code>#2C2F33</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=7289DA&icon_color=7289DA&text_color=FFFFFF&bg_color=2C2F33&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=7289DA&icon_color=7289DA&text_color=FFFFFF&bg_color=2C2F33&show_icons=true)
      
        
### Aura-dark theme preview
        
        
- :warning: Theme name isn't in snake_case.


        
title_color: <code>#ff7372</code> | icon_color: <code>#6cffd0</code> | text_color: <code>#dbdbdb</code> | bg_color: <code>#252334</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ff7372&icon_color=6cffd0&text_color=dbdbdb&bg_color=252334&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ff7372&icon_color=6cffd0&text_color=dbdbdb&bg_color=252334&show_icons=true)
      
        
### Noctis-minimus theme preview
        
        
- :warning: Theme name isn't in snake_case.


        
title_color: <code>#d3b692</code> | icon_color: <code>#72b7c0</code> | text_color: <code>#c5cdd3</code> | bg_color: <code>#1b2932</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=d3b692&icon_color=72b7c0&text_color=c5cdd3&bg_color=1b2932&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=d3b692&icon_color=72b7c0&text_color=c5cdd3&bg_color=1b2932&show_icons=true)
      
        
### Rose-pine theme preview
        
        
- :warning: Theme name isn't in snake_case.


        
title_color: <code>#9ccfd8</code> | icon_color: <code>#ebbcba</code> | text_color: <code>#e0def4</code> | bg_color: <code>#191724</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)
      
        
### Date-night theme preview
        
        
- :warning: Theme name isn't in snake_case.


        
title_color: <code>#DA7885</code> | icon_color: <code>#BB8470</code> | text_color: <code>#E1B2A2</code> | bg_color: <code>#170F0C</code> | border_color: <code>#170F0C</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=DA7885&text_color=E1B2A2&icon_color=BB8470&border_color=170F0C&bg_color=170F0C&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=DA7885&text_color=E1B2A2&icon_color=BB8470&border_color=170F0C&bg_color=170F0C&show_icons=true)
      
        
### One-dark-pro theme preview
        
        
- :warning: Theme name isn't in snake_case.


        
title_color: <code>#61AFEF</code> | icon_color: <code>#C678DD</code> | text_color: <code>#E5C06E</code> | bg_color: <code>#23272E</code> | border_color: <code>#3B4048</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=61AFEF&text_color=E5C06E&icon_color=C678DD&border_color=3B4048&bg_color=23272E&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=61AFEF&text_color=E5C06E&icon_color=C678DD&border_color=3B4048&bg_color=23272E&show_icons=true)
      
        
### Holi-theme theme preview
        
        
- :warning: Theme name isn't in snake_case.


        
title_color: <code>#5FABEE</code> | icon_color: <code>#5FABEE</code> | text_color: <code>#D6E7FF</code> | bg_color: <code>#030314</code> | border_color: <code>#85A4C0</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=5FABEE&text_color=D6E7FF&icon_color=5FABEE&border_color=85A4C0&bg_color=030314&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=5FABEE&text_color=D6E7FF&icon_color=5FABEE&border_color=85A4C0&bg_color=030314&show_icons=true)

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/2556#issuecomment-1455078558) comment above for more information.

**Comment by Zo-Bro-23** [comment]
The snake case feature is nice! How does the AA ratio work out though? I didn't add any new themes; these are all existing ones.

**Comment by rickstaa** [comment]
> The snake case feature is nice! How does the AA ratio work out, though? I didn't add any new themes; these are all existing ones.

Yea, the snake case was added for the same reason you wanted to restructure the themes in the first place. Maybe, therefore, the solution where hyphens get replaced with underscores is the best one 🤔? The AA ratio errors are from the fact that these themes have been around a long time and were therefore added before we had the AA tests. Nobody has yet taken the time to make them more AA-compatible 😅.

**Comment by rickstaa** [comment]
@Zo-Bro-23 I reopened this since it actually makes sent. I, however, would just rename the themes with hyphens to underscores. Although this will break the theme for some people, it will just fall back to the default theme, which is, in my opinion, better than adding two versions of a theme.

**Pull request closed without merging**
