### PR TITLE
Add loading Animation to Most used Language card

### LINKED ISSUE #1046: Add loading animation to Most used language card
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
The main stats card seems to be the only one having an animation when being loaded*, which is sad when you use other cards like the Most languages one**.

My feature request is to have an animation for this card type too. Right now my idea would be to make the languages appear similar to the text on the stats card (Ease-in-out with 100 transparent to 0 transparent) and have the line showing the distribution of languages "load" (extend from left to right) with each separate language, where each new line will cover less of the previous line to achieve the current look of it.

*I don't use Wakka-time so idk if that one has animations.
**I talk about the compact version.

**Describe alternatives you've considered**
Only alternative I can see is, if I would implement my own solutions, which isn't as easy for me, especially since I can't code in this particular language.

**Additional context**

### PR DESCRIPTION
**Pull request by RedHeadphone**
Fixes #1046

### Previews:

[compact](https://user-images.githubusercontent.com/55500003/195656261-62ab7e56-d711-4071-8953-008264a45ebd.webm)
[non-compact](https://user-images.githubusercontent.com/55500003/195972887-c4a6ec0b-1425-4e90-8d51-59eb5a10ef7f.webm)

### CODE REVIEW

**Comment by RedHeadphone** [comment]
@rickstaa  review PR please

**Review by rickstaa — APPROVED** [review]

**Comment by rickstaa** [comment]
@RedHeadphone I added two changes in [e51d6c9](https://github.com/anuraghazra/github-readme-stats/pull/2197/commits/e51d6c9af1c2ba0e86f5c359fb09dd94b614670e), but apart from that, your PR looks good to me. Thanks a lot for your contribution! 🚀 I added the `hacktoberfest-accepted` label. I'm not an animator expert, so I will leave the CSS for @anuraghazra to review.

**Comment by RedHeadphone** [comment]
@rickstaa @anuraghazra when would this feature would be merged and deployed?

**Comment by rickstaa** [comment]
> @rickstaa @anuraghazra when would this feature would be merged and deployed?

I think it is good to be merged but I want @anuraghazra to be able to have a look at the animation. I already merged too many PRs myself this month without a review.

**Comment by RedHeadphone** [comment]
any update of merging PR?

**Comment by rickstaa** [comment]
@RedHeadphone tested your pull request again and merged it. Thanks for your contribution! 🚀

**Comment by rickstaa** [comment]
@RedHeadphone see my comment in https://github.com/anuraghazra/github-readme-stats/pull/2396 I temporarily had to revert this because the public Vercel instance is broken.

**Pull request merged**
