### PR TITLE
feat: added Top languages card

### PR DESCRIPTION
**Pull request by anuraghazra**
NEW FEATURE :tada:

Added a `/api/top-langs` route which would show user's top 5 languages.

DONE:
- Fetching logic
- Rendering logic
- Themes support

TODO: 
- Write tests
- More customization work

### CODE REVIEW

**Comment by anuraghazra** [comment]
Preview

**Comment by nombrekeff** [comment]
Nice, I like it!

There is one thing I would change though. What about making the label the same color as the progress? Have you tried that?

I don't know how it will look, but maybe it makes it easier on the eye.

**Comment by nombrekeff** [comment]
And what about letting the user decide the number of languages? In my case, I would like to add just the most popular one or two.

**Comment by anuraghazra** [comment]
> Nice, I like it!
> 
> There is one thing I would change though. What about making the label the same color as the progress? Have you tried that?
> 
> I don't know how it will look, but maybe it makes it easier on the eye.

Yup tried that, looks bad with different themes, because every lang has different color and not all of them are vibrant

**Comment by anuraghazra** [comment]
> And what about letting the user decide the number of languages? In my case, I would like to add just the most popular one or two.

I'll add a parameter `hide_langs_below=10` to hide languages which are below 10%

**Comment by nombrekeff** [comment]
> > Nice, I like it!
> > There is one thing I would change though. What about making the label the same color as the progress? Have you tried that?
> > I don't know how it will look, but maybe it makes it easier on the eye.
> 
> Yup tried that, looks bad with different themes, because every lang has different color and not all of them are vibrant

Yup, that's what I thought might happen. Okay no problem, looks good like this

**Comment by nombrekeff** [comment]
> > And what about letting the user decide the number of languages? In my case, I would like to add just the most popular one or two.
> 
> I'll add a parameter `hide_langs_below=10` to hide languages which are below 10%

🙌  I like that approach

**Comment by anuraghazra** [comment]
Test hide_langs_below

**Comment by nombrekeff** [comment]
Looks good to me! Can you share what it looks like with default theme?

**Comment by anuraghazra** [comment]
@nombrekeff comment updated

**Comment by nombrekeff** [comment]
Thanks, it looks great as well!

**Comment by anuraghazra** [comment]
I think this is ready to be merged! :shipit:

**Pull request merged**
