### PR TITLE
added them

### PR DESCRIPTION
**Pull request by CharlyAnne**

### CODE REVIEW

**Comment by CharlyAnne** [comment]
Added new theme

**Review by CharlyAnne — COMMENTED** [review]
Added new theme

**Comment by CharlyAnne** [comment]
review

**Comment by anuraghazra** [comment]
We are currently pausing addition of new themes. If this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

**Pull request closed without merging**
