### PR TITLE
a new "jolly" theme borns

### PR DESCRIPTION
**Pull request by NoushadBug**

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title-color: <code>#BA409C</code>
      
icon-color: <code>#5A2499</code>
      
text-color: <code>#ffffff</code>
      
bg-color: <code>#291B3E</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=BA409C&icon_color=5A2499&text_color=ffffff&bg_color=291B3E&show_icons=true)

**Review by NoushadBug — COMMENTED** [review]
Please add this jolly theme. peace be upon you

**Comment by anuraghazra** [comment]
Combination is nice but can you make the colors a bit more vivid @NoushadBug ???

**Comment by NoushadBug** [comment]
Sure. I have made some changes. I have given update in another PR. Please check that out.

**Comment by anuraghazra** [comment]
Why on new PR?

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title-color: <code>#ff64da</code>
      
icon-color: <code>#a960ff</code>
      
text-color: <code>#ffffff</code>
      
bg-color: <code>#291B3E</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ff64da&icon_color=a960ff&text_color=ffffff&bg_color=291B3E&show_icons=true)

**Comment by NoushadBug** [comment]
Hello. Sorry for my mistakes. Please have a check on the theme now

**Comment by anuraghazra** [comment]
Looks good, thanks!

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title-color: <code>#ff64da</code>
      
icon-color: <code>#a960ff</code>
      
text-color: <code>#ffffff</code>
      
bg-color: <code>#291B3E</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ff64da&icon_color=a960ff&text_color=ffffff&bg_color=291B3E&show_icons=true)

**Comment by anuraghazra** [comment]
Congrats on your first PR @NoushadBug

**Comment by NoushadBug** [comment]
thanks buddy

**Comment by NoushadBug** [comment]
Peace

**Pull request merged**
