### PR TITLE
[design] add-some-themes

### PR DESCRIPTION
**Pull request by s-ggul**
Hello, we are Chungnam National University students majoring in computer science in South Korea. 

Please check the 5 design themes we made by sending a pull request! Have a nice day :)

### CODE REVIEW

**Comment by anuraghazra** [comment]
**Automated Theme preview**  
      
      
title_color: <code>#F2AB35</code> | icon_color: <code>#E4B55D</code> | text_color: <code>#FED442</code> | bg_color: <code>#825B21</code>
      
      
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=F2AB35&icon_color=E4B55D&text_color=FED442&bg_color=825B21&show_icons=true)

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=F2AB35&icon_color=E4B55D&text_color=FED442&bg_color=825B21&show_icons=true)
      
      
  
Hi thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).  
  
We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:x: Theme PR does not adhere to our guidelines.
      
## Test results
      
- :x: almond
- :x: lemontree
- :x: watercolor
- :x: matcha
- :x: starrynight

      
**Result:** :x: Some themes are invalid.


  
Unfortunately, your theme PR does not adhere to our [theme guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution). Please fix the issues below, and we will review your  
 PR again. This pull request will **automatically close in 15 days** if no changes are made. After this time, you must re-open the PR for it to be reviewed.

      
      
## Details
      
        
### Almond theme preview
        
        
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=F2AB35&bcolor=825B21).
- :warning: `icon_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=E4B55D&bcolor=825B21).
- :warning: `text_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=FED442&bcolor=825B21).


        
title_color: <code>#F2AB35</code> | icon_color: <code>#E4B55D</code> | text_color: <code>#FED442</code> | bg_color: <code>#825B21</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=F2AB35&icon_color=E4B55D&text_color=FED442&bg_color=825B21&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=F2AB35&icon_color=E4B55D&text_color=FED442&bg_color=825B21&show_icons=true)
      
        
### Lemontree theme preview
        
        
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=C8EA90&bcolor=559B5B).
- :warning: `icon_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=90B987&bcolor=559B5B).
- :warning: `text_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=ECE883&bcolor=559B5B).


        
title_color: <code>#C8EA90</code> | icon_color: <code>#90B987</code> | text_color: <code>#ECE883</code> | bg_color: <code>#559B5B</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=C8EA90&icon_color=90B987&text_color=ECE883&bg_color=559B5B&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=C8EA90&icon_color=90B987&text_color=ECE883&bg_color=559B5B&show_icons=true)
      
        
### Watercolor theme preview
        
        
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=0384BD&bcolor=E5EDF8).
- :warning: `icon_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=EDBC7A&bcolor=E5EDF8).
- :warning: `text_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=E29E93&bcolor=E5EDF8).


        
title_color: <code>#0384BD</code> | icon_color: <code>#EDBC7A</code> | text_color: <code>#E29E93</code> | bg_color: <code>#E5EDF8</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=0384BD&icon_color=EDBC7A&text_color=E29E93&bg_color=E5EDF8&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=0384BD&icon_color=EDBC7A&text_color=E29E93&bg_color=E5EDF8&show_icons=true)
      
        
### Matcha theme preview
        
        
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=C1E1C1&bcolor=8A9A5B).
- :warning: `icon_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=C1E1C1&bcolor=8A9A5B).
- :warning: `text_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=355E3B&bcolor=8A9A5B).


        
title_color: <code>#C1E1C1</code> | icon_color: <code>#C1E1C1</code> | text_color: <code>#355E3B</code> | bg_color: <code>#8A9A5B</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=C1E1C1&icon_color=C1E1C1&text_color=355E3B&bg_color=8A9A5B&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=C1E1C1&icon_color=C1E1C1&text_color=355E3B&bg_color=8A9A5B&show_icons=true)
      
        
### Starrynight theme preview
        
        
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=FFFF8F&bcolor=6082B6).
- :warning: `icon_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=FFFF8F&bcolor=6082B6).
- :warning: `text_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=023020&bcolor=6082B6).


        
title_color: <code>#FFFF8F</code> | icon_color: <code>#FFFF8F</code> | text_color: <code>#023020</code> | bg_color: <code>#6082B6</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FFFF8F&icon_color=FFFF8F&text_color=023020&bg_color=6082B6&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FFFF8F&icon_color=FFFF8F&text_color=023020&bg_color=6082B6&show_icons=true)

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1336#issuecomment-1264658481) comment above for more information.

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1336#issuecomment-1264658481) comment above for more information.

**Comment by rickstaa** [comment]
This PR has been automatically closed due to inactivity. Please feel free to reopen it if you need to continue working on it.	
Thank you for your contributions.

**Pull request closed without merging**
