### PR TITLE
style(theme): add transblue

### PR DESCRIPTION
**Pull request by Hephaest**
Hi @anuraghazra,

I provide a reasonable and compatible theme for both light and dark modes. Thanks for reviewing the PR.

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title_color: <code>#1d87da</code> | icon_color: <code>#539bf5</code> | text_color: <code>#539bf5</code> | bg_color: <code>#0000</code>
      
      
Link: https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=1d87da&icon_color=539bf5&text_color=539bf5&bg_color=0000&show_icons=true

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=1d87da&icon_color=539bf5&text_color=539bf5&bg_color=0000&show_icons=true)
      
      
  
> Hi thanks for the theme contribution, please read our theme contribution guidelines

  
> We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 
  
> Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

**Comment by Hephaest** [comment]
One of acceptable solutions for Discussion #690 and #1010.

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: transblue

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Transblue theme preview
        
        

        
title_color: <code>#1d87da</code> | icon_color: <code>#539bf5</code> | text_color: <code>#539bf5</code> | bg_color: <code>#0000</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=1d87da&icon_color=539bf5&text_color=539bf5&bg_color=0000&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=1d87da&icon_color=539bf5&text_color=539bf5&bg_color=0000&show_icons=true)

**Review by rickstaa — APPROVED** [review]

**Review by rickstaa — APPROVED** [review]

**Comment by Hephaest** [comment]
Hi @rickstaa, seems like I need your help to approve running workflows before merging the PR. Can you help me out? Thanks!

**Review by rickstaa — APPROVED** [review]

**Comment by rickstaa** [comment]
@Hephaest Thanks for your theme PR. I just ran the improved theme-preview action that's why you received a message. It looks like your theme is good to merge. However, we have more than 100 themes open, so we are currently only merging themes that receive several upvotes or that are based on very popular Vscode themes. I will keep this PR open so that we can track how much interest there is in your theme.

**Comment by rickstaa** [comment]
Ah, I just saw that you have a transparent theme. We decided that we will provide one transparent theme for now (see https://github.com/anuraghazra/github-readme-stats/issues/1001#issuecomment-1264600231). The others people can create by changing the background to transparent.

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&theme=default&bg_color=ffff&show_icons=true)](https://github.com/anuraghazra/github-readme-stats)
 ```

[Anurag's GitHub stats](https://github.com/anuraghazra/github-readme-stats)

**Comment by rickstaa** [comment]
I will close this for now. I will re-open if we change this in the future.

**Pull request closed without merging**
