### PR TITLE
Add alyan

### PR DESCRIPTION
**Pull request by SaurFort**
Add theme a named alyan, the color was inspired by a project on I work. If you accept this PR I will immediately use it on my profile.

image_2023-02-15_171455233

### CODE REVIEW

**Comment by SaurFort** [comment]
This time colors are correct ^^"

**Comment by SaurFort** [comment]
Now the theme is valid. I have a question can I modify colors if the PR was accept ?

**Comment by Zo-Bro-23** [comment]
> Now the theme is valid. I have a question can I modify colors if the PR was accept ?

What do you mean? Note that you can use custom colors by specifying the colors directly in the image URL (see [this](https://github.com/anuraghazra/github-readme-stats#common-options)). Also, if this theme is based on a VSCode theme, please mention which. This will increase your chances of merging.

**Comment by SaurFort** [comment]
This theme is not based on a VSCode theme but I am working on a plugin to add it.

**Comment by Zo-Bro-23** [comment]
I'm sorry, but it looks too similar to the themes we already have (`transparent`, `tokyonight`, `prussian`, `algolia`, `jolly`, ). Please feel free to reopen the PR once you modify the colors a bit!

**Comment by SaurFort** [comment]
> I'm sorry, but it looks too similar to the themes we already have (`transparent`, `tokyonight`, `prussian`, `algolia`, `jolly`). Please feel free to reopen the PR once you modify the colors a bit!

What do you think I can change to make it better?

**Comment by Zo-Bro-23** [comment]
> > I'm sorry, but it looks too similar to the themes we already have (`transparent`, `tokyonight`, `prussian`, `algolia`, `jolly`). Please feel free to reopen the PR once you modify the colors a bit!
> 
> What do you think I can change to make it better?

VSCode-based themes have a better chance of merging. For themes that are not VSCode-based, we look for uniqueness and community reception. Developing a theme that is unique (see `./themes/README.md`) and looks good (upvotes) will be the way to go! As for this particular theme, I closed the PR because it closely resembles some of the themes we already have. We are so selective on adding new themes because we don't want to bloat up the theme base; thanks for understanding!

**Comment by SaurFort** [comment]
> > > I'm sorry, but it looks too similar to the themes we already have (`transparent`, `tokyonight`, `prussian`, `algolia`, `jolly`). Please feel free to reopen the PR once you modify the colors a bit!
> > 
> > 
> > What do you think I can change to make it better?
> 
> VSCode-based themes have a better chance of merging. For themes that are not VSCode-based, we look for uniqueness and community reception. Developing a theme that is unique (see `./themes/README.md`) and looks good (upvotes) will be the way to go! As for this particular theme, I closed the PR because it closely resembles some of the themes we already have. We are so selective on adding new themes because we don't want to bloat up the theme base; thanks for understanding!

Thanks for your feedback, I will see if I have any ideas for a unique theme.

**Pull request closed without merging**
