### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by lucsn**

### CODE REVIEW

**Comment by lucsn** [comment]
Therme demolsn

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:x: Theme PR does not adhere to our guidelines.
      
## Test results
      
- :x: demolsn

      
**Result:** :x: Some themes are invalid.


  
Unfortunately, your theme PR does not adhere to our [theme guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution). Please fix the issues below, and we will review your  
 PR again. This pull request will **automatically close in 15 days** if no changes are made. After this time, you must re-open the PR for it to be reviewed.

      
      
## Details
      
        
### Demolsn theme preview
        
        
- :warning: `icon_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=FACA22&bcolor=ffffff).


        
title_color: <code>#262B4F</code> | icon_color: <code>#FACA22</code> | text_color: <code>#262B4F</code> | bg_color: <code>#ffffff</code> | border_color: <code>#FACA22</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=262B4F&icon_color=FACA22&text_color=262B4F&bg_color=ffffff&border_color=FACA22&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=262B4F&icon_color=FACA22&text_color=262B4F&bg_color=ffffff&border_color=FACA22&show_icons=true)

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1603#issuecomment-1264657890) comment above for more information.

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1603#issuecomment-1264657890) comment above for more information.

**Comment by rickstaa** [comment]
This PR has been automatically closed due to inactivity. Please feel free to reopen it if you need to continue working on it.	
Thank you for your contributions.

**Pull request closed without merging**
