### PR TITLE
rose pine/master rebase

### PR DESCRIPTION
**Pull request by rickstaa**
This is #892 rebased on the current master branch.

### CODE REVIEW

**Comment by anuraghazra** [comment]
**Automated Theme Preview**  
      
      

      
title_color: <code>#9ccfd8</code> | icon_color: <code>#ebbcba</code> | text_color: <code>#e0def4</code> | bg_color: <code>#191724</code>
      
      
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=9ccfd8&icon_color=ebbcba&text_color=e0def4&bg_color=191724&show_icons=true)
      
      
  
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).  
  
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

**Comment by rickstaa** [comment]
@ThatOneCalculator I think this PR now is ready to be merged since your theme is not a VSCode theme, I first want to have this approved by @anuraghazra to prevent cluttering of the theme database.

I, however, think the theme is distinct enough from the themes we already have https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md.

**Comment by rickstaa** [comment]
@ThatOneCalculator Thanks again for your contribution. I merged this since it is distinct enough from the other themes we already have, and your previous pull request had a lot of support. Maybe you can create a Vscode theme for it too?

**Comment by ThatOneCalculator** [comment]
> @ThatOneCalculator Thanks again for your contribution. I merged this since it is distinct from the other themes we already have, and your theme was highly requested. Maybe you can create a Vscode theme for it too?

It's been a VSCode theme for a while 😁
Just search Rosé Pine in extensions

**Comment by ThatOneCalculator** [comment]
Also, https://rosepinetheme.com

**Comment by anuraghazra** [comment]
Looks beautiful! Thanks @ThatOneCalculator

**Comment by ThatOneCalculator** [comment]
@rickstaa @anuraghazra 
I can't seem to find the theme here, btw:
https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md

**Comment by rickstaa** [comment]
@ThatOneCalculator Thanks for letting us know. We just merged the pull request that the GA created for that (see https://github.com/anuraghazra/github-readme-stats/pull/1632).

**Comment by ThatOneCalculator** [comment]
Also, it's now on https://rosepinetheme.com/themes !

**Comment by rickstaa** [comment]
@ThatOneCalculator That's great. I think your theme is a great addition to our little tool.

**Pull request merged**
