### PR TITLE
themes: add ambient_gradient theme for test

### PR DESCRIPTION
**Pull request by qwerty541**
I want to check if we currently support gradient themes addition.

### CODE REVIEW

**Comment by rickstaa** [comment]
@qwerty541 looks like the test failed 🤔.

**Review by qwerty541 — COMMENTED** [review]
> @qwerty541 looks like the test failed 🤔.

@rickstaa Test workflow executed successfully, but theme preview failed. Looks like i made a mistake while implementing feature to allow addition of gradient themes. I have opened pull request https://github.com/anuraghazra/github-readme-stats/pull/3427/files to resolve the issue, please check it.

**Comment by qwerty541** [comment]
@rickstaa Looks like theme preview workflow finally works with gradient themes. What do you think about adding 2-3 such themes into our collection before disabling this workflow, since currently we do not provide any gradient theme?

**Comment by rickstaa** [comment]
> @rickstaa Looks like theme preview workflow finally works with gradient themes. What do you think about adding 2-3 such themes into our collection before disabling this workflow, since currently we do not provide any gradient theme?

I'm okay with adding three gradient themes 👍🏻. But let's first check with @anuraghazra.

**Comment by qwerty541** [comment]
> > @rickstaa Looks like theme preview workflow finally works with gradient themes. What do you think about adding 2-3 such themes into our collection before disabling this workflow, since currently we do not provide any gradient theme?
> 
> I'm okay with adding three gradient themes 👍🏻. But let's first check with @anuraghazra.

Since we didn't received response from Anurag during two weeks, i suggest to merge just this one gradient theme, and may be one more from you, if you're interested, in order to not block implementation of https://github.com/anuraghazra/github-readme-stats/issues/3404. What do you think?

**Review by rickstaa — APPROVED** [review]

**Review by anuraghazra — APPROVED** [review]

**Pull request merged**
