### PR TITLE
Fixes #3184 : added white border

### LINKED ISSUE #3184: add border for "graphs"
### Is your feature request related to a problem? Please describe.

Some Languages colors blend into the background of my "top languages" card image

### Describe the solution you'd like

I would like to have a white or some other color border around stuff like the top languages bar, to increase its visibility and looks.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vinfinity7**
added white border to rect element

### CODE REVIEW

**Review by qwerty541 — COMMENTED** [review]
Hey, @vinfinity7! Thanks for opening pull request!

I expect graph border to be optional, top languages card endpoint should receive new querystring parameter `graph_border_color`. I think it will be better to give ability for user's to choose color. It is also adviseble to cover this changes with test.

If we make this enabled by default, thousands of users' cards will be corrupted because they don't expect the card to change on its own.

It would be very helpful if you could attach a screenshot of how graph with border looks like.

It’s also worth adding that the other collaborators and I haven’t even discussed whether we want to add this feature to the project.

**Comment by Arbee4ever** [comment]
I'd also appreciate it if you could set the thickness of the border

**Comment by vinfinity7** [comment]
hi @qwerty541 , I've been trying to figure out as to how to see the output of the changes that I have done , might need a little assistance here !

**Comment by qwerty541** [comment]
> hi @qwerty541 , I've been trying to figure out as to how to see the output of the changes that I have done , might need a little assistance here !

We have [local development](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#local-development) section inside our contributing guidelines. Just follow through all these steps.

image

**Pull request closed without merging**
