### PR TITLE
Added two themes - Lunar & Dev

### PR DESCRIPTION
**Pull request by Abod1960**
just added another two themes 😊

### CODE REVIEW

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:x: Theme PR does not adhere to our guidelines.
      
## Test results
      
- :x: dev
- :heavy_check_mark: lunar

      
**Result:** :x: Some themes are invalid.


  
Unfortunately, your theme PR does not adhere to our [theme guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution). Please fix the issues below, and we will review your  
 PR again. This pull request will **automatically close in 15 days** if no changes are made. After this time, you must re-open the PR for it to be reviewed.

      
      
## Details
      
        
### Dev theme preview
        
        
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=4f5975&bcolor=1c2028).
- :warning: `text_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=4f5975&bcolor=1c2028).


        
title_color: <code>#4f5975</code> | icon_color: <code>#59a7d4</code> | text_color: <code>#4f5975</code> | bg_color: <code>#1c2028</code> | border_color: <code>#212630</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=4f5975&icon_color=59a7d4&text_color=4f5975&bg_color=1c2028&border_color=212630&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=4f5975&icon_color=59a7d4&text_color=4f5975&bg_color=1c2028&border_color=212630&show_icons=true)
      
        
### Lunar theme preview
        
        

        
title_color: <code>#0284e8</code> | icon_color: <code>#59a7d4</code> | text_color: <code>#f3f3f3</code> | bg_color: <code>#161616</code> | border_color: <code>#202020</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=0284e8&icon_color=59a7d4&text_color=f3f3f3&bg_color=161616&border_color=202020&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=0284e8&icon_color=59a7d4&text_color=f3f3f3&bg_color=161616&border_color=202020&show_icons=true)

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1706#issuecomment-1264657651) comment above for more information.

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1706#issuecomment-1264657651) comment above for more information.

**Comment by Abod1960** [comment]
so after this time, both of these themes are not really supported so far, so I am going to create a new PR with a new theme and close this one. 👍

**Comment by rickstaa** [comment]
@Abod1960 Yea, we recently updated our tests to test old theme PRs. Looks like the luna theme is already valid, but the dev theme needs some changes. You can also simply open #1706 again and push changes here to get the theme PR re-reviewed.

**Comment by Abod1960** [comment]
> @Abod1960 Yea, we recently updated our tests to test old theme PRs. The luna theme is already valid, but the dev theme needs some changes. You can also open #1706 again and push changes here to get the theme PR re-reviewed.

so lunar actually got changed to @solis-theme so it is not supported anymore...
but yea I will make a new PR for my theme @moonlight-theme...

**Pull request closed without merging**
