### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by AJ-Wuu**

### CODE REVIEW

**Comment by anuraghazra** [comment]
**Automated Theme Preview**  
      
      
- :warning: `title_color` does not passes [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=7fa0f4&bcolor=434aa8)


      
title_color: <code>#7fa0f4</code> | icon_color: <code>#d7dcf6</code> | text_color: <code>#def0ff</code> | bg_color: <code>#434aa8</code>
      
      
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=7fa0f4&icon_color=d7dcf6&text_color=def0ff&bg_color=434aa8&show_icons=true)

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=7fa0f4&icon_color=d7dcf6&text_color=def0ff&bg_color=434aa8&show_icons=true)
      
      
  
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).  
  
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:x: Theme PR does not adhere to our guidelines.
      
## Test results
      
- :x: jay

      
**Result:** :x: Some themes are invalid.


  
Unfortunately, your theme PR does not adhere to our [theme guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution). Please fix the issues below, and we will review your  
 PR again. This pull request will **automatically close in 15 days** if no changes are made. After this time, you must re-open the PR for it to be reviewed.

      
      
## Details
      
        
### Jay theme preview
        
        
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=7fa0f4&bcolor=434aa8).


        
title_color: <code>#7fa0f4</code> | icon_color: <code>#d7dcf6</code> | text_color: <code>#def0ff</code> | bg_color: <code>#434aa8</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=7fa0f4&icon_color=d7dcf6&text_color=def0ff&bg_color=434aa8&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=7fa0f4&icon_color=d7dcf6&text_color=def0ff&bg_color=434aa8&show_icons=true)

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1523#issuecomment-1264658139) comment above for more information.

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1523#issuecomment-1264658139) comment above for more information.

**Comment by rickstaa** [comment]
This PR has been automatically closed due to inactivity. Please feel free to reopen it if you need to continue working on it.	
Thank you for your contributions.

**Pull request closed without merging**
