### PR TITLE
New theme green_sky

### PR DESCRIPTION
**Pull request by 0ME9A**

### CODE REVIEW

**Comment by anuraghazra** [comment]
**Automated Theme Preview**  
      
      

      
title_color: <code>#14FF5B</code> | icon_color: <code>#14FF5B</code> | text_color: <code>#FFFFFF</code> | bg_color: <code>#004280</code>
      
      
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=14FF5B&icon_color=14FF5B&text_color=FFFFFF&bg_color=004280&show_icons=true)

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=14FF5B&icon_color=14FF5B&text_color=FFFFFF&bg_color=004280&show_icons=true)
      
      
  
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).  
  
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: green_sky

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Green_sky theme preview
        
        

        
title_color: <code>#14FF5B</code> | icon_color: <code>#14FF5B</code> | text_color: <code>#FFFFFF</code> | bg_color: <code>#004280</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=14FF5B&icon_color=14FF5B&text_color=FFFFFF&bg_color=004280&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=14FF5B&icon_color=14FF5B&text_color=FFFFFF&bg_color=004280&show_icons=true)

**Review by rickstaa — APPROVED** [review]

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: green_sky

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Green_sky theme preview
        
        

        
title_color: <code>#14FF5B</code> | icon_color: <code>#14FF5B</code> | text_color: <code>#FFFFFF</code> | bg_color: <code>#004280</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=14FF5B&icon_color=14FF5B&text_color=FFFFFF&bg_color=004280&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=14FF5B&icon_color=14FF5B&text_color=FFFFFF&bg_color=004280&show_icons=true)

**Review by rickstaa — APPROVED** [review]

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: green_sky

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Green_sky theme preview
        
        

        
title_color: <code>#14FF5B</code> | icon_color: <code>#14FF5B</code> | text_color: <code>#FFFFFF</code> | bg_color: <code>#004280</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=14FF5B&icon_color=14FF5B&text_color=FFFFFF&bg_color=004280&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=14FF5B&icon_color=14FF5B&text_color=FFFFFF&bg_color=004280&show_icons=true)

**Review by rickstaa — APPROVED** [review]

**Review by rickstaa — APPROVED** [review]

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: green_sky

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Green_sky theme preview
        
        

        
title_color: <code>#14FF5B</code> | icon_color: <code>#14FF5B</code> | text_color: <code>#FFFFFF</code> | bg_color: <code>#004280</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=14FF5B&icon_color=14FF5B&text_color=FFFFFF&bg_color=004280&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=14FF5B&icon_color=14FF5B&text_color=FFFFFF&bg_color=004280&show_icons=true)

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: green_sky

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Green_sky theme preview
        
        

        
title_color: <code>#14FF5B</code> | icon_color: <code>#14FF5B</code> | text_color: <code>#FFFFFF</code> | bg_color: <code>#004280</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=14FF5B&icon_color=14FF5B&text_color=FFFFFF&bg_color=004280&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=14FF5B&icon_color=14FF5B&text_color=FFFFFF&bg_color=004280&show_icons=true)

**Review by rickstaa — APPROVED** [review]

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: green_sky

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Green_sky theme preview
        
        

        
title_color: <code>#14FF5B</code> | icon_color: <code>#14FF5B</code> | text_color: <code>#FFFFFF</code> | bg_color: <code>#004280</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=14FF5B&icon_color=14FF5B&text_color=FFFFFF&bg_color=004280&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=14FF5B&icon_color=14FF5B&text_color=FFFFFF&bg_color=004280&show_icons=true)

**Review by rickstaa — APPROVED** [review]

**Review by rickstaa — APPROVED** [review]

**Comment by rickstaa** [comment]
@0ME9A, thanks for your theme pull request!

> [!WARNING]  
> Keep in mind that we already have a vast collection of different themes. To keep their number manageable, we began to add only themes supported by the community. Your pull request with theme addition will be merged once we get enough positive feedback from the community in the form of thumbs up :+1: emojis (see [#1935](https://github.com/anuraghazra/github-readme-stats/issues/1935#top-themes-prs)). We expect to see at least 10-15 thumbs up before deciding to merge your pull request into the master branch. Remember that you can also support themes of other contributors that you liked to speed up their merge.

  
> [!NOTE]  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

**Pull request closed without merging**
