### PR TITLE
feat: adding moonlight based theme

### PR DESCRIPTION
**Pull request by LucasAlexander13**

### CODE REVIEW

**Comment by anuraghazra** [comment]
**Automated Theme Preview**  
      
      
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=ff757f&bcolor=3a3e59)
- :warning: `icon_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=599dff&bcolor=3a3e59)


      
title_color: <code>#ff757f</code> | icon_color: <code>#599dff</code> | text_color: <code>#f8f8f8</code> | bg_color: <code>#3a3e59</code>
      
      
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ff757f&icon_color=599dff&text_color=f8f8f8&bg_color=3a3e59&show_icons=true)

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ff757f&icon_color=599dff&text_color=f8f8f8&bg_color=3a3e59&show_icons=true)
      
      
  
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).  
  
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: moonlight

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Moonlight theme preview
        
        

        
title_color: <code>#ff757f</code> | icon_color: <code>#599dff</code> | text_color: <code>#f8f8f8</code> | bg_color: <code>#222436</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ff757f&icon_color=599dff&text_color=f8f8f8&bg_color=222436&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ff757f&icon_color=599dff&text_color=f8f8f8&bg_color=222436&show_icons=true)

**Review by rickstaa — APPROVED** [review]

**Review by rickstaa — APPROVED** [review]

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: moonlight

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Moonlight theme preview
        
        

        
title_color: <code>#ff757f</code> | icon_color: <code>#599dff</code> | text_color: <code>#f8f8f8</code> | bg_color: <code>#222436</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ff757f&icon_color=599dff&text_color=f8f8f8&bg_color=222436&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ff757f&icon_color=599dff&text_color=f8f8f8&bg_color=222436&show_icons=true)

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: moonlight

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Moonlight theme preview
        
        

        
title_color: <code>#ff757f</code> | icon_color: <code>#599dff</code> | text_color: <code>#f8f8f8</code> | bg_color: <code>#222436</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ff757f&icon_color=599dff&text_color=f8f8f8&bg_color=222436&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ff757f&icon_color=599dff&text_color=f8f8f8&bg_color=222436&show_icons=true)

**Review by rickstaa — APPROVED** [review]

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: moonlight

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Moonlight theme preview
        
        

        
title_color: <code>#ff757f</code> | icon_color: <code>#599dff</code> | text_color: <code>#f8f8f8</code> | bg_color: <code>#222436</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ff757f&icon_color=599dff&text_color=f8f8f8&bg_color=222436&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ff757f&icon_color=599dff&text_color=f8f8f8&bg_color=222436&show_icons=true)

**Review by rickstaa — APPROVED** [review]

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: moonlight

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Moonlight theme preview
        
        

        
title_color: <code>#ff757f</code> | icon_color: <code>#599dff</code> | text_color: <code>#f8f8f8</code> | bg_color: <code>#222436</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ff757f&icon_color=599dff&text_color=f8f8f8&bg_color=222436&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ff757f&icon_color=599dff&text_color=f8f8f8&bg_color=222436&show_icons=true)

**Review by rickstaa — APPROVED** [review]

**Review by rickstaa — APPROVED** [review]

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: moonlight

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Moonlight theme preview
        
        

        
title_color: <code>#ff757f</code> | icon_color: <code>#599dff</code> | text_color: <code>#f8f8f8</code> | bg_color: <code>#222436</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ff757f&icon_color=599dff&text_color=f8f8f8&bg_color=222436&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ff757f&icon_color=599dff&text_color=f8f8f8&bg_color=222436&show_icons=true)

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: moonlight

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Moonlight theme preview
        
        

        
title_color: <code>#ff757f</code> | icon_color: <code>#599dff</code> | text_color: <code>#f8f8f8</code> | bg_color: <code>#222436</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ff757f&icon_color=599dff&text_color=f8f8f8&bg_color=222436&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ff757f&icon_color=599dff&text_color=f8f8f8&bg_color=222436&show_icons=true)

**Review by rickstaa — APPROVED** [review]

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: moonlight

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Moonlight theme preview
        
        

        
title_color: <code>#ff757f</code> | icon_color: <code>#599dff</code> | text_color: <code>#f8f8f8</code> | bg_color: <code>#222436</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ff757f&icon_color=599dff&text_color=f8f8f8&bg_color=222436&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ff757f&icon_color=599dff&text_color=f8f8f8&bg_color=222436&show_icons=true)

**Review by rickstaa — APPROVED** [review]

**Review by rickstaa — APPROVED** [review]

**Comment by anuraghazra** [comment]
We are currently pausing addition of new themes. If this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

**Pull request closed without merging**
