### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by fojanb**
Using GitHub-ish colors and non-eye-hurting colors :)

### CODE REVIEW

**Comment by anuraghazra** [comment]
**Automated Theme Preview**  
      
      
- :warning: `title_color` does not passes [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=26a641&bcolor=2d333b)
- :warning: `icon_color` does not passes [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=26a641&bcolor=2d333b)


      
title_color: <code>#26a641</code> | icon_color: <code>#26a641</code> | text_color: <code>#cdd9e5</code> | bg_color: <code>#2d333b</code>
      
      
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=26a641&icon_color=26a641&text_color=cdd9e5&bg_color=2d333b&show_icons=true)

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=26a641&icon_color=26a641&text_color=cdd9e5&bg_color=2d333b&show_icons=true)
      
      
  
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).  
  
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:x: Theme PR does not adhere to our guidelines.
      
## Test results
      
- :x: fojan

      
**Result:** :x: Some themes are invalid.


  
Unfortunately, your theme PR does not adhere to our [theme guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution). Please fix the issues below, and we will review your  
 PR again. This pull request will **automatically close in 15 days** if no changes are made. After this time, you must re-open the PR for it to be reviewed.

      
      
## Details
      
        
### Fojan theme preview
        
        
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=2a9d8f&bcolor=2d333b).


        
title_color: <code>#2a9d8f</code> | icon_color: <code>#b7e4c7</code> | text_color: <code>#cdd9e5</code> | bg_color: <code>#2d333b</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=2a9d8f&icon_color=b7e4c7&text_color=cdd9e5&bg_color=2d333b&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=2a9d8f&icon_color=b7e4c7&text_color=cdd9e5&bg_color=2d333b&show_icons=true)

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1510#issuecomment-1264658177) comment above for more information.

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1510#issuecomment-1264658177) comment above for more information.

**Comment by rickstaa** [comment]
This PR has been automatically closed due to inactivity. Please feel free to reopen it if you need to continue working on it.	
Thank you for your contributions.

**Pull request closed without merging**
