### PR TITLE
Added neon theme

### PR DESCRIPTION
**Pull request by anirban12d**
Added neon themes with bright colors that goes well with dark backgrounds.

### CODE REVIEW

**Comment by rickstaa** [comment]
Thanks for your contribution! I love it 🚀.

**Comment by eduardorodrigues234** [comment]
hello

**Review by eduardorodrigues234 — COMMENTED** [review]
hello

**Comment by qwerty541** [comment]
> hello

@eduardorodrigues234 Hello, please stop spamming.

**Pull request merged**
