### PR TITLE
"jolly" theme revised

### PR DESCRIPTION
**Pull request by NoushadBug**
@anuraghazra brother please give a check now

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title-color: <code>#C6D211</code>
      
icon-color: <code>#F94C29</code>
      
text-color: <code>#ffffff</code>
      
bg-color: <code>#291B3E</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=C6D211&icon_color=F94C29&text_color=ffffff&bg_color=291B3E&show_icons=true)

**Comment by NoushadBug** [comment]
is it seems ok now?

**Comment by anuraghazra** [comment]
I just said make it "vivid" and you entirely changed the color scheme. do the changes on #530

**Comment by anuraghazra** [comment]
Closing this in favor of #530

**Pull request closed without merging**
