### PR TITLE
Adding new theme

### PR DESCRIPTION
**Pull request by engineerscodes**
cool pink color

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title-color: <code>#d73a49</code>
      
icon-color: <code>#d73a49</code>
      
text-color: <code>#d73a49</code>
      
bg-color: <code>#ffdce0</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=d73a49&icon_color=d73a49&text_color=d73a49&bg_color=ffdce0&show_icons=true)

**Comment by engineerscodes** [comment]
my 2nd pull request to your repo

**Comment by anuraghazra** [comment]
Hi thanks for opening the theme contribution @

We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 

Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

**Comment by anuraghazra** [comment]
Hi thanks for opening the theme contribution @engineerscodes 

We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 

Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

**Comment by engineerscodes** [comment]
Thanks bro

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title-color: <code>#d73a49</code>
      
icon-color: <code>#d73a49</code>
      
text-color: <code>#d73a49</code>
      
bg-color: <code>#ffdce0</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=d73a49&icon_color=d73a49&text_color=d73a49&bg_color=ffdce0&show_icons=true)

**Pull request closed without merging**
