### PR TITLE
feat: clarify wakatime 403 error

### LINKED ISSUE #2683: Wakatime stats  is not working
### Describe the bug

The card that I use is this: https://github-readme-stats.vercel.app/api/wakatime?username=IsfetShen&theme=midnight-purple 

I checked the readme official and there's also not working

### Expected behaviour

_No response_

### Screenshots / Live demo link

image

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mrtnvgr**
Closes #2683, #2682, #2671

### CODE REVIEW

**Comment by KevinGuancheDarias** [comment]
I think the message would be misleading as the last_7_days option can too provide the same error for some users, it looks like the range option stopped been flexible by the wakatime api, as only the configured value in the wakatime seems to work, for example I have all_time in wakatime,  so only all_time will work in *range* request param but not the last_7_days nor last_30_days values

image


I would set the message to something like "The specified range doesn't match the time range configured in your wakatime settings to be publicly available", or if wakatime doesn't fix their side, I would directly remove the range option and use the one configured in the profile

**Comment by mrtnvgr** [comment]
> I think the message would be misleading as the last_7_days option can too provide the same error for some users, it looks like the range option stopped been flexible by the wakatime api, as only the configured value in the wakatime seems to work, for example I have all_time in wakatime,  so only all_time will work in *range* request param but not the last_7_days nor last_30_days values
> 
> image
> 
> 
> I would set the message to something like "The specified range doesn't match the time range configured in your wakatime settings to be publicly available", or if wakatime doesn't fix their side, I would directly remove the range option and use the one configured in the profile
> 
> Edit: Wakatime API seems to work with all last_7_days, last_30_days, and all_time

Thank you. I want to add that 403 is returned when the range is not specified in the API call parameters.

**Comment by KevinGuancheDarias** [comment]
Hello @mrtnvgr I have made a mistake in my "Edit" section, wakatime only works with the configured setting, It was working because I was logged in Wakatime, but after I logged out, i get the same behavior than the github-readme-stats project

# Won't work throwing 403 (as setting is set to all_time)
image
image

# Working
image

# When changing the settings to last 7 days in the wakatime settings
image

And then... 😱 
image

**Comment by mrtnvgr** [comment]
@KevinGuancheDarias I updated the error, can you check it? Is it too long?

**Comment by rickstaa** [comment]
Closing this as this should bed fixed already.

**Pull request closed without merging**
