### PR TITLE
Add theme "random-colors"

### PR DESCRIPTION
**Pull request by Ryyn-Sd**
This theme is exactly what it sounds like; it chooses random colors for the title, the icons, the text, and the background!

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)
        Cannot create theme preview

**Comment by anuraghazra** [comment]
Theme preview (bot)
        Cannot create theme preview

**Comment by anuraghazra** [comment]
Theme preview (bot)
        Cannot create theme preview

**Comment by nthnchu** [comment]
@Ryyn-Sd Yours seemed to be generating colors at build time for some reason, but my pull request fixes that (Ryyn-Sd#1). Live deployments:

**Pull request closed without merging**
