### PR TITLE
feature: consider private repo into top languages ranking

### PR DESCRIPTION
**Pull request by Hephaest**
Hi @anuraghazra 👋🏻 

I have taken private repo into Top Languages Ranking consideration. Please review my PR. Have a nice day! ❤️

### CODE REVIEW

**Comment by Hephaest** [comment]
Solved Discussion #814

**Review by Jasonnor — APPROVED** [review]
It works on my GitHub README :)

**Comment by Hephaest** [comment]
Hey @rickstaa, I have merged the `master` branch and redeployed my project again. This PR remains for more than 1 year and I found so many people have used my branch to show their contributions from their private repos. Please let me know if there are some further actions you guys wanna take for this enhancement or anything I can do before merging my PR. Thanks for your time!❤️

**Comment by rickstaa** [comment]
@Hephaest Thanks for creating this pull request. I checked it but don't think it will benefit the public GRS API. GraphQLs [isPrivate](https://docs.github.com/en/graphql/reference/objects#repository) property is used to check if a repository is private. The public API does not access users' private repositories, so this property will always be `false`. For a self-deployed Vercel instance, it is not needed since all private contributions are included by default.

**Pull request closed without merging**
