### PR TITLE
Add light and dark Catppuccin themes, #1977

### PR DESCRIPTION
**Pull request by cosmojg**
"Catppuccin Latte" and "Catppuccin Mocha" come from the official Catppuccin theme, available here: https://github.com/catppuccin/github-readme-stats

### CODE REVIEW

**Comment by anuraghazra** [comment]
**Automated Theme Preview**  
      
      
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=179299&bcolor=eff1f5)


      
title_color: <code>#179299</code> | icon_color: <code>#8839ef</code> | text_color: <code>#4c4f69</code> | bg_color: <code>#eff1f5</code>
      
      
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=179299&icon_color=8839ef&text_color=4c4f69&bg_color=eff1f5&show_icons=true)

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=179299&icon_color=8839ef&text_color=4c4f69&bg_color=eff1f5&show_icons=true)
      
      
  
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).  
  
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

**Comment by rickstaa** [comment]
@cosmojg Thanks for implementing this theme. Sadly the current colours used by the theme are incompatible with the [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=179299&bcolor=eff1f5). The title colour has to be changed before we can merge this PR. The question, however, is if we want to do it here or if we want to raise an issue on https://github.com/catppuccin/github-readme-stats.

Since this is an often requested theme, I assigned myself to this issue, so I don't forget. I can, however, not give an ETA since I'm currently very busy with my graduation, and I first want to implement https://github.com/anuraghazra/github-readme-stats/issues/1659 before I merge any new themes.

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/2009#issuecomment-1264641342) comment above for more information.

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:x: Theme PR does not adhere to our guidelines.
      
## Test results
      
- :x: catppuccin_latte
- :heavy_check_mark: catppuccin_mocha

      
**Result:** :x: Some themes are invalid.


  
Unfortunately, your theme PR does not adhere to our [theme guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution). Please fix the issues below, and we will review your  
 PR again. This pull request will **automatically close in 15 days** if no changes are made. After this time, you must re-open the PR for it to be reviewed.

      
      
## Details
      
        
### Catppuccin_latte theme preview
        
        
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=179299&bcolor=eff1f5).


        
title_color: <code>#179299</code> | icon_color: <code>#8839ef</code> | text_color: <code>#4c4f69</code> | bg_color: <code>#eff1f5</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=179299&icon_color=8839ef&text_color=4c4f69&bg_color=eff1f5&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=179299&icon_color=8839ef&text_color=4c4f69&bg_color=eff1f5&show_icons=true)
      
        
### Catppuccin_mocha theme preview
        
        

        
title_color: <code>#94e2d5</code> | icon_color: <code>#cba6f7</code> | text_color: <code>#cdd6f4</code> | bg_color: <code>#1e1e2e</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=94e2d5&icon_color=cba6f7&text_color=cdd6f4&bg_color=1e1e2e&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=94e2d5&icon_color=cba6f7&text_color=cdd6f4&bg_color=1e1e2e&show_icons=true)

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:x: Theme PR does not adhere to our guidelines.
      
## Test results
      
- :x: catppuccin_latte
- :heavy_check_mark: catppuccin_mocha

      
**Result:** :x: Some themes are invalid.


  
Unfortunately, your theme PR does not adhere to our [theme guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution). Please fix the issues below, and we will review your  
 PR again. This pull request will **automatically close in 15 days** if no changes are made. After this time, you must re-open the PR for it to be reviewed.

      
      
## Details
      
        
### Catppuccin_latte theme preview
        
        
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=179299&bcolor=eff1f5).


        
title_color: <code>#179299</code> | icon_color: <code>#8839ef</code> | text_color: <code>#4c4f69</code> | bg_color: <code>#eff1f5</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=179299&icon_color=8839ef&text_color=4c4f69&bg_color=eff1f5&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=179299&icon_color=8839ef&text_color=4c4f69&bg_color=eff1f5&show_icons=true)
      
        
### Catppuccin_mocha theme preview
        
        

        
title_color: <code>#94e2d5</code> | icon_color: <code>#cba6f7</code> | text_color: <code>#cdd6f4</code> | bg_color: <code>#1e1e2e</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=94e2d5&icon_color=cba6f7&text_color=cdd6f4&bg_color=1e1e2e&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=94e2d5&icon_color=cba6f7&text_color=cdd6f4&bg_color=1e1e2e&show_icons=true)

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/2009#issuecomment-1264642831) comment above for more information.

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/2009#issuecomment-1264646564) comment above for more information.

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:x: Theme PR does not adhere to our guidelines.
      
## Test results
      
- :x: catppuccin_latte
- :heavy_check_mark: catppuccin_mocha

      
**Result:** :x: Some themes are invalid.


  
Unfortunately, your theme PR does not adhere to our [theme guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution). Please fix the issues below, and we will review your  
 PR again. This pull request will **automatically close in 15 days** if no changes are made. After this time, you must re-open the PR for it to be reviewed.

      
      
## Details
      
        
### Catppuccin_latte theme preview
        
        
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=179299&bcolor=eff1f5).


        
title_color: <code>#179299</code> | icon_color: <code>#8839ef</code> | text_color: <code>#4c4f69</code> | bg_color: <code>#eff1f5</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=179299&icon_color=8839ef&text_color=4c4f69&bg_color=eff1f5&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=179299&icon_color=8839ef&text_color=4c4f69&bg_color=eff1f5&show_icons=true)
      
        
### Catppuccin_mocha theme preview
        
        

        
title_color: <code>#94e2d5</code> | icon_color: <code>#cba6f7</code> | text_color: <code>#cdd6f4</code> | bg_color: <code>#1e1e2e</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=94e2d5&icon_color=cba6f7&text_color=cdd6f4&bg_color=1e1e2e&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=94e2d5&icon_color=cba6f7&text_color=cdd6f4&bg_color=1e1e2e&show_icons=true)

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:x: Theme PR does not adhere to our guidelines.
      
## Test results
      
- :x: catppuccin_latte
- :heavy_check_mark: catppuccin_mocha

      
**Result:** :x: Some themes are invalid.


  
Unfortunately, your theme PR does not adhere to our [theme guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution). Please fix the issues below, and we will review your  
 PR again. This pull request will **automatically close in 15 days** if no changes are made. After this time, you must re-open the PR for it to be reviewed.

      
      
## Details
      
        
### Catppuccin_latte theme preview
        
        
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=179299&bcolor=eff1f5).


        
title_color: <code>#179299</code> | icon_color: <code>#8839ef</code> | text_color: <code>#4c4f69</code> | bg_color: <code>#eff1f5</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=179299&icon_color=8839ef&text_color=4c4f69&bg_color=eff1f5&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=179299&icon_color=8839ef&text_color=4c4f69&bg_color=eff1f5&show_icons=true)
      
        
### Catppuccin_mocha theme preview
        
        

        
title_color: <code>#94e2d5</code> | icon_color: <code>#cba6f7</code> | text_color: <code>#cdd6f4</code> | bg_color: <code>#1e1e2e</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=94e2d5&icon_color=cba6f7&text_color=cdd6f4&bg_color=1e1e2e&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=94e2d5&icon_color=cba6f7&text_color=cdd6f4&bg_color=1e1e2e&show_icons=true)

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/2009#issuecomment-1264654988) comment above for more information.

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:x: Theme PR does not adhere to our guidelines.
      
## Test results
      
- :x: catppuccin_latte
- :heavy_check_mark: catppuccin_mocha

      
**Result:** :x: Some themes are invalid.


  
Unfortunately, your theme PR does not adhere to our [theme guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution). Please fix the issues below, and we will review your  
 PR again. This pull request will **automatically close in 15 days** if no changes are made. After this time, you must re-open the PR for it to be reviewed.

      
      
## Details
      
        
### Catppuccin_latte theme preview
        
        
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=179299&bcolor=eff1f5).


        
title_color: <code>#179299</code> | icon_color: <code>#8839ef</code> | text_color: <code>#4c4f69</code> | bg_color: <code>#eff1f5</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=179299&icon_color=8839ef&text_color=4c4f69&bg_color=eff1f5&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=179299&icon_color=8839ef&text_color=4c4f69&bg_color=eff1f5&show_icons=true)
      
        
### Catppuccin_mocha theme preview
        
        

        
title_color: <code>#94e2d5</code> | icon_color: <code>#cba6f7</code> | text_color: <code>#cdd6f4</code> | bg_color: <code>#1e1e2e</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=94e2d5&icon_color=cba6f7&text_color=cdd6f4&bg_color=1e1e2e&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=94e2d5&icon_color=cba6f7&text_color=cdd6f4&bg_color=1e1e2e&show_icons=true)

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/2009#issuecomment-1264655233) comment above for more information.

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:x: Theme PR does not adhere to our guidelines.
      
## Test results
      
- :x: catppuccin_latte
- :heavy_check_mark: catppuccin_mocha

      
**Result:** :x: Some themes are invalid.


  
Unfortunately, your theme PR does not adhere to our [theme guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution). Please fix the issues below, and we will review your  
 PR again. This pull request will **automatically close in 15 days** if no changes are made. After this time, you must re-open the PR for it to be reviewed.

      
      
## Details
      
        
### Catppuccin_latte theme preview
        
        
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=179299&bcolor=eff1f5).


        
title_color: <code>#179299</code> | icon_color: <code>#8839ef</code> | text_color: <code>#4c4f69</code> | bg_color: <code>#eff1f5</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=179299&icon_color=8839ef&text_color=4c4f69&bg_color=eff1f5&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=179299&icon_color=8839ef&text_color=4c4f69&bg_color=eff1f5&show_icons=true)
      
        
### Catppuccin_mocha theme preview
        
        

        
title_color: <code>#94e2d5</code> | icon_color: <code>#cba6f7</code> | text_color: <code>#cdd6f4</code> | bg_color: <code>#1e1e2e</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=94e2d5&icon_color=cba6f7&text_color=cdd6f4&bg_color=1e1e2e&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=94e2d5&icon_color=cba6f7&text_color=cdd6f4&bg_color=1e1e2e&show_icons=true)

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/2009#issuecomment-1264656190) comment above for more information.

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/2009#issuecomment-1264641342) comment above for more information.

**Comment by rickstaa** [comment]
This PR has been automatically closed due to inactivity. Please feel free to reopen it if you need to continue working on it.	
Thank you for your contributions.

**Comment by rickstaa** [comment]
@cosmojg Please fix the warnings above for your theme to get merged. I will increase the stale theme time to 30 days, by the way. Fifteen days is a bit aggressive. 😅

**Pull request closed without merging**
