### PR TITLE
feat: moonlight vscode dark theme

### PR DESCRIPTION
**Pull request by LucasAlexander13**
This is a Moonlight II theme based, using the theme palette for title, icons and background.

### CODE REVIEW

**Comment by anuraghazra** [comment]
**Automated Theme Preview**  
      
      

      
title_color: <code>#FF757F</code> | icon_color: <code>#599DFF</code> | text_color: <code>#F8F8F8</code> | bg_color: <code>#222436</code>
      
      
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FF757F&icon_color=599DFF&text_color=F8F8F8&bg_color=222436&show_icons=true)

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FF757F&icon_color=599DFF&text_color=F8F8F8&bg_color=222436&show_icons=true)
      
      
  
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).  
  
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

**Comment by LucasAlexander13** [comment]
@anuraghazra This is how the theme looks like
image

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: moonlight

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Moonlight theme preview
        
        

        
title_color: <code>#FF757F</code> | icon_color: <code>#599DFF</code> | text_color: <code>#F8F8F8</code> | bg_color: <code>#222436</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FF757F&icon_color=599DFF&text_color=F8F8F8&bg_color=222436&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FF757F&icon_color=599DFF&text_color=F8F8F8&bg_color=222436&show_icons=true)

**Review by rickstaa — APPROVED** [review]

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: moonlight

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Moonlight theme preview
        
        

        
title_color: <code>#FF757F</code> | icon_color: <code>#599DFF</code> | text_color: <code>#F8F8F8</code> | bg_color: <code>#222436</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FF757F&icon_color=599DFF&text_color=F8F8F8&bg_color=222436&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FF757F&icon_color=599DFF&text_color=F8F8F8&bg_color=222436&show_icons=true)

**Review by rickstaa — APPROVED** [review]

**Review by rickstaa — APPROVED** [review]

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: moonlight

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Moonlight theme preview
        
        

        
title_color: <code>#FF757F</code> | icon_color: <code>#599DFF</code> | text_color: <code>#F8F8F8</code> | bg_color: <code>#222436</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FF757F&icon_color=599DFF&text_color=F8F8F8&bg_color=222436&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FF757F&icon_color=599DFF&text_color=F8F8F8&bg_color=222436&show_icons=true)

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: moonlight

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Moonlight theme preview
        
        

        
title_color: <code>#FF757F</code> | icon_color: <code>#599DFF</code> | text_color: <code>#F8F8F8</code> | bg_color: <code>#222436</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FF757F&icon_color=599DFF&text_color=F8F8F8&bg_color=222436&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FF757F&icon_color=599DFF&text_color=F8F8F8&bg_color=222436&show_icons=true)

**Review by rickstaa — APPROVED** [review]

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: moonlight

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Moonlight theme preview
        
        

        
title_color: <code>#FF757F</code> | icon_color: <code>#599DFF</code> | text_color: <code>#F8F8F8</code> | bg_color: <code>#222436</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FF757F&icon_color=599DFF&text_color=F8F8F8&bg_color=222436&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FF757F&icon_color=599DFF&text_color=F8F8F8&bg_color=222436&show_icons=true)

**Review by rickstaa — APPROVED** [review]

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: moonlight

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Moonlight theme preview
        
        

        
title_color: <code>#FF757F</code> | icon_color: <code>#599DFF</code> | text_color: <code>#F8F8F8</code> | bg_color: <code>#222436</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FF757F&icon_color=599DFF&text_color=F8F8F8&bg_color=222436&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FF757F&icon_color=599DFF&text_color=F8F8F8&bg_color=222436&show_icons=true)

**Review by rickstaa — APPROVED** [review]

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: moonlight

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Moonlight theme preview
        
        

        
title_color: <code>#FF757F</code> | icon_color: <code>#599DFF</code> | text_color: <code>#F8F8F8</code> | bg_color: <code>#222436</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FF757F&icon_color=599DFF&text_color=F8F8F8&bg_color=222436&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FF757F&icon_color=599DFF&text_color=F8F8F8&bg_color=222436&show_icons=true)

**Review by rickstaa — APPROVED** [review]

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: moonlight

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Moonlight theme preview
        
        

        
title_color: <code>#FF757F</code> | icon_color: <code>#599DFF</code> | text_color: <code>#F8F8F8</code> | bg_color: <code>#222436</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FF757F&icon_color=599DFF&text_color=F8F8F8&bg_color=222436&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FF757F&icon_color=599DFF&text_color=F8F8F8&bg_color=222436&show_icons=true)

**Review by rickstaa — APPROVED** [review]

**Review by rickstaa — APPROVED** [review]

**Comment by LucasAlexander13** [comment]
@rickstaa thanks for approving, let me know if I need to make any changes.

**Comment by anuraghazra** [comment]
We are currently pausing addition of new themes. If this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

**Pull request closed without merging**
