### PR TITLE
fix: firefox layout breaking

### PR DESCRIPTION
**Pull request by anuraghazra**
fixes #45

### CODE REVIEW

**Comment by anuraghazra** [comment]
@saurabhdaware can you check the updates?

here's live development preview

**Comment by cjdenio** [comment]
It's definitely better, but still a bit off.

image

**Comment by anuraghazra** [comment]
@cjdenio Yes i checked it, i have no idea why tho, its working fine locally. ff has lot of issues with SVGs :weary: weird

**Comment by cjdenio** [comment]
Weird, it works perfectly when icons are turned on.
image

**Comment by anuraghazra** [comment]
Huh! very weird

**Comment by anuraghazra** [comment]
Oh got it, for some reason user-agent isn't recognized

**Comment by saurabhdaware** [comment]
Yes I have same output as @cjdenio

**Comment by anuraghazra** [comment]
Ahh got it, the problem is that in the request headers i'm getting `github-camo` instead of `firefox's ua` which makes sense because the API is hit from server not directly from browser, any ideas to fix this? @saurabhdaware @cjdenio

**Comment by saurabhdaware** [comment]
Can we fix that on frontend? https://stackoverflow.com/questions/5378559/including-javascript-in-svg

**Comment by anuraghazra** [comment]
Not that easy i assume, the SVGs wont gonna be rendered as SVG or pure HTML elements by github, github will automatically upload the svg to their camo.githubusercontent cdn and then render that as image.

**Comment by saurabhdaware** [comment]
ahh yes right

**Comment by anuraghazra** [comment]
@saurabhdaware can you check again it should be fixed :D

**Comment by cjdenio** [comment]
image

Looks perfect!

**Comment by anuraghazra** [comment]
Awesome! thanks @cjdenio

**Comment by saurabhdaware** [comment]
uh oh I turned off my laptop and sleeping now :( so probably by tomorrow morning

**Comment by anuraghazra** [comment]
No issues @saurabhdaware @cjdenio sent the screenshot its working fine now, thanks for helping out, and reporting the bug. :heart:

**Pull request merged**
