### PR TITLE
Add issues and pull request counter to pin card

### PR DESCRIPTION
**Pull request by guibranco**
Closes the #2486

### CODE REVIEW

**Comment by rickstaa** [comment]
Great pull request! 🔥I will look at it later. There are, however, two things that still need to be added:
- [ ] The new options need to be added to the documentation -> https://github.com/anuraghazra/github-readme-stats#repo-card-exclusive-options.
- [ ] Tests need to be added for the new options in https://github.com/anuraghazra/github-readme-stats/blob/112000667c01f18fd161f204ae3ee796ec2e3011/tests/renderRepoCard.test.js#L45-L52.

**Comment by guibranco** [comment]
If the answer for the previous question is `yes` should I also add options to `stargazers` and `forks` ?

**Comment by rickstaa** [comment]
> The issues count and pull requests count are not an option, they are fixed. Do you prefer to add as optional ?

Given that these cards are based on GitHub's original pins, and these don't have these stats I think making them optional makes more sense. 👍

image

**Comment by rickstaa** [comment]
> If the answer to the previous question is `yes`, should I add options to `stargazers` and `forks`?

Forks and stargazers are on the original pin. So they can stay enabled by default but you can give people the option to disable them. 👍 @anuraghazra What do you think?

**Comment by guibranco** [comment]
Sure, I'll work on it!

**Comment by guibranco** [comment]
@rickstaa doc updated and also added the options to tests

**Review by rickstaa — APPROVED** [review]
Looks good to me. Thanks a lot for the PR.

**Comment by rickstaa** [comment]
@Zo-Bro-23 what do you think?

**Comment by Zo-Bro-23** [comment]
Thanks a lot for the PR! Most of it looks good to me. I'm not very familiar with SVG, however, so could you please include a screenshot or a live image to show me how it looks? Could you also please share the URL of a Vercel instance with the updated code so that I can test a few things out before merging? Thanks!

**Comment by guibranco** [comment]
@Zo-Bro-23 

All data: 
Stats

Default:
Stats

Hidding stars and forks, and showing issues and pull requests:
Stats

You can check a live deployed version of this PR here: [https://github-readme-stats-guibranco.vercel.app/api/pin/](https://github-readme-stats-guibranco.vercel.app/api/pin/)

**Comment by rickstaa** [comment]
@Zo-Bro-23 you can merge this if you want. LGTM 👍🏻.

**Comment by Zo-Bro-23** [comment]
Hi @guibranco, would you be able to make the requested changes? If not, I can perhaps do those changes myself, or merge without them (they're not very high-priority). Let me know if you're willing to work on those!

**Comment by guibranco** [comment]
I can do it, but this week I'm out vacationing, maybe next week, WDYT ?

**Comment by Zo-Bro-23** [comment]
> I can do it, but this week I'm out vacationing, maybe next week, WDYT ?

No problem; just wanted to know if you were planning to do it. Feel free to take your time; this is an OS project after all 🦄

**Comment by Zo-Bro-23** [comment]
@guibranco this is a great PR. Do you want me to merge it as is? It's fine if you're planning to work on it and incorporate the changes I suggested, but merging now is fine too if you don't want to spend too much time on this. I can incorporate those changes myself too. Let me know what you think!

**Comment by rickstaa** [comment]
> @guibranco this is a great PR. Do you want me to merge it as is? It's fine if you're planning to work on it and incorporate the changes I suggested, but merging now is fine too if you don't want to spend too much time on this. I can incorporate those changes myself too. Let me know what you think!

@Zo-Bro-23 I agree with your suggestions. If you apply them I am happy to review this PR again. 👍🏻

**Comment by guibranco** [comment]
You can merge now and then I can submit a new PR with the other changes, I'm still on vacation, sorry guys

**Comment by rickstaa** [comment]
> You can merge now and then I can submit a new PR with the other changes, I'm still on vacation, sorry guys

There is no hurry in open source 🌈. Enjoy your holiday. @Zo-Bro-23 if you want it merged earlier feel free to commit changes and I will review. 👍🏻

**Comment by guibranco** [comment]
I'll work on this PR this week guys!

**Review by Kesanli13 — COMMENTED** [review]
guibranco:master

**Comment by rickstaa** [comment]
@guibranco, did something go wrong while rebasing this pull request 🤔? I still think it's a nice feature to have 👍🏻.

**Comment by guibranco** [comment]
@rickstaa I needed to sync the repository and had to discard the commits I had made. I will update now and open a new PR.

**Pull request closed without merging**
