### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by mohamedation**
added give.do logo

### CODE REVIEW

**Comment by rickstaa** [comment]
@mohamedation  Thanks for your PR. I, however, don't think this is needed since the image is shown using the current URL. I think it is simply protected against direct access in the browser.

<a href="https://indiafightscorona.giveindia.org">
Give india logo
</a>

```html
<a href="https://indiafightscorona.giveindia.org">
<img src="https://d2wvdrxmr8p0wf.cloudfront.net/static/giveindia.svg" alt="Give India logo" width="200" />
</a>
```

**Comment by mohamedation** [comment]
@rickstaa oh,my mistake then. It's not showing for me and I thought it's an issue.
Sorry for the inconvenience.

**Comment by rickstaa** [comment]
@mohamedation Oh in that case maybe mine is showing because it is cached.

**Comment by rickstaa** [comment]
Thanks for letting me know I fixed it with an earlier PR https://github.com/anuraghazra/github-readme-stats/pull/2085.

**Comment by rickstaa** [comment]
@mohamedation Looks like your logo is not transparent. 

image

Do you know where we can find a transparent version of the logo?

**Pull request closed without merging**
