### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by anantsaini222**
Added new theme called "Lavender"

### CODE REVIEW

**Comment by anuraghazra** [comment]
**Automated Theme preview**
        
        
Cannot create theme preview

        
  
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).  
  
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

**Comment by anantsaini222** [comment]
If the preview if working and have made this theme using VScode , then Vercel authorization is not successfull??

**Comment by anuraghazra** [comment]
Hi @anantsaini222 sorry but we currently only accept official vscode themes which can be downloaded from the vscode marketplace.

**Comment by rickstaa** [comment]
You appear to be changing an existing theme. Can you please specify why you want that theme to change?

**Pull request closed without merging**
