### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by Genderfluid**
Just a theme...

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title-color: <code>#ff0000</code>
      
icon-color: <code>#ff0000</code>
      
text-color: <code>#ff0000</code>
      
bg-color: <code>#0000000</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ff0000&icon_color=ff0000&text_color=ff0000&bg_color=0000000&show_icons=true)

**Comment by AshenRed1** [comment]
switch bg_color to 0000001

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title-color: <code>#ff0000</code>
      
icon-color: <code>#ff0000</code>
      
text-color: <code>#ff0000</code>
      
bg-color: <code>#0000000</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ff0000&icon_color=ff0000&text_color=ff0000&bg_color=0000000&show_icons=true)

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title-color: <code>#ff0000</code>
      
icon-color: <code>#ff0000</code>
      
text-color: <code>#ff0000</code>
      
bg-color: <code>#0000001</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ff0000&icon_color=ff0000&text_color=ff0000&bg_color=0000001&show_icons=true)

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title-color: <code>#ff0000</code>
      
icon-color: <code>#ff0000</code>
      
text-color: <code>#ff0000</code>
      
bg-color: <code>#0000001</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ff0000&icon_color=ff0000&text_color=ff0000&bg_color=0000001&show_icons=true)

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title-color: <code>#ff0000</code>
      
icon-color: <code>#ff0000</code>
      
text-color: <code>#ff0000</code>
      
bg-color: <code>#000000</code>
      
      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ff0000&icon_color=ff0000&text_color=ff0000&bg_color=000000&show_icons=true)

**Comment by AshenRed1** [comment]
fixed because i cannot count number of digits

**Pull request closed without merging**
