### PR TITLE
Noctis minimus

### PR DESCRIPTION
**Pull request by Anant-mishra1729**
Github stats

### CODE REVIEW

**Comment by anuraghazra** [comment]
**Automated Theme preview**  
      
      
title_color: <code>#d3b692</code> | icon_color: <code>#72b7c0</code> | text_color: <code>#c5cdd3</code> | bg_color: <code>#1b2932</code>
      
      
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=d3b692&icon_color=72b7c0&text_color=c5cdd3&bg_color=1b2932&show_icons=true)

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=d3b692&icon_color=72b7c0&text_color=c5cdd3&bg_color=1b2932&show_icons=true)
      
      
  
Hi thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).  
  
We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

**Comment by anuraghazra** [comment]
Hi @Anant-mishra1729 color combinations looks great but is this a vscode theme?

**Comment by Anant-mishra1729** [comment]
> Hi @Anant-mishra1729 color combinations looks great but is this a vscode theme?

Thanks for replying @anuraghazra
Yes, Noctis minimus is a Vs-code theme 
Here is the link for it's repo [Noctis Minimus](https://github.com/liviuschera/noctis)

**Comment by anuraghazra** [comment]
Looks great awesome! thanks for the PR @Anant-mishra1729 

Happy hacktoberfest :heart:

**Comment by anuraghazra** [comment]
**Automated Theme preview**  
      
      
title_color: <code>#d3b692</code> | icon_color: <code>#72b7c0</code> | text_color: <code>#c5cdd3</code> | bg_color: <code>#1b2932</code>
      
      
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=d3b692&icon_color=72b7c0&text_color=c5cdd3&bg_color=1b2932&show_icons=true)

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=d3b692&icon_color=72b7c0&text_color=c5cdd3&bg_color=1b2932&show_icons=true)
      
      
  
Hi thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).  
  
We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

**Pull request merged**
