### PR TITLE
Custom title and name (#229)

### PR DESCRIPTION
**Pull request by nthnchu**
Adds ability for a custom title (Fixes #229)

### CODE REVIEW

**Comment by nthnchu** [comment]
Live Demo
https://github-readme-stats-custom-stats-title.nthnchu.vercel.app/api?username=anuraghazra&custom_title=Custom%20Title
Custom Title

**Comment by nthnchu** [comment]
Live demo of Custom Name
https://github-readme-stats-custom-stats-title.nthnchu.vercel.app/api?username=anuraghazra&custom_title=Custom%20Name
Custom Name's Github Stats

**Comment by ngtrhieu** [comment]
Hi @nthnchu your demo seems to be broken?

**Comment by nthnchu** [comment]
> Hi @nthnchu your demo seems to be broken?

@ngtrhieu just fixed it. I forgot to redeploy to Vercel. :D

**Comment by nthnchu** [comment]
> > Hi @nthnchu your demo seems to be broken?
> 
> @ngtrhieu just fixed it. I forgot to redeploy to Vercel. :D

Fixed it again. I have two branches that I'm working on, and Vercel is getting them confused for some reason...

**Comment by anuraghazra** [comment]
Hi @nthnchu thanks for the PR, sorry for late response.

Btw as of #266 we refactored the common logic to a new Card.js class, i think let's close this PR and open a new one that would be less messier. 

And we don't need to support login name and custom title, we would only support a query `custom_title`

**Comment by nthnchu** [comment]
> Btw as of #266 we refactored the common logic to a new Card.js class, i think let's close this PR and open a new one that would be less messier.

Yeah I was going to resolve the conflict but GitHub says that the conflict is too complex to resolve in the web editor, so a new PR might be easier...

> And we don't need to support login name and custom title, we would only support a query custom_title

Ok, wasn't sure what you wanted, so I just did both.

**Comment by nthnchu** [comment]
#293 is the new PR

**Pull request closed without merging**
