### PR TITLE
new themes

### PR DESCRIPTION
**Pull request by parebrike**
github_darkgray theme:

dark_contrast theme:

### CODE REVIEW

**Comment by anuraghazra** [comment]
**Automated Theme Preview**  
      
      

      
title_color: <code>#cbcbcb</code> | icon_color: <code>#ffffff</code> | text_color: <code>#cbcbcb</code> | bg_color: <code>#0D1117</code>
      
      
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=cbcbcb&icon_color=ffffff&text_color=cbcbcb&bg_color=0D1117&border_color=959595&show_icons=true)

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=cbcbcb&icon_color=ffffff&text_color=cbcbcb&bg_color=0D1117&border_color=959595&show_icons=true)
      
      
  
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).  
  
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

**Comment by rickstaa** [comment]
@lightybeam Thanks for your contribution. I agree with you that the GitHub themes should be included. One question. Is the `github_darkgray` theme referring to the `dark_dimmed` GitHub theme and the `high_contrast` theme to the Github `dark_high_contrast` theme?

**Comment by lightybeam** [comment]
@rickstaa I made these themes to my taste, i didn't watch other styles of themes besides `github_dark` and made it more lighter.`dark_contrast` is referring to another themes only by its "dark" part of name.

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: github_darkgray
- :heavy_check_mark: dark_contrast

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Github_darkgray theme preview
        
        

        
title_color: <code>#cbcbcb</code> | icon_color: <code>#ffffff</code> | text_color: <code>#cbcbcb</code> | bg_color: <code>#0D1117</code> | border_color: <code>#959595</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=cbcbcb&icon_color=ffffff&text_color=cbcbcb&bg_color=0D1117&border_color=959595&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=cbcbcb&icon_color=ffffff&text_color=cbcbcb&bg_color=0D1117&border_color=959595&show_icons=true)
      
        
### Dark_contrast theme preview
        
        

        
title_color: <code>#ffffff</code> | icon_color: <code>#ffffff</code> | text_color: <code>#ffffff</code> | bg_color: <code>#000000</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ffffff&icon_color=ffffff&text_color=ffffff&bg_color=000000&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ffffff&icon_color=ffffff&text_color=ffffff&bg_color=000000&show_icons=true)

**Review by rickstaa — APPROVED** [review]

**Review by rickstaa — APPROVED** [review]

**Comment by anuraghazra** [comment]
We are currently pausing addition of new themes. If this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

**Pull request closed without merging**
