### PR TITLE
feature: extend default card cache time to 6 hours

### PR DESCRIPTION
**Pull request by qwerty541**
Related to https://github.com/anuraghazra/github-readme-stats/issues/1471#issuecomment-1714503380

### CODE REVIEW

**Comment by rickstaa** [comment]
@qwerty541 It Looks like pat 7 and 8 were suspended (see https://github-readme-stats.vercel.app/api/status/pat-info). I sent @anuraghazra two new pats to solve this 👍🏻. I think when those are added we will be good for a while.

**Comment by anuraghazra** [comment]
8hs seems a bit excessive let's try 6h first. Otherwise we will again have issues like "Cards are not updating"

**Review by qwerty541 — COMMENTED** [review]
> 8hs seems a bit excessive let's try 6h first. Otherwise we will again have issues like "Cards are not updating"

Ok, i reduced it to 6, this pull request also contains documentation improvements. It explains our caching mechanism and suggest to deploy own instance if user want his card to be updated more often. I hope it will reduce count of potential "Cards are not updating" issues/discussions.

**Comment by qwerty541** [comment]
> @qwerty541 It Looks like pat 7 and 8 were suspended (see https://github-readme-stats.vercel.app/api/status/pat-info). I sent @anuraghazra two new pats to solve this 👍🏻. When those are added, we will be good for a while.

@rickstaa Nice, but anyway i think it will be better to reduce load from public instance for future. Sooner or later other PATs will be suspended too.

**Review by rickstaa — APPROVED** [review]

**Pull request merged**
