### PR TITLE
to contribute a new theme "for-dark-or-light-any-theme"

### PR DESCRIPTION
**Pull request by NoushadBug**
want to add this theme "for-dark-or-light-any-theme" as many people face a bit of irritating when GitHub theme does not fit and seems adaptive with cards. I made this so that, it can be used in any theme of GitHub and it will be fit in.

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title_color: <code>#FA8C00</code> | icon_color: <code>#CC5160</code> | text_color: <code>#949CA5</code> | bg_color: <code>#00000000</code>
      
      
Link: https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FA8C00&icon_color=CC5160&text_color=949CA5&bg_color=00000000&show_icons=true

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FA8C00&icon_color=CC5160&text_color=949CA5&bg_color=00000000&show_icons=true)
      
      
  
> Hi thanks for the theme contribution, please read our theme contribution guidelines

  
> We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 
  
> Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

**Comment by NoushadBug** [comment]
I want a help on naming the theme, I want it clear to understand so that while selecting a theme people may understand that this theme is adaptive on any theme. If you have any better choice on this theme name, you can suggest.

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1113#issuecomment-1264669401) comment above for more information.

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:x: Theme PR does not adhere to our guidelines.
      
## Test results
      
- :x: for-dark-or-light-any-theme

      
**Result:** :x: Some themes are invalid.


  
Unfortunately, your theme PR does not adhere to our [theme guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution). Please fix the issues below, and we will review your  
 PR again. This pull request will **automatically close in 15 days** if no changes are made. After this time, you must re-open the PR for it to be reviewed.

      
      
## Details
      
        
### For-dark-or-light-any-theme theme preview
        
        
- :warning: Theme name isn't in snake_case.


        
title_color: <code>#FA8C00</code> | icon_color: <code>#CC5160</code> | text_color: <code>#949CA5</code> | bg_color: <code>#00000000</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FA8C00&icon_color=CC5160&text_color=949CA5&bg_color=00000000&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FA8C00&icon_color=CC5160&text_color=949CA5&bg_color=00000000&show_icons=true)

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1113#issuecomment-1264669401) comment above for more information.

**Comment by rickstaa** [comment]
This PR has been automatically closed due to inactivity. Please feel free to reopen it if you need to continue working on it.	
Thank you for your contributions.

**Pull request closed without merging**
