### PR TITLE
Add catppuccin theme

### PR DESCRIPTION
**Pull request by alexanderdvorkin**

### CODE REVIEW

**Comment by anuraghazra** [comment]
**Automated Theme Preview**  
      
      

      
title_color: <code>#F5E0DC</code> | icon_color: <code>#DDB6F2</code> | text_color: <code>#D9E0EE</code> | bg_color: <code>#161320</code>
      
      
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=F5E0DC&icon_color=DDB6F2&text_color=D9E0EE&bg_color=161320&border_color=F5E0DC&show_icons=true)

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=F5E0DC&icon_color=DDB6F2&text_color=D9E0EE&bg_color=161320&border_color=F5E0DC&show_icons=true)
      
      
  
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).  
  
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

**Comment by ayamir** [comment]
`catppuccin` has vscode port: https://github.com/catppuccin/vscode
even github port: https://github.com/catppuccin/github
Here is overall effect(with another bg_color=1E1E2E): 
image

**Comment by anuraghazra** [comment]
> 1E1E2E

this one looks better

**Comment by alexnkeys** [comment]
@anuraghazra

**Comment by alexanderdvorkin** [comment]
Seeing that an official one has been created (https://github.com/catppuccin/github-readme-stats), I will be closing this pull request.

**Pull request closed without merging**
