### PR TITLE
CI: dependencies pinned by hashes

### PR DESCRIPTION
**Pull request by qwerty541**
Related to #2914

### CODE REVIEW

**Comment by rickstaa** [comment]
Does this work with dependabot? I quickly checked the documentation, but I could not see if this is the case (see https://github.blog/2020-06-25-dependabot-now-updates-your-actions-workflows/ and https://github.com/dependabot/dependabot-core/issues/4691) 🤔.

**Review by qwerty541 — COMMENTED** [review]
> Does this work with dependabot? I quickly checked the documentation, but I could not see if this is the case (see https://github.blog/2020-06-25-dependabot-now-updates-your-actions-workflows/ and [dependabot/dependabot-core#4691](https://github.com/dependabot/dependabot-core/issues/4691)) thinking.

I have found an example of PR created by dependabot with updating hashed dependency. See: https://github.com/nextcloud/android-common/pull/35

But we have to keep human-friendly version comment up-to-date manually.

Also i want to notice that i'm not sure if dependabot updates for github actions enable for this repository since i have never seen them and we don't have `dependabot.yml` clearly configured. I you are ok to merge it, i will created PR with dependabot config addition.

**Comment by rickstaa** [comment]
> > Does this work with dependabot? I quickly checked the documentation, but I could not see if this is the case (see https://github.blog/2020-06-25-dependabot-now-updates-your-actions-workflows/ and [dependabot/dependabot-core#4691](https://github.com/dependabot/dependabot-core/issues/4691)) thinking.
> 
> I have found an example of PR created by dependabot with updating hashed dependency. See: [nextcloud/android-common#35](https://github.com/nextcloud/android-common/pull/35)
> 
> But we have to keep human-friendly version comment up-to-date manually.
> 
> Also i want to notice that i'm not sure if dependabot updates for github actions enable for this repository since i have never seen them and we don't have `dependabot.yml` clearly configured. I you are ok to merge it, i will created PR with dependabot config addition.

From https://github.com/dependabot/dependabot-core/issues/4691, I already suspected Dependabot-supported hashes, but thanks for giving an example where it shows the support 🚀. According to https://github.com/dependabot/dependabot-core/issues/4691, Dependabot should automatically update the human-readable comments when they are in the correct format:

```yml
      - uses: actions/stale@6f05e4244c9a0b2ed3401882b05d701dd0a7289b # v7.0.0
```

Having Dependabot enabled would be nice when we switch to hashes. Feel free to open a pull request for me to merge with the correct configuration. If you add the right version comments to this pull request I will merge it 👍🏻!

**Comment by rickstaa** [comment]
@qwerty541 looks like you already did! Let's merge this pull request.

**Review by rickstaa — APPROVED** [review]

**Pull request merged**
