### PR TITLE
Add Eslint infra (#200)

### PR DESCRIPTION
**Pull request by maddyb99**
I think this should check one box for this issue!!
Will try to cover more as and when I get time :smile:

### CODE REVIEW

**Comment by anuraghazra** [comment]
Hi @maddyb99 thanks for the PR, but in https://github.com/anuraghazra/github-readme-stats/issues/200#issuecomment-663989910 we are talking about adding esling and associate infra to format code not manual formating of code.

**Comment by maddyb99** [comment]
So, you mean an Eslint config that autformats on save or something?

**Comment by anuraghazra** [comment]
@maddyb99 yeah and also with husky precommit hook

**Comment by maddyb99** [comment]
OK! @anuraghazra will try to do that, so keeping this PR open for now

**Comment by maddyb99** [comment]
There are some issues with styles right now as the linter wants camel case but most places the codebase is using underscore separated words.
Also, I'll test it with husky hook also once locally!

**Comment by maddyb99** [comment]
@anuraghazra is there any specific style being followed here or that has to be decided with the infrastructure being set?

**Pull request closed without merging**
