### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by pixel-alex**

### CODE REVIEW

**Comment by anuraghazra** [comment]
**Automated Theme preview**  
      
      
title_color: <code>#e84a26</code> | icon_color: <code>#ffffff</code> | text_color: <code>#ffffff</code> | bg_color: <code>#DEG</code>
      
      
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=e84a26&icon_color=ffffff&text_color=ffffff&bg_color=DEG&show_icons=true)

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=e84a26&icon_color=ffffff&text_color=ffffff&bg_color=DEG&show_icons=true)
      
      
  
Hi thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).  
  
We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:x: Theme PR does not adhere to our guidelines.
      
## Test results
      
- :x: fancy

      
**Result:** :x: Some themes are invalid.


  
Unfortunately, your theme PR does not adhere to our [theme guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution). Please fix the issues below, and we will review your  
 PR again. This pull request will **automatically close in 15 days** if no changes are made. After this time, you must re-open the PR for it to be reviewed.

      
      
## Details
      
          
### Fancy theme preview
          
          
          
- :x: Theme color property `bg_color` is not a valid hex color: <code>#DEG,3484bf,214476,182c49</code>.


          
>:x: Cannot create theme preview.

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1331#issuecomment-1264658505) comment above for more information.

**Review by rickstaa — CHANGES_REQUESTED** [review]
Some themes are invalid. See the [Automated Theme Preview](https://github.com/anuraghazra/github-readme-stats/pull/1331#issuecomment-1264658505) comment above for more information.

**Comment by rickstaa** [comment]
This PR has been automatically closed due to inactivity. Please feel free to reopen it if you need to continue working on it.	
Thank you for your contributions.

**Pull request closed without merging**
