### PR TITLE
style(theme): Add monokai theme

### PR DESCRIPTION
**Pull request by gopla**
Hi, I added monokai-like theme .
It looks like this
image

### CODE REVIEW

**Comment by anuraghazra** [comment]
Hi @gopla thanks for the theme contribution.

But the colors does not seem to be match the monokai theme, the primary colors of monokai is the white text, orange tokens, and red statements. like this

```
&bg_color=272822
&text_color=f1f1eb
&title_color=eb1f6a
&icon_color=e28905
```

**Comment by gopla** [comment]
Ah, i see
I'll change the color palette asap

**Comment by anuraghazra** [comment]
@gopla can you please fix the conflict.

**Comment by anuraghazra** [comment]
@gopla Sorry for late response.

Thanks for the PR. Looks good.

**Pull request merged**
