### PR TITLE
Add neon_blurange theme

### PR DESCRIPTION
**Pull request by adiati98**
## Description

- I have read the [Themes Contribution Section](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution) in the `CONTRIBUTION.md`.
- This theme has passed the AA contrast ratio.
- This theme is not one of the color combinations of any VS Code themes. However, I would love to be given a chance to contribute this theme to your repo. Many thanks for considering my request 😊

## Screenshot
neon_blurange theme

### CODE REVIEW

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: neon_blurange

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Neon_blurange theme preview
        
        

        
title_color: <code>#FB750B</code> | icon_color: <code>#25FB88</code> | text_color: <code>#C7CCFF</code> | bg_color: <code>#030D6B</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FB750B&icon_color=25FB88&text_color=C7CCFF&bg_color=030D6B&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FB750B&icon_color=25FB88&text_color=C7CCFF&bg_color=030D6B&show_icons=true)

**Review by rickstaa — APPROVED** [review]

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: neon_blurange

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Neon_blurange theme preview
        
        

        
title_color: <code>#FB750B</code> | icon_color: <code>#25FB88</code> | text_color: <code>#C7CCFF</code> | bg_color: <code>#030D6B</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FB750B&icon_color=25FB88&text_color=C7CCFF&bg_color=030D6B&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=FB750B&icon_color=25FB88&text_color=C7CCFF&bg_color=030D6B&show_icons=true)

**Review by rickstaa — APPROVED** [review]

**Review by rickstaa — APPROVED** [review]

**Comment by adiati98** [comment]
Hi @rickstaa,
Thank you for approving the changes!

Is there anything else I should do to get this PR merged?
Thanks 😊

**Comment by rickstaa** [comment]
@adiati98 No, the theme request is good to be merged. I, however, can not promise that the theme will be added. We have 50 valid theme PR requests we still haven't looked at (see https://github.com/anuraghazra/github-readme-stats/pulls?q=is%3Aopen+is%3Apr+label%3Athemes+-label%3Ainvalid+). We are therefore currently only merging the ones that receive multiple upvotes, are distinct enough from the themes we already have or are based on prevalent Vscode themes.

**Comment by adiati98** [comment]
@rickstaa
Oh, okay. Thank you so much for the explanation 😄

**Comment by anuraghazra** [comment]
We are currently pausing addition of new themes. If this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

**Pull request closed without merging**
