### PR TITLE
add primary lang logo in stats

### PR DESCRIPTION
**Pull request by rjoydip**
Ref: #257  

All icons are collected from [Devicons API](https://devicons.github.io/devicon/devicon.git/icons/{LANG_NAME}/{LANG_NAME}-original.svg)

/cc @anuraghazra

## Flags

- **hide_plang** - **Default: false**

## Screenshot

image

## Languages covered

- [X] C
- [X] C++
- [X] C#
- [X] Coffeescript
- [X] CSS
- [X] Elm
- [X] Erlang
- [X] Go
- [X] Groovy
- [X] HTML
- [X] Java 
- [X] JavaScript
- [X] PHP
- [X] Python
- [X] Ruby
- [X] Rust
- [X] Scala
- [X] Swift
- [X] Typescript

### CODE REVIEW

**Comment by anuraghazra** [comment]
@rjoydip add a screenshot

**Comment by rjoydip** [comment]
Yes, please check description. I've modified.

**Comment by anuraghazra** [comment]
Need to make them smaller, and set max number of languages to 8/10.

Also i've a better proposal for loading the icons. there is no way we can cover all the language's icons & it will make the codebase unneccerasily large if we have all the svgs in our file system, instead we can use devicon's api to fetch the svgs and load the icons dynamically. 

for example we will directly fetch the svg like so :-


For golang:
```
https://devicons.github.io/devicon/devicon.git/icons/go/go-original.svg
```

Typescript: 

```
https://devicons.github.io/devicon/devicon.git/icons/typescript/typescript-original.svg
```


The format is `https://devicons.github.io/devicon/devicon.git/icons/{LANG NAME}/{LANG NAME}-original.svg`

**Comment by rjoydip** [comment]
@anuraghazra Done. All languages are fetched using devicons API. If there no logo matched with language name it will show `github` icon as default.

**Comment by NightYoshi370** [comment]
If possible, could you update this PR to not contain merge conflicts?

**Pull request closed without merging**
