### PR TITLE
New Theme

### PR DESCRIPTION
**Pull request by lncoognito**
Clean Dark.

### CODE REVIEW

**Comment by lncoognito** [comment]
> Clean Dark.

https://i.imgur.com/taKgjyI.png

**Comment by lncoognito** [comment]
> Clean Dark.

image

**Review by rickstaa — APPROVED** [review]

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: clean_dark

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Clean_dark theme preview
        
        

        
title_color: <code>#ffffff</code> | icon_color: <code>#3388ff</code> | text_color: <code>#ffffff</code> | bg_color: <code>#0f0f0f</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ffffff&icon_color=3388ff&text_color=ffffff&bg_color=0f0f0f&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ffffff&icon_color=3388ff&text_color=ffffff&bg_color=0f0f0f&show_icons=true)

**Comment by rickstaa** [comment]
# Automated Theme Preview
      
  
Hi, thanks for the theme contribution. Please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).
  
We are currently only accepting color combinations from any VSCode theme or themes with good colour combinations to minimize bloating the themes collection.

  
> Also, note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection, you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization).

    
      
:heavy_check_mark: Theme PR does adhere to our guidelines.
      
## Test results
      
- :heavy_check_mark: clean_dark

      
**Result:** :heavy_check_mark: All themes are valid.
      
      
## Details
      
        
### Clean_dark theme preview
        
        

        
title_color: <code>#ffffff</code> | icon_color: <code>#3388ff</code> | text_color: <code>#ffffff</code> | bg_color: <code>#0f0f0f</code>

        
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ffffff&icon_color=3388ff&text_color=ffffff&bg_color=0f0f0f&show_icons=true)

        
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=ffffff&icon_color=3388ff&text_color=ffffff&bg_color=0f0f0f&show_icons=true)

**Review by rickstaa — APPROVED** [review]

**Review by rickstaa — APPROVED** [review]

**Pull request closed without merging**
