### PR TITLE
Added "full_green" color

### PR DESCRIPTION
**Pull request by Cased-vsc**

### CODE REVIEW

**Comment by anuraghazra** [comment]
**Automated Theme Preview**  
      
      
- :warning: `title_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=1DB10D&bcolor=1DB10D)
- :warning: `icon_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=1DB10D&bcolor=1DB10D)
- :warning: `text_color` does not pass [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=1DB10D&bcolor=1DB10D)


      
title_color: <code>#1DB10D</code> | icon_color: <code>#1DB10D</code> | text_color: <code>#1DB10D</code> | bg_color: <code>#1DB10D</code>
      
      
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=1DB10D&icon_color=1DB10D&text_color=1DB10D&bg_color=1DB10D&show_icons=true)

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=1DB10D&icon_color=1DB10D&text_color=1DB10D&bg_color=1DB10D&show_icons=true)
      
      
  
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).  
  
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

**Comment by Cased-vsc** [comment]
Hmph, alright.. I'll make a better one and read the guidelines, thanks. 😃

**Comment by Cased-vsc** [comment]
You can close the pull request if you want!

**Comment by Cased-vsc** [comment]
I just created another one and it passed the AA contrast ratio, will upload it on a new PR

**Pull request closed without merging**
