### PR TITLE
Add option to deploy using other services

### PR DESCRIPTION
**Pull request by Zo-Bro-23**
Added an easy way to deploy using services other than Vercel

- Added an `express.js` file
- Updated documentation

### CODE REVIEW

**Comment by rickstaa** [comment]
I'm good with this, but I think @anuraghazra had his reservations (see https://github.com/anuraghazra/github-readme-stats/pull/2447#issuecomment-1399223712).

**Comment by Zo-Bro-23** [comment]
> I'm good with this, but I think @anuraghazra had his reservations (see [#2447 (comment)](https://github.com/anuraghazra/github-readme-stats/pull/2447#issuecomment-1399223712)).

The issues @anuraghazra mentioned mainly had to do with code maintenance. This is really lightweight, and adding a single file doesn't affect us in any way. It also saves us the effort when users create issues and discussions regarding this (#2524 for ex). I agree that having `express` as a dependency will bloat the code up for us, and make deployments slower. Instead, this PR provides a compromise between maintainability and convenience. Let me know what you think!

**Comment by rickstaa** [comment]
> > I'm good with this, but I think @anuraghazra had his reservations (see [#2447 (comment)](https://github.com/anuraghazra/github-readme-stats/pull/2447#issuecomment-1399223712)).
> 
> The issues @anuraghazra mentioned mainly had to do with code maintenance. This is really lightweight, and adding a single file doesn't affect us in any way. It also saves us the effort when users create issues and discussions regarding this (#2524 for ex). I agree that having `express` as a dependency will bloat the code up for us, and make deployments slower. Instead, this PR provides a compromise between maintainability and convenience. Let me know what you think!

I agree. I think your PR is a good trade-off. 👍🏻

**Review by rickstaa — APPROVED** [review]

**Comment by Zo-Bro-23** [comment]
@rickstaa can we merge or do you think we should wait for @anuraghazra's opinion? It's a kinda lightweight PR imo.

**Comment by rickstaa** [comment]
> @rickstaa can we merge or do you think we should wait for @anuraghazra's opinion? It's a kinda lightweight PR imo.

I don't mind having this in the main branch, but maybe you can add a quick disclaimer that it is not the official way to cater to Anurag's comment in https://github.com/anuraghazra/github-readme-stats/pull/2447#issuecomment-1399223712:

> There will be other complexities/edge cases to handle if we support express out of the box.

> **Warning**
> This way of using GRS is not officially supported but was added to cater to some particular use cases where Vercel could not be used (e.g. https://github.com/anuraghazra/github-readme-stats/discussions/2341). The support for this method is, therefore, limited.

**Comment by Zo-Bro-23** [comment]
> > @rickstaa can we merge or do you think we should wait for @anuraghazra's opinion? It's a kinda lightweight PR imo.
> 
> I don't mind having this in the main branch, but maybe you can add a quick disclaimer that it is not the official way to cater to Anurag's comment in [#2447 (comment)](https://github.com/anuraghazra/github-readme-stats/pull/2447#issuecomment-1399223712):
> 
> > There will be other complexities/edge cases to handle if we support express out of the box.
> 
> > Warning
> > This way of using GRS is not officially supported but was added to cater to some particular use cases where Vercel could not be used (e.g. #2341). The support for this method is, therefore, limited.
> 
> ```lisp
> > **Warning**
> > This way of using GRS is not officially supported but was added to cater to some particular use cases where Vercel could not be used (e.g. https://github.com/anuraghazra/github-readme-stats/discussions/2341). The support for this method is, therefore, limited.
> ```

Added and merging!

**Pull request merged**
