### PR TITLE
Edited readme_es

### PR DESCRIPTION
**Pull request by nombrekeff**
* Replaced "customizar" with "personalizar"
* Added link to theme preview

### CODE REVIEW

**Comment by nombrekeff** [comment]
Closing PR, duplicate of #119

**Comment by JoseDeFreitas** [comment]
My bad. I created a pull request (#119) and I didn't saw this was created. Please reopen this 😅.

**Comment by nombrekeff** [comment]
Sure, no worries!

**Comment by anuraghazra** [comment]
@JoseDeFreitas should i merge this?

**Comment by nombrekeff** [comment]
Yeah, I think we can merge this one, we had a bit of confusion earlier and made the same PR 😓  All clear now!

**Comment by anuraghazra** [comment]
Okay no problem, LGTM! :)

**Pull request merged**
