### PR TITLE
fix(#291): reduce hide when hide_rank is true

### PR DESCRIPTION
**Pull request by rjoydip**
Closes: #291

### CODE REVIEW

**Review by fabiosangregorio — APPROVED** [review]

**Comment by fabiosangregorio** [comment]
YES! This should be merged.

**Comment by KonradLinkowski** [comment]
Isn't that related to #110?

**Review by jonasbb — APPROVED** [review]

**Comment by KonradLinkowski** [comment]
UP ^

**Comment by anuraghazra** [comment]
Hi @rjoydip I actually got a better solution to this and merged in #721 

Thanks for your PR!

**Pull request closed without merging**
