### PR TITLE
Modified so that the `src/calculateRank.js` link can be used on the repository main screen

### PR DESCRIPTION
**Pull request by Yaminyam**
Modify the path to an absolute path so that you can use the link in other paths, such as the repository main screen.

### CODE REVIEW

**Review by qwerty541 — COMMENTED** [review]
@Yaminyam Thanks for opening pull request!

@rickstaa I think we can merge this pull request as temporary solution for https://github.com/anuraghazra/github-readme-stats/issues/3066. Unfortunately this will not work in vscode locally and in browser when user on not master branch, but it is more important for this link to work on repository main screen. It is very rare situation when you need it somewhere else. What do you think?

**Comment by rickstaa** [comment]
It looks like #3067 fixed all relative links except `vercel.json` and `src/calculaterank.js` 🤔. This is a bug since they should add the `blob/master` prefix. I will contact the support. If they can't fix it, let's use an absolute link. The benefit of a relative link is that it works on all forks and branches.

**Comment by rickstaa** [comment]
@qwerty541, it just became a lot stranger. This bug is only present on GRS. See https://github.com/rickstaa/relative_md_links_file_bug?tab=readme-ov-file 🤔.

**Comment by qwerty541** [comment]
> @qwerty541, it just became a lot stranger. This bug is only present on GRS. See https://github.com/rickstaa/relative_md_links_file_bug?tab=readme-ov-file 🤔. Let's see what the GitHub support says about this.

@rickstaa Yeah, thats strange, i just checked if it works in another repository with same paths https://github.com/qwerty541/relative_md_links_file_bug/tree/qwerty541-patch-1. We also can test if it works in master branch if you are up to merge.

**Comment by rickstaa** [comment]
> > @qwerty541, it just became a lot stranger. This bug is only present on GRS. See https://github.com/rickstaa/relative_md_links_file_bug?tab=readme-ov-file 🤔. Let's see what the GitHub support says about this.
> 
> @rickstaa Yeah, thats strange, i just checked if it works in another repository with same paths https://github.com/qwerty541/relative_md_links_file_bug/tree/qwerty541-patch-1. We also can test if it works in master branch if you are up to merge.

Thanks for debugging! It appears to be a GitHub bug. See https://github.com/anuraghazra/github-readme-stats/issues/3066#issuecomment-1763309576.

**Comment by qwerty541** [comment]
Closing this in favour of https://github.com/anuraghazra/github-readme-stats/pull/3389.

@Yaminyam Thanks for your efforts anyway.

**Pull request closed without merging**
