### PR TITLE
[Theme] Discord theme.

### PR DESCRIPTION
**Pull request by AlphaNecron**

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title_color: <code>#5865f2</code> | icon_color: <code>#57f287</code> | text_color: <code>#ffffff</code> | bg_color: <code>#2c2f33</code>
      
      
Link: https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=5865f2&icon_color=57f287&text_color=ffffff&bg_color=2c2f33&show_icons=true

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=5865f2&icon_color=57f287&text_color=ffffff&bg_color=2c2f33&show_icons=true)
      
      
  
> Hi thanks for the theme contribution, please read our theme contribution guidelines

  
> We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 
  
> Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

**Comment by AlphaNecron** [comment]
Can you change the background color to `#23272A` ?

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title_color: <code>#5865f2</code> | icon_color: <code>#57f287</code> | text_color: <code>#ffffff</code> | bg_color: <code>#23272a</code>
      
      
Link: https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=5865f2&icon_color=57f287&text_color=ffffff&bg_color=23272a&show_icons=true

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=5865f2&icon_color=57f287&text_color=ffffff&bg_color=23272a&show_icons=true)
      
      
  
> Hi thanks for the theme contribution, please read our theme contribution guidelines

  
> We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 
  
> Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

**Comment by AlphaNecron** [comment]
Bump

**Comment by AlphaNecron** [comment]
Bump...

**Comment by Pospelove** [comment]
eueu

**Comment by AlphaNecron** [comment]
Bump

**Comment by AlphaNecron** [comment]
Bump?

**Comment by AlphaNecron** [comment]
Bump

**Comment by anuraghazra** [comment]
**Automated Theme Preview**  
      
      
- :warning: `title_color` does not passes [AA contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=5865f2&bcolor=23272a)


      
title_color: <code>#5865f2</code> | icon_color: <code>#57f287</code> | text_color: <code>#ffffff</code> | bg_color: <code>#23272a</code>
      
      
[Preview Link](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=5865f2&icon_color=57f287&text_color=ffffff&bg_color=23272a&show_icons=true)

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=5865f2&icon_color=57f287&text_color=ffffff&bg_color=23272a&show_icons=true)
      
      
  
Hi, thanks for the theme contribution, please read our theme [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#themes-contribution).  
  
We are currently only accepting color combinations from any VSCode theme or themes which have good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use, then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization)

**Comment by rickstaa** [comment]
@AlphaNecron Thanks for your contribution. Your theme currently does not respect our theme colour guidelines. As a result, I closed it for now. Feel free to create a new pull request in which the title colour visibility is improved.

**Comment by AlphaNecron** [comment]
Oh okay.

**Comment by rickstaa** [comment]
@AlphaNecron I'm currently working through the open pull request. As I already said, I'm happy to reopen if you improve the readability of the title. You can check whether the color is readable enough on https://webaim.org/resources/con.

**Comment by AlphaNecron** [comment]
Uhhh the link is invalid?

**Comment by rickstaa** [comment]
Ah, it looks like it got partially copied. I updated the link.

**Pull request closed without merging**
