### PR TITLE
Add min width languages card

### PR DESCRIPTION
**Pull request by qimolin**

### CODE REVIEW

**Comment by qimolin** [comment]
Implements #1945

**Comment by rickstaa** [comment]
@qimolin Thanks a lot for your contribution! I made some minor changes and merged them into the main branch.

**Comment by Anngoodness** [comment]
# @millette

**Comment by Anngoodness** [comment]
MY~HOPE~MY,BELIEVES

**Comment by Anngoodness** [comment]
@2022™MYHOPE.MYBELIEVES#

**Pull request merged**
