### PR TITLE
Added the City Lights Theme

### PR DESCRIPTION
**Pull request by Ryan-da-ghost**
DEMO : 
Capture

### CODE REVIEW

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title_color: <code>#5D8CB3</code> | icon_color: <code>#4798FF</code> | text_color: <code>#718CA1</code> | bg_color: <code>#1D252C</code>
      
      
Link: https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=5D8CB3&icon_color=4798FF&text_color=718CA1&bg_color=1D252C&show_icons=true

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=5D8CB3&icon_color=4798FF&text_color=718CA1&bg_color=1D252C&show_icons=true)
      
      
  
> Hi thanks for the theme contribution, please read our theme contribution guidelines

  
> We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 
  
> Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

**Comment by Ryan-da-ghost** [comment]
The theme, is based on City Lights

**Comment by Ryan-da-ghost** [comment]
Why isn't My theme being added ?

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title_color: <code>#5D8CB3</code> | icon_color: <code>#4798FF</code> | text_color: <code>#718CA1</code> | bg_color: <code>#1D252C</code>
      
      
Link: https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=5D8CB3&icon_color=4798FF&text_color=718CA1&bg_color=1D252C&show_icons=true

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=5D8CB3&icon_color=4798FF&text_color=718CA1&bg_color=1D252C&show_icons=true)
      
      
  
> Hi thanks for the theme contribution, please read our theme contribution guidelines

  
> We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 
  
> Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

**Comment by Ryan-da-ghost** [comment]
i have changed the name to the city lights theme because its the same as this

**Comment by anuraghazra** [comment]
Theme preview (bot)  
      
      
title_color: <code>#5D8CB3</code> | icon_color: <code>#4798FF</code> | text_color: <code>#718CA1</code> | bg_color: <code>#1D252C</code>
      
      
Link: https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=5D8CB3&icon_color=4798FF&text_color=718CA1&bg_color=1D252C&show_icons=true

      
[](https://github-readme-stats.vercel.app/api?username=anuraghazra&title_color=5D8CB3&icon_color=4798FF&text_color=718CA1&bg_color=1D252C&show_icons=true)
      
      
  
> Hi thanks for the theme contribution, please read our theme contribution guidelines

  
> We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

  
> Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card [customization options](https://github.com/anuraghazra/github-readme-stats#customization) 
  
> Read our [contribution guidelines](https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) for more info

**Pull request merged**
