### PR TITLE
Add black and white theme

### PR DESCRIPTION
**Pull request by KevinScruff**

### CODE REVIEW

**Comment by anuraghazra** [comment]
@KevinScruff please add screenshot

**Comment by KevinScruff** [comment]
> @KevinScruff please add screenshot

image

**Comment by anuraghazra** [comment]
Hmmm too simple, don't even need to add to the themes list probably. 

>  NOTE: If you are contributing your theme just because you are using it personally, then you can customize the looks of your card with URL params instead.

**Comment by HPaulson** [comment]
@anuraghazra I'd have to disagree... this theme matches the GitHub colors, and I'd def. use this over the default theme I'm using currently since it matches the rest of GitHub. Although fairly simple, I don't think that's a reason for denial since it very much so matches github's style.

**Comment by KevinScruff** [comment]
> Hmmm too simple, don't even need to add to the themes list probably.
> 
> > NOTE: If you are contributing your theme just because you are using it personally, then you can customize the looks of your card with URL params instead.

Thank you for your time.

**Comment by anuraghazra** [comment]
> @anuraghazra I'd have to disagree... this theme matches the GitHub colors, and I'd def. use this over the default theme I'm using currently since it matches the rest of GitHub. Although fairly simple, I don't think that's a reason for denial since it very much so matches github's style.

I'm not sure how are you saying it matches the Github's style. it's literally just black & white (as the title says) 

see: https://brandcolors.net/b/github

**Comment by HPaulson** [comment]
@anuraghazra Yes it is just black and white, but so it GitHub. Those other colors are for PR icons, etc. GitHub sometimes uses the purple, but their entire UI is black & white
image

**Comment by anuraghazra** [comment]
> @anuraghazra Yes it is just black and white, but so it GitHub. Those other colors are for PR icons, etc. GitHub sometimes uses the purple, but their entire UI is black & white (and some greys, which- is a mix of black and white) with the exception of the status (which is still white on desktop version of the site)

It's not pure black. its #24292e

**Comment by KevinScruff** [comment]
> @anuraghazra Yes it is just black and white, but so it GitHub. Those other colors are for PR icons, etc. GitHub sometimes uses the purple, but their entire UI is black & white (and some greys, which- is a mix of black and white) with the exception of the status (which is still white on desktop version of the site)
> image

Also, the readme theme is black and white.
image

**Comment by HPaulson** [comment]
@KevinScruff Just checked your page, and that actually looks VERY good in the readme (since markdown is black text on white background, like this theme). If this is accepted, I'll totally be using it, and I'm sure many others would too!

**Comment by anuraghazra** [comment]
> @KevinScruff Just checked your page, and that actually looks VERY good in the readme (since markdown is black text on white background, like this theme). If this is accepted, I'll totally be using it, and I'm sure many others would too!

He is using #24292e in his readme and PR is total black 000000

**Comment by HPaulson** [comment]
@anuraghazra Then they're very similar... @KevinScruff would you be down to change the 000000 to the grey in readme that is very slightly different?

**Comment by HPaulson** [comment]
Actually @anuraghazra you raise a good point... maybe I just like the idea of a theme that looks just like GitHub? It would be cool to have a theme using their exact colors on the profile page, or even having icon colors be the same as GitHub's (like yellow star, green PR icon, etc)... just throwing out that idea- maybe the idea is good but this just isn't the PR for what I'm thinking, and this is just meant to be simply black and white as the title suggests (where as I thought it looked cool being close to GitHub's colors)

**Comment by KevinScruff** [comment]
> > @KevinScruff Just checked your page, and that actually looks VERY good in the readme (since markdown is black text on white background, like this theme). If this is accepted, I'll totally be using it, and I'm sure many others would too!
> 
> He is using #24292e in his readme and PR is total black 000000

In the screenshot, the color was 000000.

**Comment by anuraghazra** [comment]
> In the screenshot, the color was 000000.

yeah i noticed thats why i said it does not match the gtihub color scheme

**Comment by KevinScruff** [comment]
> > In the screenshot, the color was 000000.
> 
> yeah i noticed, that's why i said it does not match the github color scheme
It's still black.
It's just not 000000.

**Comment by KevinScruff** [comment]
> > > In the screenshot, the color was 000000.
> > 
> > 
> > yeah i noticed, that's why i said it does not match the github color scheme
> 
> It's still black.
> It's just not 000000.

And 000000 also matches with the readme.

**Comment by anuraghazra** [comment]
> > > In the screenshot, the color was 000000.
> > 
> > 
> > yeah i noticed, that's why i said it does not match the github color scheme
> 
> It's still black.
> It's just not 000000.

000000 is pure black.
24292e isn't pure black and a bit softer thats why it looks good.

**Comment by KevinScruff** [comment]
> > > > In the screenshot, the color was 000000.
> > > 
> > > 
> > > yeah i noticed, that's why i said it does not match the github color scheme
> > 
> > 
> > It's still black.
> > It's just not 000000.
> 
> 000000 is pure black.
> 24292e isn't pure black and a bit softer thats why it looks good.

You can change the color to 24292e  after the merge.
It will still be black and white.

**Comment by anuraghazra** [comment]
> It will still be black and white.

https://uxmovement.com/content/why-you-should-never-use-pure-black-for-text-or-backgrounds/
https://ianstormtaylor.com/design-tip-never-use-black/

**Comment by KevinScruff** [comment]
> > > > > In the screenshot, the color was 000000.
> > > > 
> > > > 
> > > > yeah i noticed, that's why i said it does not match the github color scheme
> > > 
> > > 
> > > It's still black.
> > > It's just not 000000.
> > 
> > 
> > 000000 is pure black.
> > 24292e isn't pure black and a bit softer thats why it looks good.
> 
> You can change the color to 24292e after the merge.
> It will still be black and white.

Or you can close this PR.
I'll create a new PR with the name match-with-readme and color 24292e.

**Comment by anuraghazra** [comment]
You deleted your fork, otherwise i would edit it. okay closing it. open a new one. everything same just the color 24292e

**Comment by KevinScruff** [comment]
> You deleted your fork, otherwise i would edit it. okay closing it. open a new one. everything same just the color 24292e

#339

**Pull request closed without merging**
